// SPDX-License-Identifier: Apache-2.0
//! Host tests for the reference handler: the shared fixture corpus driven
//! through the generated byte ABI (the same exports the platform executor
//! calls), plus the input-contract refusals. The decision core is exercised
//! exactly as the module will run: envelope in, outcome document out.

use std::sync::Mutex;

use breg_wasm_handler_template::breg_wasm_abi;
use serde_json::{Value, json};

/// The ABI's result window and allocator are crate-global statics, so the
/// tests that drive them take turns.
static ABI_LOCK: Mutex<()> = Mutex::new(());

fn corpus() -> Vec<(String, Value, Value)> {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../fixtures/normalize-phone-cases.json"
    );
    let document: Value = serde_json::from_str(&std::fs::read_to_string(path).unwrap())
        .expect("the fixture corpus parses");
    document["cases"]
        .as_array()
        .expect("the corpus carries a cases array")
        .iter()
        .map(|case| {
            (
                case["name"].as_str().expect("a case name").to_owned(),
                case["inputs"].clone(),
                case["expected"].clone(),
            )
        })
        .collect()
}

/// Drive the generated exports on the host: allocate, copy the envelope in,
/// call `handle`, read the result window back. `None` means the guest
/// reported a nonzero status.
fn run_through_abi(inputs: &Value) -> Option<Value> {
    let _guard = ABI_LOCK
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner());
    let envelope = serde_json::to_vec(&json!({"inputs": inputs})).unwrap();
    let pointer = breg_wasm_abi::alloc(envelope.len());
    assert!(!pointer.is_null(), "the host allocator succeeds");
    let buffer = unsafe { std::slice::from_raw_parts_mut(pointer, envelope.len()) };
    buffer.copy_from_slice(&envelope);
    let status = breg_wasm_abi::handle(pointer as *const u8, envelope.len());
    assert_eq!(status, 0, "every corpus case is a well-formed request");
    let len = breg_wasm_abi::result_len();
    let pointer = breg_wasm_abi::result_ptr() as *const u8;
    let document = unsafe { std::slice::from_raw_parts(pointer, len) }.to_vec();
    Some(serde_json::from_slice(&document).expect("the outcome window holds one JSON document"))
}

#[test]
fn every_fixture_case_produces_its_exact_outcome_document() {
    for (name, inputs, expected) in corpus() {
        let outcome = run_through_abi(&inputs)
            .unwrap_or_else(|| panic!("{name}: expected an outcome document"));
        assert_eq!(outcome, expected, "{name}: the outcome document differs");
    }
}

#[test]
fn a_failed_handle_clears_the_result_window() {
    let _guard = ABI_LOCK
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner());
    // A null pointer or zero length never reaches the handler.
    let status = breg_wasm_abi::handle(std::ptr::null(), 0);
    assert_eq!(status, 1, "an empty request is malformed");
    assert_eq!(breg_wasm_abi::result_len(), 0, "no outcome is stored");
    assert!(breg_wasm_abi::result_ptr().is_null());
}

#[test]
fn input_contract_violations_are_malformed_requests() {
    for (name, inputs) in [
        ("missing raw-phone", json!({"default-region": "MR"})),
        (
            "null raw-phone",
            json!({"raw-phone": null, "default-region": "MR"}),
        ),
        (
            "numeric raw-phone",
            json!({"raw-phone": 22123456, "default-region": "MR"}),
        ),
        (
            "missing default-region",
            json!({"raw-phone": "22 12 34 56"}),
        ),
    ] {
        let _guard = ABI_LOCK
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner());
        let envelope = serde_json::to_vec(&json!({"inputs": inputs})).unwrap();
        let pointer = breg_wasm_abi::alloc(envelope.len());
        let buffer = unsafe { std::slice::from_raw_parts_mut(pointer, envelope.len()) };
        buffer.copy_from_slice(&envelope);
        let status = breg_wasm_abi::handle(pointer as *const u8, envelope.len());
        assert_eq!(status, 1, "{name}: expected status 1 (malformed request)");
        assert_eq!(
            breg_wasm_abi::result_len(),
            0,
            "{name}: no outcome may be stored"
        );
    }
}

#[test]
fn the_warm_up_discards_its_outcomes_and_leaves_the_window_empty() {
    let _guard = ABI_LOCK
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner());
    breg_wasm_handler_template::warm();
    assert_eq!(breg_wasm_abi::result_len(), 0);
}
