/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class BaseRegistryClient {
  constructor(config: any)
  health(): Promise<CompleteOutcome>
  ready(): Promise<CompleteOutcome>
  openapi(accessProfile?: string | undefined | null): Promise<RawOutcome>
  registryMetadata(accessProfile?: string | undefined | null): Promise<RawOutcome>
  registryContract(accessProfile?: string | undefined | null): Promise<BRegMetadata>
  entitySchema(entityIdentifier: string, accessProfile?: string | undefined | null): Promise<RawOutcome>
  getRecord(entityRoute: string, recordIdentifier: string, options?: any | undefined | null): Promise<CompleteOutcome>
  listRecords(entityRoute: string, options?: any | undefined | null): Promise<PageOutcome>
  continueList(value: any): Promise<PageOutcome>
  lookupRecord(entityRoute: string, selector: string, values?: any | undefined | null, options?: any | undefined | null): Promise<CompleteOutcome>
  createRecord(binding: BRegCreateBinding, data: any, idempotencyKey: string, formatValue?: string | undefined | null): Promise<CompleteOutcome>
  patchRecord(binding: BRegPatchBinding, recordIdentifier: string, etag: string, operations: any, idempotencyKey: string, formatValue?: string | undefined | null): Promise<CompleteOutcome>
  /**
   * Replace one governed attachment slot with exact bytes. The prepared
   * upload already satisfies the slot's served size and content-type policy.
   */
  uploadAttachment(slot: BRegAttachmentSlot, recordIdentifier: string, etag: string, upload: BRegAttachmentUpload, idempotencyKey: string, formatValue?: string | undefined | null): Promise<CompleteOutcome>
  /** Read the exact bytes one governed slot holds for one proposal version. */
  downloadAttachment(slot: BRegAttachmentSlot, recordIdentifier: string, proposalVersion: number): Promise<RawOutcome>
  /** Empty one governed attachment slot. */
  deleteAttachment(slot: BRegAttachmentSlot, recordIdentifier: string, etag: string, idempotencyKey: string, formatValue?: string | undefined | null): Promise<CompleteOutcome>
  lifecycleActions(authority: BRegLifecycleAuthority, record: any, formatValue?: string | undefined | null): Array<BRegLifecycleAction>
  executeLifecycleAction(action: BRegLifecycleAction, idempotencyKey: string): Promise<CompleteOutcome>
  getRecordJson(entityRoute: string, recordIdentifier: string, options?: any | undefined | null): Promise<JsonOutcome>
  listRecordsJson(entityRoute: string, options?: any | undefined | null): Promise<JsonOutcome>
  continueListJson(value: any): Promise<JsonOutcome>
  lookupRecordJson(entityRoute: string, selector: string, valuesJson?: string | undefined | null, options?: any | undefined | null): Promise<JsonOutcome>
  createRecordJson(binding: BRegCreateBinding, dataJson: string, idempotencyKey: string, formatValue?: string | undefined | null): Promise<JsonOutcome>
  patchRecordJson(binding: BRegPatchBinding, recordIdentifier: string, etag: string, operationsJson: string, idempotencyKey: string, formatValue?: string | undefined | null): Promise<JsonOutcome>
  uploadAttachmentJson(slot: BRegAttachmentSlot, recordIdentifier: string, etag: string, upload: BRegAttachmentUpload, idempotencyKey: string, formatValue?: string | undefined | null): Promise<JsonOutcome>
  deleteAttachmentJson(slot: BRegAttachmentSlot, recordIdentifier: string, etag: string, idempotencyKey: string, formatValue?: string | undefined | null): Promise<JsonOutcome>
  lifecycleActionsJson(authority: BRegLifecycleAuthority, recordJson: string, formatValue?: string | undefined | null): Array<BRegLifecycleAction>
  executeLifecycleActionJson(action: BRegLifecycleAction, idempotencyKey: string): Promise<JsonOutcome>
}

/** Opaque governed attachment slot selected from metadata fetched by this client source. */
export declare class BRegAttachmentSlot {
  get slotIdentifier(): string
  get entityIdentifier(): string
  get accessProfile(): string
  get requiredForSubmit(): boolean
  /** Largest body the served slot policy accepts, in bytes. */
  get maximumBytes(): number
  get contentTypes(): Array<string>
  /** Authored sensitivity of this slot's content. */
  get classification(): string
  get canDownload(): boolean
  get canUpload(): boolean
  get canRemove(): boolean
  acceptsContentType(contentType: string): boolean
  /** Bind exact bytes to this slot. Refusals happen here, before any request. */
  prepareUpload(contentType: string, body: Buffer): BRegAttachmentUpload
  /** Read this slot's engine-owned state out of one Registry Record envelope. */
  valueIn(record: any, formatValue?: string | undefined | null): any
}
export type AttachmentSlot = BRegAttachmentSlot

/** Opaque bytes already accepted by one slot's served upload policy. */
export declare class BRegAttachmentUpload {
  get contentType(): string
  get byteSize(): number
}
export type AttachmentUpload = BRegAttachmentUpload

export declare class BRegCreateBinding {

}
export type CreateBinding = BRegCreateBinding

export declare class BRegLifecycleAction {
  withReason(reason: string): BRegLifecycleAction
  get bodyJson(): string
  get reviewJson(): string | null
  get operation(): string
  get stage(): string | null
  get href(): string
  get body(): any
  get review(): any | null
}
export type LifecycleAction = BRegLifecycleAction

export declare class BRegLifecycleAuthority {

}
export type LifecycleAuthority = BRegLifecycleAuthority

export declare class BRegMetadata {
  /** Caller-filtered inert descriptors. Selectors below remain the only authority constructors. */
  get operations(): any
  get registryIdentifier(): string
  get registryVersion(): string
  get registryRevision(): string
  get traceId(): string
  get etag(): string | null
  selectCreate(operationIdentifier: string, expectedProfile: string): BRegCreateBinding
  selectPatch(operationIdentifier: string, expectedProfile: string): BRegPatchBinding
  selectLifecycle(entityIdentifier: string, expectedProfile: string): BRegLifecycleAuthority
  selectAttachments(entityIdentifier: string, expectedProfile: string): Array<BRegAttachmentSlot>
}
export type Metadata = BRegMetadata

export declare class BRegPatchBinding {

}
export type PatchBinding = BRegPatchBinding

export interface CompleteOutcome {
  kind: string
  value: any
  traceId: string
  etag?: string
  location?: string
}

/** Validated product result serialized before the JavaScript number boundary. */
export interface JsonOutcome {
  kind: string
  valueJson: string
  continuation?: any
  traceId: string
  etag?: string
  location?: string
}

export interface PageOutcome {
  kind: string
  value: any
  continuation?: any
  traceId: string
  etag?: string
}

export interface RawOutcome {
  kind: string
  body: Buffer
  mediaType: string
  traceId: string
  etag?: string
}
