// SPDX-License-Identifier: Apache-2.0
//! Integration tests for `XlsxFormat`.
//!
//! Each test loads a fixture from `tests/fixtures_xlsx/`, calls
//! `XlsxFormat::decode`, and asserts the resulting `DecodedStream`.
//!
//! Fixtures are generated by `tests/fixtures_xlsx/generate.sh` (Python +
//! openpyxl). Commit the `.xlsx` files so CI does not need openpyxl.

mod support;

use std::fs;
use std::path::Path;
use std::pin::Pin;
use std::sync::{Arc, Mutex};

use datafusion::arrow::array::{
    Array, BooleanArray, Date32Array, Float64Array, Int64Array, StringArray,
};
use datafusion::arrow::datatypes::{DataType, TimeUnit};
use futures::StreamExt;
use tokio::io::AsyncRead;

use registry_relay::config::{FieldConfig, FieldType, ResourceConfig, SchemaConfig};
use registry_relay::format::xlsx::XlsxFormat;
use registry_relay::format::{Format, FormatError, FormatHints};
use registry_relay::ingest::declared_schema::{DeclaredField, DeclaredSchema};
use registry_relay::ingest::validate_xlsx_source_bytes;

// ── helpers ──────────────────────────────────────────────────────────────────

#[derive(Clone, Default)]
struct SharedLog(Arc<Mutex<Vec<u8>>>);

struct SharedLogWriter(Arc<Mutex<Vec<u8>>>);

impl<'a> tracing_subscriber::fmt::MakeWriter<'a> for SharedLog {
    type Writer = SharedLogWriter;

    fn make_writer(&'a self) -> Self::Writer {
        SharedLogWriter(Arc::clone(&self.0))
    }
}

impl std::io::Write for SharedLogWriter {
    fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
        self.0
            .lock()
            .expect("log buffer lock")
            .extend_from_slice(buf);
        Ok(buf.len())
    }

    fn flush(&mut self) -> std::io::Result<()> {
        Ok(())
    }
}

fn fixture(name: &str) -> Pin<Box<dyn AsyncRead + Send + Unpin>> {
    Box::pin(std::io::Cursor::new(fixture_bytes(name)))
}

fn fixture_bytes(name: &str) -> Vec<u8> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures_xlsx")
        .join(name);
    fs::read(&path).unwrap_or_else(|e| panic!("could not read {name}: {e}"))
}

fn hints_default() -> FormatHints {
    FormatHints {
        sheet: None,
        header_row: Some(1),
        data_range: None,
        delimiter: None,
        quote: None,
        declared: DeclaredSchema::empty(),
    }
}

fn schema_with(fields: Vec<DeclaredField>) -> Arc<DeclaredSchema> {
    Arc::new(DeclaredSchema {
        strict: false,
        fields,
    })
}

fn field(name: &str, ty: FieldType) -> DeclaredField {
    DeclaredField {
        name: name.to_string(),
        ty,
        nullable: true,
        concept_uri: None,
        codelist: None,
        unit: None,
        language: None,
    }
}

// ── Test 1 ────────────────────────────────────────────────────────────────────

/// No sheet hint: should pick the first sheet ("data") and decode all 5 rows.
/// Asserts row count and Arrow types for each declared column.
#[tokio::test]
async fn decodes_simple_xlsx_first_sheet_by_default() {
    let hints = FormatHints {
        declared: schema_with(vec![
            field("id", FieldType::Integer),
            field("name", FieldType::String),
            field("amount", FieldType::Number),
            field("active", FieldType::Boolean),
            field("joined", FieldType::Date),
        ]),
        ..hints_default()
    };

    let decoded = XlsxFormat::new()
        .decode(fixture("simple.xlsx"), hints)
        .await
        .expect("decode should succeed");

    assert_eq!(
        decoded
            .observed_schema
            .field_with_name("id")
            .unwrap()
            .data_type(),
        &DataType::Int64
    );
    assert_eq!(
        decoded
            .observed_schema
            .field_with_name("name")
            .unwrap()
            .data_type(),
        &DataType::Utf8
    );
    assert_eq!(
        decoded
            .observed_schema
            .field_with_name("amount")
            .unwrap()
            .data_type(),
        &DataType::Float64
    );
    assert_eq!(
        decoded
            .observed_schema
            .field_with_name("active")
            .unwrap()
            .data_type(),
        &DataType::Boolean
    );
    assert_eq!(
        decoded
            .observed_schema
            .field_with_name("joined")
            .unwrap()
            .data_type(),
        &DataType::Date32
    );

    let batches: Vec<_> = decoded.batches.collect::<Vec<_>>().await;
    assert_eq!(batches.len(), 1, "V1 yields one batch");
    let batch = batches[0].as_ref().expect("batch should be Ok");
    assert_eq!(batch.num_rows(), 5, "five data rows");
    assert_eq!(batch.num_columns(), 5);

    // Spot-check the id column.
    let ids = batch
        .column_by_name("id")
        .expect("id column")
        .as_any()
        .downcast_ref::<Int64Array>()
        .expect("id: Int64Array");
    assert_eq!(ids.value(0), 1);
    assert_eq!(ids.value(4), 5);

    // Spot-check name.
    let names = batch
        .column_by_name("name")
        .expect("name column")
        .as_any()
        .downcast_ref::<StringArray>()
        .expect("name: StringArray");
    assert_eq!(names.value(0), "Alice");
    assert_eq!(names.value(1), "Bob");

    // Spot-check amount.
    let amounts = batch
        .column_by_name("amount")
        .expect("amount column")
        .as_any()
        .downcast_ref::<Float64Array>()
        .expect("amount: Float64Array");
    assert!((amounts.value(0) - 1250.50).abs() < 1e-6);

    // Spot-check active.
    let active = batch
        .column_by_name("active")
        .expect("active column")
        .as_any()
        .downcast_ref::<BooleanArray>()
        .expect("active: BooleanArray");
    assert!(active.value(0));
    assert!(!active.value(1));

    // joined is Date32; just assert it's present and non-null.
    let joined = batch
        .column_by_name("joined")
        .expect("joined column")
        .as_any()
        .downcast_ref::<Date32Array>()
        .expect("joined: Date32Array");
    assert!(!joined.is_null(0));
}

// ── Test 2 ────────────────────────────────────────────────────────────────────

/// `sheet: Some("details")` selects the second sheet in `two_sheets.xlsx`.
/// The "summary" sheet only has metadata; "details" has country/population.
#[tokio::test]
async fn selects_named_sheet_when_hint_present() {
    let hints = FormatHints {
        sheet: Some("details".to_string()),
        declared: schema_with(vec![
            field("country", FieldType::String),
            field("population", FieldType::Integer),
        ]),
        ..hints_default()
    };

    let decoded = XlsxFormat::new()
        .decode(fixture("two_sheets.xlsx"), hints)
        .await
        .expect("decode should succeed");

    let batches: Vec<_> = decoded.batches.collect::<Vec<_>>().await;
    let batch = batches[0].as_ref().expect("batch Ok");
    assert_eq!(batch.num_rows(), 3, "three country rows");

    let countries = batch
        .column_by_name("country")
        .expect("country")
        .as_any()
        .downcast_ref::<StringArray>()
        .expect("StringArray");
    assert_eq!(countries.value(0), "France");
    assert_eq!(countries.value(1), "Germany");
    assert_eq!(countries.value(2), "Italy");

    let pops = batch
        .column_by_name("population")
        .expect("population")
        .as_any()
        .downcast_ref::<Int64Array>()
        .expect("Int64Array");
    assert_eq!(pops.value(0), 68_000_000);
}

// ── Test 3 ────────────────────────────────────────────────────────────────────

/// `data_range: Some("A5:E10")` with `header_row: Some(5)`:
/// rows 1-4 are metadata to skip; row 5 is the header; rows 6-10 are data.
#[tokio::test]
async fn honors_data_range_anchors_header_and_body() {
    let hints = FormatHints {
        sheet: None,
        header_row: Some(5),
        data_range: Some("A5:E10".to_string()),
        declared: schema_with(vec![
            field("id", FieldType::Integer),
            field("name", FieldType::String),
            field("amount", FieldType::Number),
            field("active", FieldType::Boolean),
            field("joined", FieldType::Date),
        ]),
        ..hints_default()
    };

    let decoded = XlsxFormat::new()
        .decode(fixture("with_data_range.xlsx"), hints)
        .await
        .expect("decode should succeed");

    let batches: Vec<_> = decoded.batches.collect::<Vec<_>>().await;
    let batch = batches[0].as_ref().expect("batch Ok");
    assert_eq!(
        batch.num_rows(),
        5,
        "five data rows after skipping metadata"
    );
    assert_eq!(batch.num_columns(), 5);

    let ids = batch
        .column_by_name("id")
        .expect("id")
        .as_any()
        .downcast_ref::<Int64Array>()
        .expect("Int64Array");
    assert_eq!(ids.value(0), 10);
    assert_eq!(ids.value(4), 14);
}

// ── Test 4 ────────────────────────────────────────────────────────────────────

/// Excel serial date cells declared as Date should come out as Arrow Date32.
/// `simple.xlsx` has a "joined" column stored as Excel dates (openpyxl writes
/// them as DateTime values with a date format).
#[tokio::test]
async fn coerces_excel_date_serial_to_date32() {
    let hints = FormatHints {
        declared: schema_with(vec![
            field("id", FieldType::Integer),
            field("name", FieldType::String),
            field("amount", FieldType::Number),
            field("active", FieldType::Boolean),
            field("joined", FieldType::Date),
        ]),
        ..hints_default()
    };

    let decoded = XlsxFormat::new()
        .decode(fixture("simple.xlsx"), hints)
        .await
        .expect("decode should succeed");

    assert_eq!(
        decoded
            .observed_schema
            .field_with_name("joined")
            .unwrap()
            .data_type(),
        &DataType::Date32
    );

    let batches: Vec<_> = decoded.batches.collect::<Vec<_>>().await;
    let batch = batches[0].as_ref().expect("batch Ok");
    let joined = batch
        .column_by_name("joined")
        .expect("joined")
        .as_any()
        .downcast_ref::<Date32Array>()
        .expect("Date32Array");

    // Alice's date is 2020-01-15; days since UNIX epoch (1970-01-01) = 18276
    let expected_days = (date_to_days(2020, 1, 15)) as i32;
    assert_eq!(joined.value(0), expected_days, "Alice: 2020-01-15");

    // Eve's date is 2018-07-22
    let expected_eve = date_to_days(2018, 7, 22) as i32;
    assert_eq!(joined.value(4), expected_eve, "Eve: 2018-07-22");
}

/// Returns days since 1970-01-01 (UNIX epoch) for a given date.
fn date_to_days(year: i32, month: u32, day: u32) -> i64 {
    // Simple calculation: use chrono-compatible logic via time crate
    // We compute based on known leap-year rules.
    let y = year;
    let m = month as i32;
    let d = day as i32;
    // Days from 1970-01-01
    let days_from_year = |yr: i32| -> i64 {
        let yr = yr as i64 - 1;
        365 * yr + yr / 4 - yr / 100 + yr / 400
    };
    let days_in_months = [0i64, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334];
    let is_leap = (y % 4 == 0 && y % 100 != 0) || (y % 400 == 0);
    let leap_day = if is_leap && m > 2 { 1i64 } else { 0 };
    let doy = days_in_months[(m - 1) as usize] + d as i64 + leap_day;
    days_from_year(y) + doy - days_from_year(1970) - 1
}

// ── Test 5 ────────────────────────────────────────────────────────────────────

/// A column declared as Date that contains a non-parsable string cell should
/// yield `FormatError::Parse` with row and column context.
#[tokio::test]
async fn rejects_mistyped_date_column_with_parse_error() {
    let hints = FormatHints {
        declared: schema_with(vec![
            field("id", FieldType::Integer),
            field("name", FieldType::String),
            field("joined", FieldType::Date),
        ]),
        ..hints_default()
    };

    let result = XlsxFormat::new()
        .decode(fixture("mistyped_date.xlsx"), hints)
        .await;

    match result {
        Err(FormatError::Parse(msg)) => {
            assert!(
                msg.contains("row"),
                "parse error should have context: {msg}"
            );
            assert!(
                !msg.contains("not-a-date"),
                "parse error must not echo spreadsheet values: {msg}"
            );
        }
        Ok(decoded) => {
            // Error may also surface in the batch stream (acceptable).
            let batches: Vec<_> = decoded.batches.collect::<Vec<_>>().await;
            let has_error = batches.iter().any(|b| b.is_err());
            assert!(has_error, "expected a parse error for mistyped date");
            let err_msg = batches
                .iter()
                .filter_map(|b| b.as_ref().err())
                .next()
                .unwrap()
                .to_string();
            assert!(
                err_msg.contains("row"),
                "parse error should have context: {err_msg}"
            );
            assert!(
                !err_msg.contains("not-a-date"),
                "parse error must not echo spreadsheet values: {err_msg}"
            );
        }
        Err(other) => {
            panic!("expected FormatError::Parse, got: {other}");
        }
    }
}

// ── Test 6 ────────────────────────────────────────────────────────────────────

/// With `DeclaredSchema::empty()`, all columns from `simple.xlsx` should be
/// inferred and default to Utf8 (since the decoder has no type hints).
#[tokio::test]
async fn infers_utf8_when_no_declared_schema() {
    let decoded = XlsxFormat::new()
        .decode(fixture("simple.xlsx"), hints_default())
        .await
        .expect("decode should succeed");

    let schema = &decoded.observed_schema;
    for f in schema.fields() {
        assert_eq!(
            *f.data_type(),
            DataType::Utf8,
            "field {} should be Utf8 without declared schema",
            f.name()
        );
    }

    let batches: Vec<_> = decoded.batches.collect::<Vec<_>>().await;
    let batch = batches[0].as_ref().expect("batch Ok");
    assert_eq!(batch.num_rows(), 5);
    assert_eq!(batch.num_columns(), 5);
}

// ── Decompression-bomb guard (security review 2026-05-16) ─────────────────

/// Build a minimal, valid XLSX (a ZIP) with one worksheet.
fn build_minimal_xlsx(sheet: &str) -> Vec<u8> {
    use std::io::Write;
    use zip::write::SimpleFileOptions;
    use zip::ZipWriter;

    let content_types = br#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
</Types>"#;

    let root_rels = br#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>"#;

    let workbook = br#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
          xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <sheets>
    <sheet name="data" sheetId="1" r:id="rId1"/>
  </sheets>
</workbook>"#;

    let workbook_rels = br#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
</Relationships>"#;

    let mut buf: Vec<u8> = Vec::new();
    {
        let cursor = std::io::Cursor::new(&mut buf);
        let mut zip = ZipWriter::new(cursor);
        let opts =
            SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated);

        zip.start_file("[Content_Types].xml", opts).unwrap();
        zip.write_all(content_types).unwrap();
        zip.start_file("_rels/.rels", opts).unwrap();
        zip.write_all(root_rels).unwrap();
        zip.start_file("xl/workbook.xml", opts).unwrap();
        zip.write_all(workbook).unwrap();
        zip.start_file("xl/_rels/workbook.xml.rels", opts).unwrap();
        zip.write_all(workbook_rels).unwrap();
        zip.start_file("xl/worksheets/sheet1.xml", opts).unwrap();
        zip.write_all(sheet.as_bytes()).unwrap();
        zip.finish().unwrap();
    }
    buf
}

/// Build a minimal, valid XLSX (a ZIP) whose `<dimension>` element advertises
/// a huge cell count while the on-disk payload is tiny. Used to
/// reproduce the XLSX cell-count bomb guard.
///
/// `dim_ref` is the A1-notation reference to embed in the sheet's `<dimension>`
/// element (e.g. `"A1:Z10000000"` for a 26 col x 10M row sheet).
fn build_bomb_xlsx(dim_ref: &str) -> Vec<u8> {
    // The sheet declares a giant dimension via `<dimension ref="...">`,
    // but the actual <sheetData> contains a single inline-string cell.
    build_minimal_xlsx(&format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <dimension ref="{dim_ref}"/>
  <sheetData>
    <row r="1"><c r="A1" t="inlineStr"><is><t>hdr</t></is></c></row>
  </sheetData>
</worksheet>"#
    ))
}

fn build_formula_xlsx() -> Vec<u8> {
    build_minimal_xlsx(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <dimension ref="A1:B2"/>
  <sheetData>
    <row r="1">
      <c r="A1" t="inlineStr"><is><t>id</t></is></c>
      <c r="B1" t="inlineStr"><is><t>amount</t></is></c>
    </row>
    <row r="2">
      <c r="A2"><v>1</v></c>
      <c r="B2"><f>A2*2</f><v>2</v></c>
    </row>
  </sheetData>
</worksheet>"#,
    )
}

fn build_uncached_formula_xlsx() -> Vec<u8> {
    build_minimal_xlsx(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <dimension ref="A1:B2"/>
  <sheetData>
    <row r="1">
      <c r="A1" t="inlineStr"><is><t>id</t></is></c>
      <c r="B1" t="inlineStr"><is><t>amount</t></is></c>
    </row>
    <row r="2">
      <c r="A2"><v>1</v></c>
      <c r="B2"><f>A2*2</f></c>
    </row>
  </sheetData>
</worksheet>"#,
    )
}

fn build_strict_validation_xlsx(duplicate_primary_key: bool, extra_column: bool) -> Vec<u8> {
    build_strict_validation_xlsx_with_extra(duplicate_primary_key, extra_column.then_some("extra"))
}

fn build_strict_validation_xlsx_with_extra(
    duplicate_primary_key: bool,
    extra_header_name: Option<&str>,
) -> Vec<u8> {
    let second_id = if duplicate_primary_key { "1" } else { "2" };
    let extra_header = extra_header_name
        .map(|name| format!(r#"<c r="C1" t="inlineStr"><is><t>{name}</t></is></c>"#))
        .unwrap_or_default();
    let extra_first = if extra_header_name.is_some() {
        r#"<c r="C2" t="inlineStr"><is><t>unexpected</t></is></c>"#
    } else {
        ""
    };
    let extra_second = if extra_header_name.is_some() {
        r#"<c r="C3" t="inlineStr"><is><t>unexpected</t></is></c>"#
    } else {
        ""
    };
    let dimension = if extra_header_name.is_some() {
        "A1:C3"
    } else {
        "A1:B3"
    };
    build_minimal_xlsx(&format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <dimension ref="{dimension}"/>
  <sheetData>
    <row r="1">
      <c r="A1" t="inlineStr"><is><t>id</t></is></c>
      <c r="B1" t="inlineStr"><is><t>name</t></is></c>
      {extra_header}
    </row>
    <row r="2">
      <c r="A2"><v>1</v></c>
      <c r="B2" t="inlineStr"><is><t>Alice</t></is></c>
      {extra_first}
    </row>
    <row r="3">
      <c r="A3"><v>{second_id}</v></c>
      <c r="B3" t="inlineStr"><is><t>Bob</t></is></c>
      {extra_second}
    </row>
  </sheetData>
</worksheet>"#
    ))
}

fn build_blank_primary_key_xlsx() -> Vec<u8> {
    build_minimal_xlsx(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <dimension ref="A1:B2"/>
  <sheetData>
    <row r="1">
      <c r="A1" t="inlineStr"><is><t>id</t></is></c>
      <c r="B1" t="inlineStr"><is><t>name</t></is></c>
    </row>
    <row r="2">
      <c r="B2" t="inlineStr"><is><t>Alice</t></is></c>
    </row>
  </sheetData>
</worksheet>"#,
    )
}

fn build_duplicate_header_xlsx(header: &str) -> Vec<u8> {
    build_minimal_xlsx(&format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <dimension ref="A1:B2"/>
  <sheetData>
    <row r="1">
      <c r="A1" t="inlineStr"><is><t>{header}</t></is></c>
      <c r="B1" t="inlineStr"><is><t>{header}</t></is></c>
    </row>
    <row r="2">
      <c r="A2" t="inlineStr"><is><t>left</t></is></c>
      <c r="B2" t="inlineStr"><is><t>right</t></is></c>
    </row>
  </sheetData>
</worksheet>"#
    ))
}

fn build_string_primary_key_xlsx(primary_key: &str) -> Vec<u8> {
    build_minimal_xlsx(&format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <dimension ref="A1:B2"/>
  <sheetData>
    <row r="1">
      <c r="A1" t="inlineStr"><is><t>id</t></is></c>
      <c r="B1" t="inlineStr"><is><t>name</t></is></c>
    </row>
    <row r="2">
      <c r="A2" t="inlineStr"><is><t xml:space="preserve">{primary_key}</t></is></c>
      <c r="B2" t="inlineStr"><is><t>Alice</t></is></c>
    </row>
  </sheetData>
</worksheet>"#
    ))
}

fn build_invalid_calendar_date_xlsx() -> Vec<u8> {
    build_minimal_xlsx(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <dimension ref="A1:B2"/>
  <sheetData>
    <row r="1">
      <c r="A1" t="inlineStr"><is><t>id</t></is></c>
      <c r="B1" t="inlineStr"><is><t>reported_on</t></is></c>
    </row>
    <row r="2">
      <c r="A2"><v>1</v></c>
      <c r="B2" t="inlineStr"><is><t>2024-02-31</t></is></c>
    </row>
  </sheetData>
</worksheet>"#,
    )
}

fn strict_validation_schema(fields: &[(&str, FieldType)]) -> SchemaConfig {
    SchemaConfig {
        strict: true,
        fields: fields
            .iter()
            .map(|(name, field_type)| FieldConfig {
                name: (*name).to_string(),
                r#type: *field_type,
                nullable: false,
                sensitive: true,
                concept_uri: None,
                codelist: None,
                unit: None,
                language: None,
            })
            .collect(),
    }
}

async fn validate_temporary_project_workbook(
    bytes: &[u8],
    schema: &SchemaConfig,
    primary_key: Option<&str>,
) -> Result<(), registry_relay::error::IngestError> {
    let mut resource: ResourceConfig = serde_saphyr::from_str(
        r#"
id: workbook
source:
  type: file
  path: /runtime/workbook.xlsx
  format:
    xlsx:
      sheet: data
      header_row: 1
schema:
  strict: true
  fields: []
"#,
    )
    .expect("resource parses");
    resource.schema = schema.clone();
    resource.primary_key = primary_key.map(str::to_owned);
    let config = support::load_example_config_for_tests("format-xlsx-project-validation");
    validate_xlsx_source_bytes(&config, &resource, bytes).await
}

#[tokio::test]
async fn project_workbook_validation_accepts_exact_validated_bytes() {
    let bytes = build_strict_validation_xlsx(false, false);
    let schema =
        strict_validation_schema(&[("id", FieldType::Integer), ("name", FieldType::String)]);
    validate_temporary_project_workbook(&bytes, &schema, Some("id"))
        .await
        .expect("valid strict workbook");
}

#[tokio::test]
async fn project_workbook_validation_rejects_corrupt_formula_duplicate_and_extra_columns() {
    let id_name_schema =
        strict_validation_schema(&[("id", FieldType::Integer), ("name", FieldType::String)]);
    assert!(
        validate_temporary_project_workbook(b"not an xlsx zip", &id_name_schema, Some("id"))
            .await
            .is_err(),
        "corrupt workbook must fail"
    );
    let formula_schema =
        strict_validation_schema(&[("id", FieldType::Integer), ("amount", FieldType::Number)]);
    assert!(
        validate_temporary_project_workbook(&build_formula_xlsx(), &formula_schema, Some("id"))
            .await
            .is_err(),
        "formula workbook must fail"
    );
    assert!(
        validate_temporary_project_workbook(
            &build_strict_validation_xlsx(true, false),
            &id_name_schema,
            Some("id"),
        )
        .await
        .is_err(),
        "duplicate primary key must fail"
    );
    assert!(
        validate_temporary_project_workbook(
            &build_strict_validation_xlsx(false, true),
            &id_name_schema,
            Some("id"),
        )
        .await
        .is_err(),
        "strict extra column must fail"
    );
}

#[tokio::test]
async fn project_workbook_validation_rejects_one_null_primary_key() {
    let mut schema =
        strict_validation_schema(&[("id", FieldType::Integer), ("name", FieldType::String)]);
    schema.fields[0].nullable = true;

    assert!(
        validate_temporary_project_workbook(&build_blank_primary_key_xlsx(), &schema, Some("id"))
            .await
            .is_err(),
        "a primary key cannot be null even when its field is declared nullable"
    );
}

#[tokio::test]
async fn xlsx_decode_rejects_duplicate_header_names_without_echoing_them() {
    const SENTINEL: &str = "country-sensitive-duplicate-header";
    let result = XlsxFormat::new()
        .decode(
            Box::pin(std::io::Cursor::new(build_duplicate_header_xlsx(SENTINEL))),
            hints_default(),
        )
        .await;

    match result {
        Err(FormatError::Parse(message)) => {
            assert!(message.contains("header names must be unique"), "{message}");
            assert!(!message.contains(SENTINEL), "{message}");
        }
        Err(other) => panic!("expected duplicate-header parse error, got {other:?}"),
        Ok(_) => panic!("duplicate XLSX header names must fail"),
    }
}

#[tokio::test]
async fn project_workbook_validation_rejects_whitespace_only_string_primary_key() {
    let schema =
        strict_validation_schema(&[("id", FieldType::String), ("name", FieldType::String)]);

    assert!(
        validate_temporary_project_workbook(
            &build_string_primary_key_xlsx(" \t "),
            &schema,
            Some("id"),
        )
        .await
        .is_err(),
        "a string primary key must contain non-whitespace content"
    );
}

#[tokio::test]
async fn project_workbook_validation_preserves_non_empty_whitespace_bearing_primary_key() {
    let schema =
        strict_validation_schema(&[("id", FieldType::String), ("name", FieldType::String)]);

    validate_temporary_project_workbook(
        &build_string_primary_key_xlsx("  country-1  "),
        &schema,
        Some("id"),
    )
    .await
    .expect("non-empty whitespace-bearing primary key remains valid");
}

#[tokio::test(flavor = "current_thread")]
async fn project_workbook_validation_redacts_sensitive_header_names_from_logs() {
    const SENTINEL: &str = "country-sensitive-header-sentinel";
    let schema =
        strict_validation_schema(&[("id", FieldType::Integer), ("name", FieldType::String)]);
    let logs = SharedLog::default();
    let subscriber = tracing_subscriber::fmt()
        .compact()
        .with_ansi(false)
        .with_target(false)
        .with_max_level(tracing::Level::WARN)
        .with_writer(logs.clone())
        .finish();
    let guard = tracing::subscriber::set_default(subscriber);

    let result = validate_temporary_project_workbook(
        &build_strict_validation_xlsx_with_extra(false, Some(SENTINEL)),
        &schema,
        Some("id"),
    )
    .await;
    drop(guard);
    let rendered = String::from_utf8(logs.0.lock().expect("log buffer lock").clone())
        .expect("captured logs are UTF-8");

    assert!(result.is_err(), "strict extra header must fail");
    assert!(rendered.contains("redacted_sensitive_schema"), "{rendered}");
    assert!(!rendered.contains(SENTINEL), "{rendered}");
}

#[tokio::test]
async fn project_workbook_validation_rejects_invalid_calendar_dates() {
    let schema =
        strict_validation_schema(&[("id", FieldType::Integer), ("reported_on", FieldType::Date)]);

    assert!(
        validate_temporary_project_workbook(
            &build_invalid_calendar_date_xlsx(),
            &schema,
            Some("id"),
        )
        .await
        .is_err(),
        "invalid calendar dates must not be normalized into valid Date32 values"
    );
}

fn build_whitespace_xlsx() -> Vec<u8> {
    build_minimal_xlsx(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <dimension ref="A1:A3"/>
  <sheetData>
    <row r="1"><c r="A1" t="inlineStr"><is><t>value</t></is></c></row>
    <row r="2"><c r="A2" t="inlineStr"><is><t>  ordinary  </t></is></c></row>
    <row r="3"><c r="A3" t="inlineStr"><is><t xml:space="preserve">  preserved  </t></is></c></row>
  </sheetData>
</worksheet>"#,
    )
}

/// The synthetic-bomb helper above must actually be a workbook calamine
/// will open. This sanity test uses a tiny dimension so `worksheet_range`
/// is cheap and the bomb-guard path is not exercised. If this fails, the
/// bomb tests below are also untrustworthy.
#[tokio::test]
async fn synthetic_xlsx_helper_produces_a_workbook_calamine_can_open() {
    let bytes = build_bomb_xlsx("A1:A1");
    let decoded = XlsxFormat::new()
        .decode(Box::pin(std::io::Cursor::new(bytes)), hints_default())
        .await
        .expect("synthetic xlsx should decode");
    let batches: Vec<_> = decoded.batches.collect::<Vec<_>>().await;
    let batch = batches[0].as_ref().expect("batch");
    // Header row only; no data rows.
    assert_eq!(batch.num_rows(), 0);
}

/// Calamine 0.36 follows SpreadsheetML's `xml:space` semantics. Pin both
/// branches so dependency updates cannot silently change ingested identifiers.
#[tokio::test]
async fn honors_xlsx_inline_string_whitespace_semantics() {
    let bytes = build_whitespace_xlsx();
    let decoded = XlsxFormat::new()
        .decode(Box::pin(std::io::Cursor::new(bytes)), hints_default())
        .await
        .expect("synthetic whitespace workbook should decode");
    let batches: Vec<_> = decoded.batches.collect::<Vec<_>>().await;
    let batch = batches[0].as_ref().expect("batch");
    let values = batch
        .column_by_name("value")
        .expect("value column")
        .as_any()
        .downcast_ref::<StringArray>()
        .expect("value: StringArray");

    assert_eq!(values.value(0), "ordinary");
    assert_eq!(values.value(1), "  preserved  ");
}

/// A workbook whose `<dimension>` advertises more than `MAX_XLSX_CELLS`
/// cells must be rejected with a `LimitExceeded` error before calamine's
/// `from_sparse` allocates `vec![Default; height*width]`. Reproduces the
/// XLSX bomb from the 2026-05-16 security review.
///
/// The cap in `src/format/xlsx.rs` is 10_000_000. The dimension below
/// (`A1:L1000000` = 12 columns x 1,000,000 rows = 12,000,000 cells) is
/// just over the cap; small enough that this test does not OOM the
/// process when the cap is absent (defensive against false negatives).
#[tokio::test]
async fn rejects_xlsx_when_declared_dimension_exceeds_cell_cap() {
    let bytes = build_bomb_xlsx("A1:L1000000");
    let result = XlsxFormat::new()
        .decode(Box::pin(std::io::Cursor::new(bytes)), hints_default())
        .await;

    match result {
        Err(FormatError::LimitExceeded(_)) => {}
        Err(other) => panic!("expected FormatError::LimitExceeded, got {other:?}"),
        Ok(_) => panic!("expected the cell-count cap to reject this workbook"),
    }
}

#[tokio::test]
async fn rejects_corrupt_zip_xlsx_as_parse_error() {
    let result = XlsxFormat::new()
        .decode(
            Box::pin(std::io::Cursor::new(b"not an xlsx zip".to_vec())),
            hints_default(),
        )
        .await;

    match result {
        Err(FormatError::Parse(msg)) => {
            assert!(
                msg.contains("failed to open XLSX workbook"),
                "parse error should identify workbook open failure: {msg}"
            );
        }
        Err(other) => panic!("expected FormatError::Parse, got {other:?}"),
        Ok(_) => panic!("expected corrupt XLSX bytes to fail"),
    }
}

#[tokio::test]
async fn rejects_truncated_zip_xlsx_as_parse_error() {
    let mut bytes = fixture_bytes("simple.xlsx");
    bytes.truncate(bytes.len() / 2);

    let result = XlsxFormat::new()
        .decode(Box::pin(std::io::Cursor::new(bytes)), hints_default())
        .await;

    match result {
        Err(FormatError::Parse(_)) => {}
        Err(other) => panic!("expected FormatError::Parse, got {other:?}"),
        Ok(_) => panic!("expected truncated XLSX ZIP to fail"),
    }
}

#[tokio::test]
async fn rejects_formula_cells_inside_configured_range() {
    let hints = FormatHints {
        declared: schema_with(vec![
            field("id", FieldType::Integer),
            field("amount", FieldType::Number),
        ]),
        ..hints_default()
    };

    let result = XlsxFormat::new()
        .decode(Box::pin(std::io::Cursor::new(build_formula_xlsx())), hints)
        .await;

    match result {
        Err(FormatError::Parse(msg)) => {
            assert!(
                msg.contains("formula cell"),
                "parse error should identify formula cell rejection: {msg}"
            );
            assert!(
                !msg.contains("A2*2"),
                "parse error must not echo formula text: {msg}"
            );
        }
        Err(other) => panic!("expected FormatError::Parse, got {other:?}"),
        Ok(_) => panic!("expected formula cells in the ingest range to fail"),
    }
}

#[tokio::test]
async fn rejects_formula_cells_outside_configured_range() {
    let hints = FormatHints {
        data_range: Some("A1:A2".to_string()),
        declared: schema_with(vec![field("id", FieldType::Integer)]),
        ..hints_default()
    };

    let result = XlsxFormat::new()
        .decode(Box::pin(std::io::Cursor::new(build_formula_xlsx())), hints)
        .await;

    match result {
        Err(FormatError::Parse(msg)) => {
            assert!(msg.contains("formula cell"), "{msg}");
            assert!(!msg.contains("A2*2"), "{msg}");
        }
        Err(other) => panic!("expected FormatError::Parse, got {other:?}"),
        Ok(_) => panic!("formula anywhere in the selected worksheet must fail"),
    }
}

#[tokio::test]
async fn rejects_formula_cells_without_cached_value_inside_configured_range() {
    let hints = FormatHints {
        declared: schema_with(vec![
            field("id", FieldType::Integer),
            field("amount", FieldType::Number),
        ]),
        ..hints_default()
    };

    let result = XlsxFormat::new()
        .decode(
            Box::pin(std::io::Cursor::new(build_uncached_formula_xlsx())),
            hints,
        )
        .await;

    match result {
        Err(FormatError::Parse(msg)) => {
            assert!(
                msg.contains("formula cell"),
                "parse error should identify formula cell rejection: {msg}"
            );
            assert!(
                !msg.contains("A2*2"),
                "parse error must not echo formula text: {msg}"
            );
        }
        Err(other) => panic!("expected FormatError::Parse, got {other:?}"),
        Ok(_) => panic!("expected uncached formula cells in the ingest range to fail"),
    }
}

// ── Timestamp test (bonus) ─────────────────────────────────────────────────

/// A column declared as Timestamp from a Date cell (Excel DateTime) should
/// come out as Timestamp(Millisecond, "UTC").
#[tokio::test]
async fn coerces_excel_date_serial_to_timestamp_millis() {
    let hints = FormatHints {
        declared: schema_with(vec![
            field("id", FieldType::Integer),
            field("name", FieldType::String),
            field("amount", FieldType::Number),
            field("active", FieldType::Boolean),
            field("joined", FieldType::Timestamp),
        ]),
        ..hints_default()
    };

    let decoded = XlsxFormat::new()
        .decode(fixture("simple.xlsx"), hints)
        .await
        .expect("decode should succeed");

    let joined_field = decoded.observed_schema.field_with_name("joined").unwrap();
    assert_eq!(
        joined_field.data_type(),
        &DataType::Timestamp(TimeUnit::Millisecond, Some("UTC".into())),
        "joined should be Timestamp(Millisecond, UTC)"
    );
}
