#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["cryptography>=42"]
# ///
"""
Synthetic credential generator for registry-witness performance testing.

Registry Witness clients use the raw bearer/API-key values, while the server
config reads SHA-256 fingerprints from `*_HASH` environment variables.

Emits:

- REGISTRY_WITNESS_BEARER_TOKEN: bearer token bound to the perf verification
  identity (civil_registry + farmer_registry evidence scopes).
- REGISTRY_WITNESS_BEARER_TOKEN_HASH: SHA-256 fingerprint consumed by witness.
- REGISTRY_WITNESS_API_KEY: API-key token bound to the same identity. Used
  in auth_deny.js to verify both header forms exercise the same code path.
- REGISTRY_WITNESS_API_KEY_HASH: SHA-256 fingerprint consumed by witness.
- REGISTRY_WITNESS_NO_SCOPE_TOKEN: valid API-key token bound to an identity
  with no evidence scopes, used to drive the 403 deny path.
- REGISTRY_WITNESS_NO_SCOPE_TOKEN_HASH: SHA-256 fingerprint consumed by witness.
- REGISTRY_WITNESS_AUDIT_HASH_SECRET: HMAC secret for audit primary-key hashing.
- REGISTRY_WITNESS_TOKEN_INVALID: deliberately invalid synthetic value for
  401 tests.
- EVIDENCE_SOURCE_REGISTRY_RELAY_TOKEN: bearer token the witness process
  sends to the source stub. The stub uses the same value to authenticate
  witness's requests.
- REGISTRY_WITNESS_ISSUER_JWK: Ed25519 private JWK consumed by the witness
  credential issuer. Witness validates issuer keys at startup even when
  credential issuance is not exercised, so the value is required.
- Defaults for base URL, claim ids, and the subject pool size that the k6
  scenarios read.

Usage:
    uv run perf/scripts/generate_perf_keys.py --env-file target/perf/perf.env
    uv run perf/scripts/generate_perf_keys.py --env-file target/perf/perf.env --force
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import os
import secrets
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

INVALID_TOKEN_VALUE = "not-a-real-token-xxxx"
ISSUER_KID = "did:web:perf.registry-witness.example#perf-key-1"


def generate_token() -> str:
    return secrets.token_urlsafe(32)


def fingerprint_api_key(token: str) -> str:
    return f"sha256:{hashlib.sha256(token.encode('utf-8')).hexdigest()}"


def _b64url(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def generate_issuer_jwk() -> str:
    """Return a JSON-encoded Ed25519 private JWK with kid + alg fields.

    Matches the issuer_kid declared in perf/config/{small,medium}.yaml.
    Witness reads this via REGISTRY_WITNESS_ISSUER_JWK at startup.
    """
    private = Ed25519PrivateKey.generate()
    seed = private.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption(),
    )
    public = private.public_key().public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    jwk = {
        "kty": "OKP",
        "crv": "Ed25519",
        "alg": "EdDSA",
        "kid": ISSUER_KID,
        "d": _b64url(seed),
        "x": _b64url(public),
    }
    return json.dumps(jwk, separators=(",", ":"))


def build_env_lines(
    bearer: str,
    api_key: str,
    no_scope: str,
    source_bearer: str,
    issuer_jwk: str,
) -> list[str]:
    return [
        "# registry-witness perf test environment",
        "# Generated by generate_perf_keys.py. Do NOT commit this file.",
        "#",
        "# Witness credentials (raw values for clients, hashes for server config)",
        f"REGISTRY_WITNESS_BEARER_TOKEN={bearer}",
        f"REGISTRY_WITNESS_BEARER_TOKEN_HASH={fingerprint_api_key(bearer)}",
        f"REGISTRY_WITNESS_API_KEY={api_key}",
        f"REGISTRY_WITNESS_API_KEY_HASH={fingerprint_api_key(api_key)}",
        f"REGISTRY_WITNESS_NO_SCOPE_TOKEN={no_scope}",
        f"REGISTRY_WITNESS_NO_SCOPE_TOKEN_HASH={fingerprint_api_key(no_scope)}",
        f"REGISTRY_WITNESS_TOKEN_INVALID={INVALID_TOKEN_VALUE}",
        f"REGISTRY_WITNESS_AUDIT_HASH_SECRET={generate_token()}",
        "#",
        "# Token witness sends to the source stub (stub accepts the same value)",
        f"EVIDENCE_SOURCE_REGISTRY_RELAY_TOKEN={source_bearer}",
        "#",
        "# Witness routing and scenario defaults",
        "REGISTRY_WITNESS_BASE_URL=http://127.0.0.1:14255",
        "REGISTRY_WITNESS_PROFILE=medium",
        "REGISTRY_WITNESS_BATCH_SIZE=10",
        "REGISTRY_WITNESS_SUBJECT_COUNT=100000",
        "REGISTRY_WITNESS_CLAIM_EXTRACT=date-of-birth",
        "REGISTRY_WITNESS_CLAIM_CEL=farmer-under-4ha",
        "#",
        "# Source stub bind address (default 127.0.0.1:14256)",
        "EVIDENCE_SOURCE_STUB_BIND=127.0.0.1:14256",
        "#",
        "# Issuer signing key: JSON-encoded Ed25519 private JWK.",
        "# Witness validates this at startup even when issuance is not exercised.",
        f"REGISTRY_WITNESS_ISSUER_JWK={issuer_jwk}",
    ]


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate synthetic credentials for registry-witness perf testing."
    )
    parser.add_argument(
        "--env-file",
        default="target/perf/perf.env",
        help="Destination env file (default: target/perf/perf.env).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing env file.",
    )
    args = parser.parse_args()

    env_path = Path(args.env_file)
    if env_path.exists() and not args.force:
        print(
            f"Error: {env_path} already exists. Use --force to overwrite.",
            file=sys.stderr,
        )
        sys.exit(1)

    env_path.parent.mkdir(parents=True, exist_ok=True)

    env_lines = build_env_lines(
        bearer=generate_token(),
        api_key=generate_token(),
        no_scope=generate_token(),
        source_bearer=generate_token(),
        issuer_jwk=generate_issuer_jwk(),
    )
    env_content = "\n".join(env_lines) + "\n"

    env_path.write_text(env_content, encoding="utf-8")
    os.chmod(env_path, 0o600)

    print(f"Wrote: {env_path}")
    print("Variables written:")
    for name in (
        "REGISTRY_WITNESS_BEARER_TOKEN",
        "REGISTRY_WITNESS_BEARER_TOKEN_HASH",
        "REGISTRY_WITNESS_API_KEY",
        "REGISTRY_WITNESS_API_KEY_HASH",
        "REGISTRY_WITNESS_NO_SCOPE_TOKEN",
        "REGISTRY_WITNESS_NO_SCOPE_TOKEN_HASH",
        "REGISTRY_WITNESS_TOKEN_INVALID",
        "REGISTRY_WITNESS_AUDIT_HASH_SECRET",
        "EVIDENCE_SOURCE_REGISTRY_RELAY_TOKEN",
        "REGISTRY_WITNESS_BASE_URL",
        "REGISTRY_WITNESS_PROFILE",
        "REGISTRY_WITNESS_BATCH_SIZE",
        "REGISTRY_WITNESS_SUBJECT_COUNT",
        "REGISTRY_WITNESS_CLAIM_EXTRACT",
        "REGISTRY_WITNESS_CLAIM_CEL",
        "EVIDENCE_SOURCE_STUB_BIND",
        "REGISTRY_WITNESS_ISSUER_JWK",
    ):
        print(f"  {name}")


if __name__ == "__main__":
    main()
