#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["cryptography>=42"]
# ///
"""
Synthetic credential generator for registry-notary performance testing.

Registry Notary clients use the raw bearer/API-key values, while the server
config reads SHA-256 fingerprints from `*_HASH` environment variables.

Emits:

- REGISTRY_NOTARY_BEARER_TOKEN: bearer token bound to the perf verification
  identity (civil_registry + farmer_registry evidence scopes).
- REGISTRY_NOTARY_BEARER_TOKEN_HASH: SHA-256 fingerprint consumed by notary.
- REGISTRY_NOTARY_API_KEY: API-key token bound to the same identity. Used
  in auth_deny.js to verify both header forms exercise the same code path.
- REGISTRY_NOTARY_API_KEY_HASH: SHA-256 fingerprint consumed by notary.
- REGISTRY_NOTARY_NO_SCOPE_TOKEN: valid API-key token bound to an identity
  with no evidence scopes, used to drive the 403 deny path.
- REGISTRY_NOTARY_NO_SCOPE_TOKEN_HASH: SHA-256 fingerprint consumed by notary.
- REGISTRY_NOTARY_AUDIT_HASH_SECRET: HMAC secret for audit primary-key hashing.
- REGISTRY_NOTARY_TOKEN_INVALID: deliberately invalid synthetic value for
  401 tests.
- EVIDENCE_SOURCE_REGISTRY_RELAY_TOKEN: bearer token the notary process
  sends to the source stub. The stub uses the same value to authenticate
  notary's requests.
- REGISTRY_NOTARY_ISSUER_JWK: Ed25519 private JWK consumed by the notary
  credential issuer. Notary validates issuer keys at startup even when
  credential issuance is not exercised, so the value is required.
- Defaults for base URL, claim ids, and the subject pool size that the k6
  scenarios read.

Usage:
    uv run perf/scripts/generate_perf_keys.py --env-file target/perf/perf.env
    uv run perf/scripts/generate_perf_keys.py --env-file target/perf/perf.env --force
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import os
import re
import secrets
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

INVALID_TOKEN_VALUE = "not-a-real-token-xxxx"
ISSUER_KID = "did:web:perf.registry-notary.example#perf-key-1"
SCRIPT_ROOT = Path(__file__).resolve().parents[1]

AUTH_LIST_RE = re.compile(r"^(\s*)(api_keys|bearer_tokens):\s*$")
ENTRY_ID_RE = re.compile(r"^(\s*)-\s+id:\s*(.+?)\s*$")
FINGERPRINT_NAME_RE = re.compile(r"^(\s*)name:\s*(.+?)\s*$")
FINGERPRINT_COMMITMENT_RE = re.compile(r"^(\s*)commitment:\s*(.+?)\s*$")


def generate_token() -> str:
    return secrets.token_urlsafe(32)


def fingerprint_api_key(token: str) -> str:
    return f"sha256:{hashlib.sha256(token.encode('utf-8')).hexdigest()}"


def credential_commitment(
    credential_type: str,
    credential_id: str,
    credential_fingerprint: str,
) -> str:
    payload = {
        "product": "registry-notary",
        "credential_type": credential_type,
        "credential_id": credential_id,
        "fingerprint": credential_fingerprint,
    }
    encoded = json.dumps(payload, separators=(",", ":")).encode("utf-8")
    return f"sha256:{hashlib.sha256(encoded).hexdigest()}"


def _b64url(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def generate_issuer_jwk() -> str:
    """Return a JSON-encoded Ed25519 private JWK with kid + alg fields.

    Matches the signing key kid declared in perf/config/{small,medium}.yaml.
    Notary reads this via REGISTRY_NOTARY_ISSUER_JWK at startup.
    """
    private = Ed25519PrivateKey.generate()
    seed = private.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption(),
    )
    public = private.public_key().public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    jwk = {
        "kty": "OKP",
        "crv": "Ed25519",
        "alg": "EdDSA",
        "kid": ISSUER_KID,
        "d": _b64url(seed),
        "x": _b64url(public),
    }
    return json.dumps(jwk, separators=(",", ":"))


def build_env_lines(
    bearer: str,
    api_key: str,
    no_scope: str,
    source_bearer: str,
    issuer_jwk: str,
) -> list[str]:
    return [
        "# registry-notary perf test environment",
        "# Generated by generate_perf_keys.py. Do NOT commit this file.",
        "#",
        "# Notary credentials (raw values for clients, hashes for server config)",
        f"REGISTRY_NOTARY_BEARER_TOKEN={bearer}",
        f"REGISTRY_NOTARY_BEARER_TOKEN_HASH={fingerprint_api_key(bearer)}",
        f"REGISTRY_NOTARY_API_KEY={api_key}",
        f"REGISTRY_NOTARY_API_KEY_HASH={fingerprint_api_key(api_key)}",
        f"REGISTRY_NOTARY_NO_SCOPE_TOKEN={no_scope}",
        f"REGISTRY_NOTARY_NO_SCOPE_TOKEN_HASH={fingerprint_api_key(no_scope)}",
        f"REGISTRY_NOTARY_TOKEN_INVALID={INVALID_TOKEN_VALUE}",
        f"REGISTRY_NOTARY_AUDIT_HASH_SECRET={generate_token()}",
        "#",
        "# Token notary sends to the source stub (stub accepts the same value)",
        f"EVIDENCE_SOURCE_REGISTRY_RELAY_TOKEN={source_bearer}",
        "#",
        "# Notary routing and scenario defaults",
        "REGISTRY_NOTARY_BASE_URL=http://127.0.0.1:14255",
        "REGISTRY_NOTARY_PROFILE=medium",
        "REGISTRY_NOTARY_BATCH_SIZE=10",
        "REGISTRY_NOTARY_SUBJECT_COUNT=100000",
        "REGISTRY_NOTARY_CLAIM_EXTRACT=date-of-birth",
        "REGISTRY_NOTARY_CLAIM_CEL=farmer-under-4ha",
        "#",
        "# Source stub bind address (default 127.0.0.1:14256)",
        "EVIDENCE_SOURCE_STUB_BIND=127.0.0.1:14256",
        "#",
        "# Issuer signing key: JSON-encoded Ed25519 private JWK.",
        "# Notary validates this at startup even when issuance is not exercised.",
        f"REGISTRY_NOTARY_ISSUER_JWK={issuer_jwk}",
    ]


def env_values_from_lines(lines: list[str]) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in lines:
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key] = value
    return values


def refresh_config_commitments(values: dict[str, str]) -> int:
    updated = 0
    for path in sorted((SCRIPT_ROOT / "config").glob("*.yaml")):
        if refresh_config_file(path, values):
            updated += 1
    return updated


def refresh_config_file(path: Path, values: dict[str, str]) -> bool:
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    rewritten: list[str] = []
    index = 0
    changed = False
    current_type: str | None = None
    list_indent: int | None = None
    while index < len(lines):
        line = lines[index]
        if match := AUTH_LIST_RE.match(line):
            current_type = "api_key" if match.group(2) == "api_keys" else "bearer_token"
            list_indent = len(match.group(1))
            rewritten.append(line)
            index += 1
            continue
        if current_type is not None and list_indent is not None:
            if line.strip() and leading_spaces(line) <= list_indent:
                current_type = None
                list_indent = None
                rewritten.append(line)
                index += 1
                continue
            if entry_match := ENTRY_ID_RE.match(line):
                entry_indent = len(entry_match.group(1))
                block_end = index + 1
                while block_end < len(lines):
                    candidate = lines[block_end]
                    if candidate.strip() and leading_spaces(candidate) <= list_indent:
                        break
                    if ENTRY_ID_RE.match(candidate) and leading_spaces(candidate) == entry_indent:
                        break
                    block_end += 1
                block, block_changed = refresh_credential_block(
                    lines[index:block_end],
                    current_type,
                    entry_match.group(2).strip(),
                    values,
                )
                rewritten.extend(block)
                changed = changed or block_changed
                index = block_end
                continue
        rewritten.append(line)
        index += 1
    if changed:
        path.write_text("".join(rewritten), encoding="utf-8")
    return changed


def refresh_credential_block(
    block: list[str],
    credential_type: str,
    credential_id: str,
    values: dict[str, str],
) -> tuple[list[str], bool]:
    env_name = None
    commitment_index = None
    for index, line in enumerate(block):
        if name_match := FINGERPRINT_NAME_RE.match(line):
            env_name = name_match.group(2).strip()
        if FINGERPRINT_COMMITMENT_RE.match(line):
            commitment_index = index
    if env_name is None or commitment_index is None:
        return block, False
    if env_name not in values:
        raise KeyError(f"{env_name} is required by a perf config but was not generated")
    commitment = credential_commitment(credential_type, credential_id, values[env_name])
    commitment_match = FINGERPRINT_COMMITMENT_RE.match(block[commitment_index])
    assert commitment_match is not None
    new_line = f"{commitment_match.group(1)}commitment: {commitment}\n"
    if block[commitment_index] == new_line:
        return block, False
    rewritten = list(block)
    rewritten[commitment_index] = new_line
    return rewritten, True


def leading_spaces(line: str) -> int:
    return len(line) - len(line.lstrip(" "))


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate synthetic credentials for registry-notary perf testing."
    )
    parser.add_argument(
        "--env-file",
        default="target/perf/perf.env",
        help="Destination env file (default: target/perf/perf.env).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing env file.",
    )
    args = parser.parse_args()

    env_path = Path(args.env_file)
    if env_path.exists() and not args.force:
        print(
            f"Error: {env_path} already exists. Use --force to overwrite.",
            file=sys.stderr,
        )
        sys.exit(1)

    env_path.parent.mkdir(parents=True, exist_ok=True)

    env_lines = build_env_lines(
        bearer=generate_token(),
        api_key=generate_token(),
        no_scope=generate_token(),
        source_bearer=generate_token(),
        issuer_jwk=generate_issuer_jwk(),
    )
    env_content = "\n".join(env_lines) + "\n"

    env_path.write_text(env_content, encoding="utf-8")
    os.chmod(env_path, 0o600)
    updated_configs = refresh_config_commitments(env_values_from_lines(env_lines))

    print(f"Wrote: {env_path}")
    if updated_configs:
        print(f"Updated fingerprint commitments in {updated_configs} perf config files")
    print("Variables written:")
    for name in (
        "REGISTRY_NOTARY_BEARER_TOKEN",
        "REGISTRY_NOTARY_BEARER_TOKEN_HASH",
        "REGISTRY_NOTARY_API_KEY",
        "REGISTRY_NOTARY_API_KEY_HASH",
        "REGISTRY_NOTARY_NO_SCOPE_TOKEN",
        "REGISTRY_NOTARY_NO_SCOPE_TOKEN_HASH",
        "REGISTRY_NOTARY_TOKEN_INVALID",
        "REGISTRY_NOTARY_AUDIT_HASH_SECRET",
        "EVIDENCE_SOURCE_REGISTRY_RELAY_TOKEN",
        "REGISTRY_NOTARY_BASE_URL",
        "REGISTRY_NOTARY_PROFILE",
        "REGISTRY_NOTARY_BATCH_SIZE",
        "REGISTRY_NOTARY_SUBJECT_COUNT",
        "REGISTRY_NOTARY_CLAIM_EXTRACT",
        "REGISTRY_NOTARY_CLAIM_CEL",
        "EVIDENCE_SOURCE_STUB_BIND",
        "REGISTRY_NOTARY_ISSUER_JWK",
    ):
        print(f"  {name}")


if __name__ == "__main__":
    main()
