#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""
Synthetic API-key generator for Registry Relay performance testing.

Hashing scheme: Registry Relay expects env vars holding sha256:<64 lowercase hex chars>
where the hex is SHA-256(raw_token_bytes). This is stdlib hashlib.

Generates 6 tokens, writes an env file, and prints only the variable names and
the output path. Raw tokens and hashes are never printed to stdout.

Also emits:

- REGISTRY_RELAY_AUDIT_HASH_SECRET: per-deployment audit HMAC secret used to
  hash sensitive audit identifiers.

If the env file already exists and is being reused (--force not set), this
script exits without writing. When --force is set a new file is written with
fresh values for all variables (tokens and audit secret).

Usage:
    uv run perf/scripts/generate_perf_keys.py --env-file target/perf/perf.env
    uv run perf/scripts/generate_perf_keys.py --env-file target/perf/perf.env --force
"""

import argparse
import hashlib
import os
import secrets
import sys
from pathlib import Path


# Key definitions: (id, fingerprint_env_var, scopes list or None)
# Scopes are informational for the comment; the env file carries the hash only.
KEY_DEFS = [
    ("perf_rows",               "PERF_ROWS_KEY_HASH",               ["clinic_capacity:rows"]),
    ("perf_metadata",           "PERF_METADATA_KEY_HASH",           ["clinic_capacity:metadata"]),
    ("perf_aggregate",          "PERF_AGGREGATE_KEY_HASH",          ["clinic_capacity:aggregate"]),
    ("perf_no_scope",           "PERF_NO_SCOPE_KEY_HASH",           []),
    ("perf_evidence_verification", "PERF_EVIDENCE_VERIFICATION_KEY_HASH", ["clinic_capacity:evidence_verification"]),
    ("perf_admin",              "PERF_ADMIN_KEY_HASH",              ["registry_relay:admin"]),
]

INVALID_TOKEN_VALUE = "not-a-real-token-xxxx"

def sha256_fingerprint(raw: str) -> str:
    """Return sha256:<64 lowercase hex chars> of the UTF-8-encoded raw token."""
    digest = hashlib.sha256(raw.encode("utf-8")).hexdigest()
    return f"sha256:{digest}"


def generate_token() -> str:
    """Return a URL-safe random token (~32 bytes of entropy, 43 chars)."""
    return secrets.token_urlsafe(32)


def generate_audit_hash_secret() -> str:
    """Return a per-deployment audit HMAC secret for perf smoke runs."""
    return secrets.token_urlsafe(48)


def write_secret_file(path: Path, contents: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    try:
        if hasattr(os, "fchmod"):
            os.fchmod(fd, 0o600)
        else:
            os.chmod(path, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            fd = -1
            handle.write(contents)
    finally:
        if fd != -1:
            os.close(fd)


def build_env_lines(
    tokens: dict[str, str],
    audit_hash_secret: str,
) -> list[str]:
    """Build the env file lines from the token map. Never includes raw tokens."""
    lines = [
        "# Registry Relay perf test environment",
        "# Generated by generate_perf_keys.py. Do NOT commit this file.",
        "#",
        "# Token variables (raw bearer tokens for k6 / curl)",
        f"REGISTRY_RELAY_TOKEN={tokens['perf_rows']}",
        f"REGISTRY_RELAY_TOKEN_METADATA={tokens['perf_metadata']}",
        f"REGISTRY_RELAY_TOKEN_AGGREGATE={tokens['perf_aggregate']}",
        f"REGISTRY_RELAY_TOKEN_NO_SCOPE={tokens['perf_no_scope']}",
        f"REGISTRY_RELAY_TOKEN_EVIDENCE_VERIFICATION={tokens['perf_evidence_verification']}",
        f"REGISTRY_RELAY_TOKEN_ADMIN={tokens['perf_admin']}",
        f"REGISTRY_RELAY_TOKEN_INVALID={INVALID_TOKEN_VALUE}",
        "#",
        "# Routing defaults",
        "REGISTRY_RELAY_BASE_URL=http://127.0.0.1:18080",
        "REGISTRY_RELAY_DATASET_ID=clinic_capacity",
        "REGISTRY_RELAY_ENTITY=facility",
        "#",
        "# SHA-256 fingerprints consumed by Registry Relay at startup",
        "# (sha256:<64 lowercase hex chars> of the raw token above)",
    ]
    for key_id, hash_env, _ in KEY_DEFS:
        fingerprint = sha256_fingerprint(tokens[key_id])
        lines.append(f"{hash_env}={fingerprint}")
    lines += [
        "#",
        "# Audit HMAC secret for sensitive audit identifiers.",
        "# Must remain stable across server restarts for consistent audit lookups.",
        f"REGISTRY_RELAY_AUDIT_HASH_SECRET={audit_hash_secret}",
    ]
    return lines


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate synthetic API keys for Registry Relay perf testing."
    )
    parser.add_argument(
        "--env-file",
        default="target/perf/perf.env",
        help="Destination env file (default: target/perf/perf.env).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing env file.",
    )
    args = parser.parse_args()

    env_path = Path(args.env_file)

    if env_path.exists() and not args.force:
        print(
            f"Error: {env_path} already exists. Use --force to overwrite.",
            file=sys.stderr,
        )
        sys.exit(1)

    # Generate one random token per keyed entry and the audit secret.
    tokens: dict[str, str] = {key_id: generate_token() for key_id, _, _ in KEY_DEFS}
    audit_hash_secret = generate_audit_hash_secret()

    env_lines = build_env_lines(tokens, audit_hash_secret)
    env_content = "\n".join(env_lines) + "\n"

    write_secret_file(env_path, env_content)

    # Report only the path and variable names, never values.
    print(f"Wrote: {env_path}")
    print("Variables written:")
    var_names = [
        "REGISTRY_RELAY_TOKEN",
        "REGISTRY_RELAY_TOKEN_METADATA",
        "REGISTRY_RELAY_TOKEN_AGGREGATE",
        "REGISTRY_RELAY_TOKEN_NO_SCOPE",
        "REGISTRY_RELAY_TOKEN_EVIDENCE_VERIFICATION",
        "REGISTRY_RELAY_TOKEN_ADMIN",
        "REGISTRY_RELAY_TOKEN_INVALID",
        "REGISTRY_RELAY_BASE_URL",
        "REGISTRY_RELAY_DATASET_ID",
        "REGISTRY_RELAY_ENTITY",
    ] + [hash_env for _, hash_env, _ in KEY_DEFS] + [
        "REGISTRY_RELAY_AUDIT_HASH_SECRET",
    ]
    for name in var_names:
        print(f"  {name}")


if __name__ == "__main__":
    main()
