#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["cryptography>=42"]
# ///
"""
Synthetic API-key generator for Registry Relay performance testing.

Hashing scheme: Registry Relay expects env vars holding sha256:<64 lowercase hex chars>
where the hex is SHA-256(raw_token_bytes). This is stdlib hashlib.

The `cryptography` dep is used solely to derive the Ed25519 public half from
the freshly generated private seed when assembling the provenance JWK.

Generates 6 tokens, writes an env file, and prints only the variable names and
the output path. Raw tokens and hashes are never printed to stdout.

Also emits:

- REGISTRY_RELAY_AUDIT_HASH_SECRET: per-deployment audit HMAC secret used to
  hash sensitive audit identifiers.
- REGISTRY_RELAY_PROVENANCE_JWK: JSON-encoded Ed25519 private JWK used by
  the provenance signer to issue signed VC-JWT responses.

If the env file already exists and is being reused (--force not set), this
script exits without writing. When --force is set a new file is written with
fresh values for all variables (tokens, audit secret, signing JWK).

Usage:
    uv run perf/scripts/generate_perf_keys.py --env-file target/perf/perf.env
    uv run perf/scripts/generate_perf_keys.py --env-file target/perf/perf.env --force
"""

import argparse
import base64
import hashlib
import json
import os
import secrets
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey


# Key definitions: (id, fingerprint_env_var, scopes list or None)
# Scopes are informational for the comment; the env file carries the hash only.
KEY_DEFS = [
    ("perf_rows",               "PERF_ROWS_KEY_HASH",               ["clinic_capacity:rows"]),
    ("perf_metadata",           "PERF_METADATA_KEY_HASH",           ["clinic_capacity:metadata"]),
    ("perf_aggregate",          "PERF_AGGREGATE_KEY_HASH",          ["clinic_capacity:aggregate"]),
    ("perf_no_scope",           "PERF_NO_SCOPE_KEY_HASH",           []),
    ("perf_evidence_verification", "PERF_EVIDENCE_VERIFICATION_KEY_HASH", ["clinic_capacity:evidence_verification"]),
    ("perf_admin",              "PERF_ADMIN_KEY_HASH",              ["registry_relay:admin"]),
]

INVALID_TOKEN_VALUE = "not-a-real-token-xxxx"

def sha256_fingerprint(raw: str) -> str:
    """Return sha256:<64 lowercase hex chars> of the UTF-8-encoded raw token."""
    digest = hashlib.sha256(raw.encode("utf-8")).hexdigest()
    return f"sha256:{digest}"



def generate_token() -> str:
    """Return a URL-safe random token (~32 bytes of entropy, 43 chars)."""
    return secrets.token_urlsafe(32)


def generate_audit_hash_secret() -> str:
    """Return a per-deployment audit HMAC secret for perf smoke runs."""
    return secrets.token_urlsafe(48)


def _b64url(raw: bytes) -> str:
    """Unpadded base64url encoding per RFC 7515."""
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


# kid for the perf provenance signer. Must match the fragment in
# provenance.issuer.verification_method_id in perf/config/*.yaml.
PROVENANCE_KID = "perf-evidence-verification-v1"


def generate_provenance_jwk() -> str:
    """Return a JSON-encoded Ed25519 private JWK with kid + alg fields.

    The value is consumed by the software signer via
    `provenance.issuer.signer.jwk_env`. Format matches docs/provenance.md.
    """
    private = Ed25519PrivateKey.generate()
    seed = private.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption(),
    )
    public = private.public_key().public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    jwk = {
        "kty": "OKP",
        "crv": "Ed25519",
        "alg": "EdDSA",
        "kid": PROVENANCE_KID,
        "d": _b64url(seed),
        "x": _b64url(public),
    }
    # Compact, no whitespace. The env var is a single JSON string.
    return json.dumps(jwk, separators=(",", ":"))


def build_env_lines(
    tokens: dict[str, str],
    audit_hash_secret: str,
    provenance_jwk: str,
) -> list[str]:
    """Build the env file lines from the token map. Never includes raw tokens."""
    lines = [
        "# Registry Relay perf test environment",
        "# Generated by generate_perf_keys.py. Do NOT commit this file.",
        "#",
        "# Token variables (raw bearer tokens for k6 / curl)",
        f"REGISTRY_RELAY_TOKEN={tokens['perf_rows']}",
        f"REGISTRY_RELAY_TOKEN_METADATA={tokens['perf_metadata']}",
        f"REGISTRY_RELAY_TOKEN_AGGREGATE={tokens['perf_aggregate']}",
        f"REGISTRY_RELAY_TOKEN_NO_SCOPE={tokens['perf_no_scope']}",
        f"REGISTRY_RELAY_TOKEN_EVIDENCE_VERIFICATION={tokens['perf_evidence_verification']}",
        f"REGISTRY_RELAY_TOKEN_ADMIN={tokens['perf_admin']}",
        f"REGISTRY_RELAY_TOKEN_INVALID={INVALID_TOKEN_VALUE}",
        "#",
        "# Routing defaults",
        "REGISTRY_RELAY_BASE_URL=http://127.0.0.1:18080",
        "REGISTRY_RELAY_DATASET_ID=clinic_capacity",
        "REGISTRY_RELAY_ENTITY=facility",
        "#",
        "# SHA-256 fingerprints consumed by Registry Relay at startup",
        "# (sha256:<64 lowercase hex chars> of the raw token above)",
    ]
    for key_id, hash_env, _ in KEY_DEFS:
        fingerprint = sha256_fingerprint(tokens[key_id])
        lines.append(f"{hash_env}={fingerprint}")
    lines += [
        "#",
        "# Audit HMAC secret for sensitive audit identifiers.",
        "# Must remain stable across server restarts for consistent audit lookups.",
        f"REGISTRY_RELAY_AUDIT_HASH_SECRET={audit_hash_secret}",
        "#",
        "# Provenance signing key: JSON-encoded Ed25519 private JWK.",
        "# Read by the software signer at startup. NEVER commit this file.",
        f"REGISTRY_RELAY_PROVENANCE_JWK={provenance_jwk}",
    ]
    return lines



def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate synthetic API keys for Registry Relay perf testing."
    )
    parser.add_argument(
        "--env-file",
        default="target/perf/perf.env",
        help="Destination env file (default: target/perf/perf.env).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing env file.",
    )
    args = parser.parse_args()

    env_path = Path(args.env_file)

    if env_path.exists() and not args.force:
        print(
            f"Error: {env_path} already exists. Use --force to overwrite.",
            file=sys.stderr,
        )
        sys.exit(1)

    env_path.parent.mkdir(parents=True, exist_ok=True)

    # Generate one random token per keyed entry, the audit secret, and the
    # Ed25519 private JWK for the provenance signer.
    tokens: dict[str, str] = {key_id: generate_token() for key_id, _, _ in KEY_DEFS}
    audit_hash_secret = generate_audit_hash_secret()
    provenance_jwk = generate_provenance_jwk()

    env_lines = build_env_lines(tokens, audit_hash_secret, provenance_jwk)
    env_content = "\n".join(env_lines) + "\n"

    env_path.write_text(env_content, encoding="utf-8")
    # Restrict to owner read/write only.
    os.chmod(env_path, 0o600)

    # Report only the path and variable names, never values.
    print(f"Wrote: {env_path}")
    print("Variables written:")
    var_names = [
        "REGISTRY_RELAY_TOKEN",
        "REGISTRY_RELAY_TOKEN_METADATA",
        "REGISTRY_RELAY_TOKEN_AGGREGATE",
        "REGISTRY_RELAY_TOKEN_NO_SCOPE",
        "REGISTRY_RELAY_TOKEN_EVIDENCE_VERIFICATION",
        "REGISTRY_RELAY_TOKEN_ADMIN",
        "REGISTRY_RELAY_TOKEN_INVALID",
        "REGISTRY_RELAY_BASE_URL",
        "REGISTRY_RELAY_DATASET_ID",
        "REGISTRY_RELAY_ENTITY",
    ] + [hash_env for _, hash_env, _ in KEY_DEFS] + [
        "REGISTRY_RELAY_AUDIT_HASH_SECRET",
        "REGISTRY_RELAY_PROVENANCE_JWK",
    ]
    for name in var_names:
        print(f"  {name}")


if __name__ == "__main__":
    main()
