services:
  mongodb:
    image: mongo:8.2.11@sha256:951c2ff9fc6bdb6cb89b1dfea4a0e8ae3ee4fb287c0bf579b2bba54c7803f75d
  nginx:
    build:
      context: ./nginx
      dockerfile: ${REGISTRY_OPENID_CONFORMANCE_CONFIG_DIR:?runner must set config directory}/nginx.Dockerfile
  server:
    build:
      context: ./server-dev
      dockerfile: ${REGISTRY_OPENID_CONFORMANCE_CONFIG_DIR:?runner must set config directory}/server-dev.Dockerfile
