/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class RelayClient {
  constructor(configValue: any)
  health(): Promise<CompleteOutcome>
  ready(): Promise<CompleteOutcome>
  openapi(etag?: string | undefined | null): Promise<RawCompleteOutcome | NotModifiedOutcome>
  serviceMetadata(etag?: string | undefined | null): Promise<CompleteOutcome | NotModifiedOutcome>
  resources(options?: any | undefined | null, etag?: string | undefined | null): Promise<ResourcePageOutcome | NotModifiedOutcome>
  continueResources(continuation: any, etag?: string | undefined | null): Promise<ResourcePageOutcome | NotModifiedOutcome>
  resource(resource: string, etag?: string | undefined | null): Promise<CompleteOutcome | NotModifiedOutcome>
  listRecords(resource: string, options?: any | undefined | null, etag?: string | undefined | null): Promise<CollectionPageOutcome | NotModifiedOutcome>
  continueListRecords(continuation: any, etag?: string | undefined | null): Promise<CollectionPageOutcome | NotModifiedOutcome>
  readRecord(resource: string, recordIdentifier: string, options?: any | undefined | null, etag?: string | undefined | null): Promise<CompleteOutcome | NotModifiedOutcome>
  lookup(resource: string, lookup: string, selectors: any, options?: any | undefined | null, etag?: string | undefined | null): Promise<CompleteOutcome | NotModifiedOutcome>
  search(resource: string, search: string, options: any, etag?: string | undefined | null): Promise<CollectionPageOutcome | NotModifiedOutcome>
  continueSearch(continuation: any, etag?: string | undefined | null): Promise<CollectionPageOutcome | NotModifiedOutcome>
  artifact(artifactIdentifier: string, etag?: string | undefined | null): Promise<RawCompleteOutcome | NotModifiedOutcome>
  sdmxData(requestValue: any, etag?: string | undefined | null): Promise<RawCompleteOutcome | NotModifiedOutcome>
  sdmxStructure(requestValue: any, etag?: string | undefined | null): Promise<RawCompleteOutcome | NotModifiedOutcome>
}

export interface CollectionPageOutcome {
  kind: string
  value: any
  continuation?: any
  traceId: string
  etag?: string
}

export interface CompleteOutcome {
  kind: string
  value: any
  traceId: string
  etag?: string
}

export interface NotModifiedOutcome {
  kind: string
  etag: string
  traceId: string
}

export interface RawCompleteOutcome {
  kind: string
  body: Buffer
  mediaType: string
  traceId: string
  etag?: string
}

export interface ResourcePageOutcome {
  kind: string
  value: any
  continuation?: any
  traceId: string
  etag?: string
}
