#!/usr/bin/env bash
set -euo pipefail

repo="registrystack/registry-stack"
binaries=(evidence evidencectl evidence-oid4vci)
installer_name="evidencectl"
product_name="Evidence toolset"
version_env_name="EVIDENCECTL_VERSION"
bootstrap_tmp_prefix="evidencectl-bootstrap"
# Publication packaging replaces this empty value with the asset's canonical tag.
default_version=""
script_name="${BASH_SOURCE[0]:-}"
script_name="${script_name##*/}"
filename_version=""
if [[ "$script_name" =~ ^evidencectl-(v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)((-dev\.([1-9][0-9]*)\.([1-9][0-9]*))|(-nightly\.[0-9]{8}\.[0-9a-f]{40}))?)-install\.sh$ ]]; then
	filename_version="${BASH_REMATCH[1]}"
fi
if [ -n "$default_version" ] &&
	[ -n "$filename_version" ] &&
	[ "$default_version" != "$filename_version" ]; then
	echo "Refusing an installer whose embedded release does not match its filename." >&2
	exit 1
fi
default_version="${default_version:-$filename_version}"
version_override="${EVIDENCECTL_VERSION:-}"
version="${version_override:-$default_version}"
if [ -n "$default_version" ] &&
	[ -n "${EVIDENCECTL_VERSION:-}" ] &&
	[ "$EVIDENCECTL_VERSION" != "$default_version" ]; then
	echo "Refusing a release override that does not match the released installer asset." >&2
	exit 1
fi
install_dir="${EVIDENCECTL_INSTALL_DIR:-$HOME/.local/bin}"
asset_dir="${EVIDENCECTL_ASSET_DIR:-}"

usage() {
	cat <<EOF
Install the Evidence toolset: the evidence runtime, the evidencectl adopter
tooling, and the evidence-oid4vci wallet delivery service.

Quick install:
  curl -fsSL https://github.com/${repo}/releases/latest/download/evidencectl-install.sh | bash

Release selection (for the unpinned source installer):
  --channel nightly  Install the latest successfully published nightly build.
  --build <tag>      Install one immutable vX.Y.Z-nightly.YYYYMMDD.SHA build.

A published installer is already pinned and refuses both selection options.

The installer verifies every downloaded release asset against the release's
SHA256SUMS before anything reaches the install directory, and installs the
three binaries together or not at all: every command is a stable link resolved
through one toolset pointer, so the whole toolset changes version in a single
step. It does not verify release
authenticity. For a higher-assurance installation, follow the release
verification guide for the pinned tag, then rerun with EVIDENCECTL_ASSET_DIR
set to the verified directory:
  https://github.com/${repo}/blob/<version>/release/VERIFY.md

Environment:
  EVIDENCECTL_VERSION      Toolset tag to install. A published installer
                           embeds its tag and refuses a different override.
  EVIDENCECTL_INSTALL_DIR  Install directory. Defaults to ~/.local/bin.
  EVIDENCECTL_ASSET_DIR    Read already-downloaded release assets from this
                           directory instead of downloading them.
EOF
}

need() {
	if ! command -v "$1" >/dev/null 2>&1; then
		echo "evidencectl installer needs '$1'." >&2
		exit 1
	fi
}

# BEGIN generated release channel resolver
# Generated by release/scripts/render-installer-channel.py. Do not edit by hand.
channel=""
build=""
while [ "$#" -gt 0 ]; do
	case "$1" in
	--channel)
		[ "$#" -ge 2 ] || { echo "--channel needs a value." >&2; exit 2; }
		[ -z "$channel" ] || { echo "--channel may be supplied only once." >&2; exit 2; }
		channel="$2"
		shift 2
		;;
	--build)
		[ "$#" -ge 2 ] || { echo "--build needs an immutable nightly tag." >&2; exit 2; }
		[ -z "$build" ] || { echo "--build may be supplied only once." >&2; exit 2; }
		build="$2"
		shift 2
		;;
	--help | -h)
		usage
		exit 0
		;;
	*)
		printf 'Unknown option: %s\n' "$1" >&2
		usage >&2
		exit 2
		;;
	esac
done
if [ -n "$channel" ] && [ "$channel" != "nightly" ]; then
	printf 'Unknown release channel: %s. Supported channel: nightly.\n' "$channel" >&2
	exit 2
fi
if [ -n "$channel" ] && [ -n "$build" ]; then
	echo "--channel and --build are mutually exclusive." >&2
	exit 2
fi
if [ -n "$default_version" ] && { [ -n "$channel" ] || [ -n "$build" ]; }; then
	echo "This published installer is already pinned to $default_version; --channel and --build are not accepted." >&2
	exit 2
fi
if [ -n "$version_override" ] && { [ -n "$channel" ] || [ -n "$build" ]; }; then
	echo "$version_env_name cannot be combined with --channel or --build." >&2
	exit 2
fi

sha256_file() {
	local path="$1"
	local result
	if command -v shasum >/dev/null 2>&1; then
		result="$(shasum -a 256 "$path")"
	elif command -v sha256sum >/dev/null 2>&1; then
		result="$(sha256sum "$path")"
	else
		echo "$product_name installer needs 'shasum' or 'sha256sum' for checksum verification." >&2
		exit 1
	fi
	printf '%s\n' "${result%% *}"
}

manifest_value() {
	local key="$1"
	awk -v key="$key" '
		$0 ~ "^[[:space:]]*\\\"" key "\\\"[[:space:]]*:" {
			line = $0
			sub("^[[:space:]]*\\\"" key "\\\"[[:space:]]*:[[:space:]]*\\\"", "", line)
			sub("\\\"[[:space:]]*$", "", line)
			value = line
			count++
		}
		END { if (count != 1) exit 1; print value }
	' "$2"
}

manifest_asset_hash() {
	local wanted="$1"
	awk -v wanted="$wanted" '
		{
			name = $0
			if (name !~ /"name"[[:space:]]*:[[:space:]]*"/) next
			sub(/^.*"name"[[:space:]]*:[[:space:]]*"/, "", name)
			sub(/".*$/, "", name)
			if (name != wanted) next
			hash = $0
			if (hash !~ /"sha256"[[:space:]]*:[[:space:]]*"/) next
			sub(/^.*"sha256"[[:space:]]*:[[:space:]]*"/, "", hash)
			sub(/".*$/, "", hash)
			value = hash
			count++
		}
		END { if (count != 1) exit 1; print value }
	' "$2"
}

embedded_installer_version() {
	awk '
		/^default_version="v[0-9][0-9A-Za-z.-]*"$/ {
			line = $0
			sub(/^default_version="/, "", line)
			sub(/"$/, "", line)
			value = line
			count++
		}
		END { if (count != 1) exit 1; print value }
	' "$1"
}

run_unpinned_installer() {
	need curl
	local bootstrap_tmp manifest_url manifest normalized objects tag schema manifest_version
	local base_version source_sha created_at expected_base expected_installer installer_hash actual_hash
	bootstrap_tmp="$(mktemp -d 2>/dev/null || mktemp -d -t "$bootstrap_tmp_prefix")"
	trap 'rm -rf "$bootstrap_tmp"' EXIT
	trap 'exit 130' INT
	trap 'exit 143' TERM

	if [ -z "$channel" ] && [ -z "$build" ]; then
		printf 'Resolving the latest numbered %s release...\n' "$product_name"
		if ! curl -fsSL "https://github.com/${repo}/releases/latest/download/${installer_name}-install.sh" \
			-o "$bootstrap_tmp/installer" 2>/dev/null; then
			echo "Could not download the latest numbered $product_name installer." >&2
			exit 1
		fi
		tag="$(embedded_installer_version "$bootstrap_tmp/installer" || true)"
		if [[ ! "$tag" =~ ^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]]; then
			echo "The latest numbered installer did not embed a canonical release tag." >&2
			exit 1
		fi
		printf 'Resolved latest numbered release to %s.\n' "$tag"
		bash "$bootstrap_tmp/installer"
		exit $?
	fi

	if [ -n "$build" ]; then
		if [[ ! "$build" =~ ^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)-nightly\.[0-9]{8}\.[0-9a-f]{40}$ ]]; then
			echo "--build requires vMAJOR.MINOR.PATCH-nightly.YYYYMMDD.FULL40CHARSHA." >&2
			exit 2
		fi
		manifest_url="https://github.com/${repo}/releases/download/${build}/nightly.json"
	else
		manifest_url="https://raw.githubusercontent.com/${repo}/nightly-channel/nightly.json"
	fi
	manifest="$bootstrap_tmp/nightly.json"
	if ! curl -fsSL "$manifest_url" -o "$manifest" 2>/dev/null; then
		echo "Could not download nightly metadata from $manifest_url" >&2
		exit 1
	fi
	# The producer validates the JSON before it advances the channel. Splitting
	# structural punctuation makes its scalar fields available to standard awk
	# without adding jq or Python as an installation prerequisite.
	normalized="$bootstrap_tmp/nightly.fields"
	tr '{}[],' '\n' <"$manifest" >"$normalized"
	objects="$bootstrap_tmp/nightly.objects"
	tr '\n}' ' \n' <"$manifest" >"$objects"
	schema="$(manifest_value schema_version "$normalized" || true)"
	tag="$(manifest_value tag "$normalized" || true)"
	manifest_version="$(manifest_value version "$normalized" || true)"
	base_version="$(manifest_value base_version "$normalized" || true)"
	source_sha="$(manifest_value source_sha "$normalized" || true)"
	created_at="$(manifest_value created_at "$normalized" || true)"
	if [ "$schema" != "registry-stack.nightly.v1" ] && [ "$schema" != "registry-stack.nightly.v2" ]; then
		echo "Refusing nightly metadata with a missing or unsupported schema_version." >&2
		exit 1
	fi
	if [[ ! "$tag" =~ ^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)-nightly\.[0-9]{8}\.([0-9a-f]{40})$ ]]; then
		echo "Refusing nightly metadata with a non-canonical immutable tag." >&2
		exit 1
	fi
	if [ -n "$build" ] && [ "$tag" != "$build" ]; then
		printf 'Refusing nightly metadata for %s while installing %s.\n' "$tag" "$build" >&2
		exit 1
	fi
	expected_base="${tag#v}"
	expected_base="${expected_base%%-nightly.*}"
	if [ "$manifest_version" != "${tag#v}" ] || [ "$base_version" != "$expected_base" ] || \
		[ "$source_sha" != "${BASH_REMATCH[4]}" ] || [ -z "$created_at" ]; then
		echo "Refusing internally inconsistent nightly metadata." >&2
		exit 1
	fi
	expected_installer="${installer_name}-${tag}-install.sh"
	installer_hash="$(manifest_asset_hash "$expected_installer" "$objects" || true)"
	if [[ ! "$installer_hash" =~ ^[0-9a-f]{64}$ ]]; then
		printf 'Nightly metadata has no valid checksum for %s.\n' "$expected_installer" >&2
		exit 1
	fi
	if ! curl -fsSL "https://github.com/${repo}/releases/download/${tag}/${expected_installer}" \
		-o "$bootstrap_tmp/installer" 2>/dev/null; then
		printf 'Could not download immutable nightly installer %s.\n' "$expected_installer" >&2
		exit 1
	fi
	actual_hash="$(sha256_file "$bootstrap_tmp/installer")"
	if [ "$actual_hash" != "$installer_hash" ]; then
		printf 'Checksum verification failed for %s.\n' "$expected_installer" >&2
		exit 1
	fi
	if [ "$(embedded_installer_version "$bootstrap_tmp/installer" || true)" != "$tag" ]; then
		echo "The verified nightly installer does not embed the manifest tag." >&2
		exit 1
	fi
	printf 'Resolved nightly build %s from source %s.\n' "$tag" "$source_sha"
	printf 'Verified %s against nightly.json.\n' "$expected_installer"
	bash "$bootstrap_tmp/installer"
	exit $?
}

if [ -z "$version" ]; then
	run_unpinned_installer
fi

verification_guide="release/VERIFY.md"
case "$version" in
*-nightly.*) verification_guide="release/NIGHTLY.md" ;;
esac
# END generated release channel resolver
if [[ ! "$version" =~ ^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)((-dev\.([1-9][0-9]*)\.([1-9][0-9]*))|(-nightly\.[0-9]{8}\.[0-9a-f]{40}))?$ ]]; then
	echo "Refusing non-canonical Evidence toolset tag '$version'." >&2
	echo "Use vMAJOR.MINOR.PATCH, a workflow-produced dev tag, or vMAJOR.MINOR.PATCH-nightly.YYYYMMDD.FULL40CHARSHA." >&2
	exit 1
fi
development_build=0
if [[ "$version" =~ -dev\.[1-9][0-9]*\.[1-9][0-9]*$ ]]; then
	development_build=1
fi

need uname
if [ -z "$asset_dir" ]; then
	need curl
fi

os="$(uname -s)"
arch="$(uname -m)"

case "$os/$arch" in
Linux/x86_64 | Linux/amd64)
	os_label="linux"
	arch_label="amd64"
	;;
Linux/arm64 | Linux/aarch64)
	os_label="linux"
	arch_label="arm64"
	;;
Darwin/arm64 | Darwin/aarch64)
	os_label="macos"
	arch_label="arm64"
	;;
*)
	printf 'No prebuilt Evidence toolset asset is published for %s/%s.\n' "$os" "$arch" >&2
	printf 'Supported platforms: Linux amd64, Linux arm64, and macOS arm64.\n' >&2
	printf 'Check the published assets at https://github.com/%s/releases/tag/%s\n' "$repo" "$version" >&2
	exit 1
	;;
esac

# FIPS on macOS uses shared libraries. From v0.33 each executable and its
# libraries travel together in one checksum-covered archive.
macos_bundle=0
if [ "$os_label" = "macos" ]; then
	IFS=. read -r release_major release_minor release_patch <<<"${version#v}"
	if ((release_major > 0 || release_minor >= 33)); then
		macos_bundle=1
		need tar
	fi
fi

asset_name() {
	local stem="${1}-${version}-${os_label}-${arch_label}"
	if [ "$macos_bundle" -eq 1 ]; then
		printf '%s.tar.gz\n' "$stem"
	else
		printf '%s\n' "$stem"
	fi
}

# BEGIN generated libc preflight
# Generated from release/glibc-floor.env by
# release/scripts/render-installer-libc-preflight.py. Do not edit by hand.
#
# The published Linux binaries are dynamically linked against GNU libc. On a
# musl system, or on a glibc older than the floor below, they cannot start, and
# the dynamic linker only says so at the first run, long after this installer
# would have reported success. Refuse here instead, before anything downloads.
if [ "$os_label" = "linux" ]; then
	libc_floor="2.35"
	# musl's ldd exits non-zero when asked for a version, and this installer runs
	# under pipefail, so its report is captured once here instead of being read
	# through a pipeline whose status would hide the match.
	libc_report=""
	if command -v ldd >/dev/null 2>&1; then
		libc_report="$(ldd --version 2>&1 || true)"
	fi
	# Only glibc's getconf answers GNU_LIBC_VERSION, so an answer names the libc
	# this system runs on, whatever else is installed beside it: a musl loader
	# kept for cross builds does not make a musl system. Without an answer, musl
	# is recognised by its ldd report or its loader. The report is matched by a
	# pattern rather than through grep, which can exit before the report is
	# fully written and, under pipefail, lose the match.
	detected_libc=""
	if command -v getconf >/dev/null 2>&1; then
		detected_libc="$(getconf GNU_LIBC_VERSION 2>/dev/null | awk '{print $2}' || true)"
	fi
	musl_system=0
	if [ -z "$detected_libc" ]; then
		case "$libc_report" in
		*[Mm][Uu][Ss][Ll]*) musl_system=1 ;;
		esac
		if ls /lib/ld-musl-*.so.1 >/dev/null 2>&1; then
			musl_system=1
		fi
	fi
	if [ "$musl_system" = 1 ]; then
		printf 'No musl build of the Evidence toolset is published for this platform.\n' >&2
		printf 'Every published Linux binary needs GNU libc %s or newer, so none of them can start here.\n' \
			"$libc_floor" >&2
		printf 'Install on a GNU libc distribution, or run the published container images.\n' >&2
		printf 'If you need musl builds, ask for them at https://github.com/%s/issues so the demand is recorded.\n' \
			"$repo" >&2
		exit 1
	fi
	if [ -z "$detected_libc" ]; then
		detected_libc="$(printf '%s\n' "$libc_report" | awk 'NR == 1 {print $NF}')"
	fi
	case "$detected_libc" in
	[0-9]*.[0-9]*) ;;
	*) detected_libc="" ;;
	esac
	if [ -z "$detected_libc" ]; then
		printf 'Could not read the GNU libc version of this system, so the %s floor is unchecked.\n' \
			"$libc_floor" >&2
	elif ! awk -v have="$detected_libc" -v floor="$libc_floor" '
		BEGIN {
			split(have, h, ".")
			split(floor, f, ".")
			exit !(h[1] > f[1] || (h[1] == f[1] && h[2] >= f[2]))
		}
	'; then
		printf 'This system has GNU libc %s. The published binaries of the Evidence toolset need %s or newer.\n' \
			"$detected_libc" "$libc_floor" >&2
		printf 'Nothing was installed: the binaries would fail to start with a dynamic linker error.\n' >&2
		printf 'Upgrade the distribution, or run the published container images.\n' >&2
		exit 1
	fi
fi

# END generated libc preflight
base_url="https://github.com/${repo}/releases/download/${version}"
verify_url="https://github.com/${repo}/blob/${version}/${verification_guide}"
tmpdir="$(mktemp -d 2>/dev/null || mktemp -d -t evidencectl)"

cleanup() {
	rm -rf "$tmpdir"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

download() {
	local src="$1"
	local dest="$2"
	if [ -n "$asset_dir" ]; then
		local name="${src##*/}"
		if [ ! -f "$asset_dir/$name" ]; then
			return 1
		fi
		cp "$asset_dir/$name" "$dest"
	else
		curl -fsSL "$src" -o "$dest" 2>/dev/null
	fi
}

if [ -n "$asset_dir" ]; then
	printf 'Installing verified local Evidence toolset %s assets for %s/%s...\n' \
		"$version" "$os_label" "$arch_label"
else
	printf 'Downloading the Evidence toolset %s for %s/%s...\n' \
		"$version" "$os_label" "$arch_label"
fi

for binary in "${binaries[@]}"; do
	asset="$(asset_name "$binary")"
	if ! download "$base_url/$asset" "$tmpdir/$asset"; then
		printf 'Could not read the published %s %s binary for %s/%s.\n' \
			"$binary" "$version" "$os_label" "$arch_label" >&2
		printf 'Check the published assets at https://github.com/%s/releases/tag/%s\n' \
			"$repo" "$version" >&2
		exit 1
	fi
done

if ! download "$base_url/SHA256SUMS" "$tmpdir/SHA256SUMS"; then
	echo "Could not download SHA256SUMS for checksum verification." >&2
	exit 1
fi

verify_asset() {
	local name="$1"
	local expected_hash actual_hash
	expected_hash="$(awk -v asset="$name" '$2 == asset {print $1}' "$tmpdir/SHA256SUMS")"
	if [ -z "$expected_hash" ]; then
		echo "SHA256SUMS has no entry for $name" >&2
		exit 1
	fi
	actual_hash="$(sha256_file "$tmpdir/$name")"
	if [ "$actual_hash" != "$expected_hash" ]; then
		echo "Checksum verification failed for $name" >&2
		echo "Expected: $expected_hash" >&2
		echo "Actual:   $actual_hash" >&2
		exit 1
	fi
}

for binary in "${binaries[@]}"; do
	verify_asset "$(asset_name "$binary")"
done
printf 'Integrity checks passed: %s binaries matched SHA256SUMS.\n' "${#binaries[@]}"
if [ "$development_build" -eq 1 ]; then
	cat <<EOF
Development build: this unsupported prerelease was built from the exact source
tag below, but its checksum file is not signed and this installer performs no
authenticity check. Do not treat it as a Registry Stack release.
  https://github.com/${repo}/tree/${version}

EOF
else
	cat <<EOF
Authenticity check not performed by this installer.
For a higher-assurance installation, follow the tag-frozen release
verification guide first, then rerun this installer with
EVIDENCECTL_ASSET_DIR set to that verified directory:
  $verify_url

EOF
fi

# Check the complete flat archive roster before extracting any file. Each
# binary keeps its own libraries, including when independently built toolset
# members contain different module bytes with the same library basename.
validate_macos_bundle() {
	local binary="$1"
	local stem="${binary}-${version}-${os_label}-${arch_label}"
	local archive="$tmpdir/$(asset_name "$binary")"
	if ! tar -tzf "$archive" >"$tmpdir/$binary.members" ||
		! awk -v executable="$stem" '
			{
				if (seen[$0]++) { bad = 1; exit }
				if ($0 == executable) { binaries++; next }
				if ($0 == "THIRD_PARTY_NOTICES") { notices++; next }
				if ($0 ~ /^libaws_lc_fips_[A-Za-z0-9_]+\.dylib$/) {
					libraries++; next
				}
				bad = 1; exit
			}
			END { exit (bad || binaries != 1 || notices != 1 || libraries < 1) }
		' "$tmpdir/$binary.members"; then
		echo "Refusing an invalid macOS bundle roster: ${archive##*/}" >&2
		exit 1
	fi
	if ! tar -tvzf "$archive" >"$tmpdir/$binary.types" ||
		! awk '
			$NF == "THIRD_PARTY_NOTICES" {
				if ($1 != "-rw-r--r--") bad = 1
				next
			}
			$1 != "-rwxr-xr-x" { bad = 1 }
			END { exit bad }
		' "$tmpdir/$binary.types"; then
		echo "Refusing non-regular files or unexpected modes in ${archive##*/}" >&2
		exit 1
	fi
}

if [ "$macos_bundle" -eq 1 ]; then
	for binary in "${binaries[@]}"; do
		validate_macos_bundle "$binary"
	done
fi

mkdir -p "$install_dir"
stage_dir="$(mktemp -d "$install_dir/.evidence-toolset.XXXXXX")"
link_stage_dir="$(mktemp -d "$install_dir/.evidence-links.XXXXXX")"
chmod 0755 "$stage_dir"
install_complete=0
cleanup_install() {
	set +e
	if [ "$install_complete" -eq 0 ]; then
		rm -rf "$stage_dir"
	fi
	rm -rf "$link_stage_dir"
}
trap 'cleanup_install; cleanup' EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

for binary in "${binaries[@]}"; do
	if [ "$macos_bundle" -eq 1 ]; then
		stem="${binary}-${version}-${os_label}-${arch_label}"
		bundle_dir="$stage_dir/$binary.bundle"
		mkdir "$bundle_dir"
		tar -xzf "$tmpdir/$(asset_name "$binary")" -C "$bundle_dir"
		chmod 0755 "$bundle_dir" "$bundle_dir/$stem" "$bundle_dir"/*.dylib
		ln -s "$binary.bundle/$stem" "$stage_dir/$binary"
		observed_version="$(env -u DYLD_LIBRARY_PATH -u DYLD_FALLBACK_LIBRARY_PATH \
			-u DYLD_INSERT_LIBRARIES "$stage_dir/$binary" --version)"
		if [ "$observed_version" != "$binary ${version#v}" ]; then
			echo "The staged macOS $binary has an unexpected version." >&2
			exit 1
		fi
	else
		cp "$tmpdir/$(asset_name "$binary")" "$stage_dir/$binary"
		chmod 0755 "$stage_dir/$binary"
	fi
done

replace_path() {
	local source="$1"
	local destination="$2"
	if [ "$os_label" = "macos" ]; then
		mv -fh "$source" "$destination"
	else
		mv -Tf "$source" "$destination"
	fi
}

current_link="$install_dir/.evidence-current"
if [ -e "$current_link" ] && [ ! -L "$current_link" ]; then
	echo "Refusing to replace a non-symbolic Evidence toolset pointer." >&2
	exit 1
fi

# A one-time migration keeps existing direct binaries behind the same pointer
# before their stable command links are installed. At every point every command
# therefore resolves to the prior toolset, the new toolset, or neither. Stock
# macOS bash is 3.2 and has no associative array, so the migration walks the
# binaries instead of bookkeeping their previous state.
if [ ! -L "$current_link" ]; then
	previous_dir="$(mktemp -d "$install_dir/.evidence-previous.XXXXXX")"
	chmod 0755 "$previous_dir"
	previous_count=0
	for binary in "${binaries[@]}"; do
		if [ -e "$install_dir/$binary" ] && [ ! -d "$install_dir/$binary" ]; then
			cp -p "$install_dir/$binary" "$previous_dir/$binary"
			previous_count=$((previous_count + 1))
		fi
	done
	if [ "$previous_count" -gt 0 ]; then
		ln -s "${previous_dir##*/}" "$link_stage_dir/current"
		replace_path "$link_stage_dir/current" "$current_link"
	else
		rm -rf "$previous_dir"
	fi
fi

for binary in "${binaries[@]}"; do
	if [ -d "$install_dir/$binary" ] && [ ! -L "$install_dir/$binary" ]; then
		echo "Refusing to replace a directory at $install_dir/$binary." >&2
		exit 1
	fi
	ln -s ".evidence-current/$binary" "$link_stage_dir/$binary"
	if [ -e "$current_link/$binary" ]; then
		replace_path "$link_stage_dir/$binary" "$install_dir/$binary"
	fi
done

# Every stable command link the pointer already resolves changes version through
# this one atomic rename. A failed switch leaves the pointer, and with it the
# previously working toolset, exactly where it was.
ln -s "${stage_dir##*/}" "$link_stage_dir/current"
install_complete=1
replace_path "$link_stage_dir/current" "$current_link"

# A command the pointer does not resolve yet, such as one another product's
# installer wrote directly, is linked only now that the switch has made its
# target real. Installing that link earlier would replace a working command with
# a link to a file that a failed switch never creates. Its staged link is still
# in place because the loop above left it there.
for binary in "${binaries[@]}"; do
	if [ -L "$link_stage_dir/$binary" ]; then
		replace_path "$link_stage_dir/$binary" "$install_dir/$binary"
	fi
done

printf 'Evidence toolset %s installed to %s.\n' "$version" "$install_dir"
printf 'Every command (%s) is a link through the toolset pointer %s.\n' \
	"${binaries[*]}" "$current_link"
cat <<EOF

Try it:
  evidencectl keygen --help
  evidencectl new --help
  evidencectl fixtures --help

EOF

case ":$PATH:" in
*":$install_dir:"*) ;;
*)
	echo "Add $install_dir to PATH to run the Evidence toolset from any shell." >&2
	;;
esac
