/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class BaseRegistryClient {
  constructor(config: any)
  health(): Promise<CompleteOutcome>
  ready(): Promise<CompleteOutcome>
  openapi(accessProfile?: string | undefined | null): Promise<RawOutcome>
  registryMetadata(accessProfile?: string | undefined | null): Promise<RawOutcome>
  registryContract(accessProfile?: string | undefined | null): Promise<BRegMetadata>
  entitySchema(entityIdentifier: string, accessProfile?: string | undefined | null): Promise<RawOutcome>
  getRecord(entityRoute: string, recordIdentifier: string, options?: any | undefined | null): Promise<CompleteOutcome>
  listRecords(entityRoute: string, options?: any | undefined | null): Promise<PageOutcome>
  continueList(value: any): Promise<PageOutcome>
  lookupRecord(entityRoute: string, selector: string, values?: any | undefined | null, options?: any | undefined | null): Promise<CompleteOutcome>
  createRecord(binding: BRegCreateBinding, data: any, idempotencyKey: string, formatValue?: string | undefined | null): Promise<CompleteOutcome>
  patchRecord(binding: BRegPatchBinding, recordIdentifier: string, etag: string, operations: any, idempotencyKey: string, formatValue?: string | undefined | null): Promise<CompleteOutcome>
  lifecycleActions(authority: BRegLifecycleAuthority, record: any, formatValue?: string | undefined | null): Array<BRegLifecycleAction>
  executeLifecycleAction(action: BRegLifecycleAction, idempotencyKey: string): Promise<CompleteOutcome>
  getRecordJson(entityRoute: string, recordIdentifier: string, options?: any | undefined | null): Promise<JsonOutcome>
  listRecordsJson(entityRoute: string, options?: any | undefined | null): Promise<JsonOutcome>
  continueListJson(value: any): Promise<JsonOutcome>
  lookupRecordJson(entityRoute: string, selector: string, valuesJson?: string | undefined | null, options?: any | undefined | null): Promise<JsonOutcome>
  createRecordJson(binding: BRegCreateBinding, dataJson: string, idempotencyKey: string, formatValue?: string | undefined | null): Promise<JsonOutcome>
  patchRecordJson(binding: BRegPatchBinding, recordIdentifier: string, etag: string, operationsJson: string, idempotencyKey: string, formatValue?: string | undefined | null): Promise<JsonOutcome>
  lifecycleActionsJson(authority: BRegLifecycleAuthority, recordJson: string, formatValue?: string | undefined | null): Array<BRegLifecycleAction>
  executeLifecycleActionJson(action: BRegLifecycleAction, idempotencyKey: string): Promise<JsonOutcome>
}

export declare class BRegCreateBinding {

}
export type CreateBinding = BRegCreateBinding

export declare class BRegLifecycleAction {
  withReason(reason: string): BRegLifecycleAction
  get bodyJson(): string
  get reviewJson(): string | null
  get operation(): string
  get stage(): string | null
  get href(): string
  get body(): any
  get review(): any | null
}
export type LifecycleAction = BRegLifecycleAction

export declare class BRegLifecycleAuthority {

}
export type LifecycleAuthority = BRegLifecycleAuthority

export declare class BRegMetadata {
  /** Caller-filtered inert descriptors. Selectors below remain the only authority constructors. */
  get operations(): any
  get registryIdentifier(): string
  get registryVersion(): string
  get registryRevision(): string
  get traceId(): string
  get etag(): string | null
  selectCreate(operationIdentifier: string, expectedProfile: string): BRegCreateBinding
  selectPatch(operationIdentifier: string, expectedProfile: string): BRegPatchBinding
  selectLifecycle(entityIdentifier: string, expectedProfile: string): BRegLifecycleAuthority
}
export type Metadata = BRegMetadata

export declare class BRegPatchBinding {

}
export type PatchBinding = BRegPatchBinding

export interface CompleteOutcome {
  kind: string
  value: any
  traceId: string
  etag?: string
  location?: string
}

/** Validated product result serialized before the JavaScript number boundary. */
export interface JsonOutcome {
  kind: string
  valueJson: string
  continuation?: any
  traceId: string
  etag?: string
  location?: string
}

export interface PageOutcome {
  kind: string
  value: any
  continuation?: any
  traceId: string
  etag?: string
}

export interface RawOutcome {
  kind: string
  body: Buffer
  mediaType: string
  traceId: string
  etag?: string
}
