#!/usr/bin/env python3
"""Render the self-contained release-channel resolver into product installers."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


INSTALLERS = (
    "crates/registry-breg/install.sh",
    "crates/registry-evidencectl/install.sh",
    "crates/registry-casework/install.sh",
    "crates/registry-scheduling/install.sh",
)
BEGIN = "# BEGIN generated release channel resolver"
END = "# END generated release channel resolver"

# Published installers are single files, so this block is copied into each of
# them. Keep product-specific names and environment values in variables above
# the block. This is intentionally shell-only: modern macOS does not include
# Python, and requiring jq would make the bootstrap harder to use than the
# binaries it installs.
BLOCK = r'''# BEGIN generated release channel resolver
# Generated by release/scripts/render-installer-channel.py. Do not edit by hand.
channel=""
build=""
while [ "$#" -gt 0 ]; do
	case "$1" in
	--channel)
		[ "$#" -ge 2 ] || { echo "--channel needs a value." >&2; exit 2; }
		[ -z "$channel" ] || { echo "--channel may be supplied only once." >&2; exit 2; }
		channel="$2"
		shift 2
		;;
	--build)
		[ "$#" -ge 2 ] || { echo "--build needs an immutable nightly tag." >&2; exit 2; }
		[ -z "$build" ] || { echo "--build may be supplied only once." >&2; exit 2; }
		build="$2"
		shift 2
		;;
	--help | -h)
		usage
		exit 0
		;;
	*)
		printf 'Unknown option: %s\n' "$1" >&2
		usage >&2
		exit 2
		;;
	esac
done
if [ -n "$channel" ] && [ "$channel" != "nightly" ]; then
	printf 'Unknown release channel: %s. Supported channel: nightly.\n' "$channel" >&2
	exit 2
fi
if [ -n "$channel" ] && [ -n "$build" ]; then
	echo "--channel and --build are mutually exclusive." >&2
	exit 2
fi
if [ -n "$default_version" ] && { [ -n "$channel" ] || [ -n "$build" ]; }; then
	echo "This published installer is already pinned to $default_version; --channel and --build are not accepted." >&2
	exit 2
fi
if [ -n "$version_override" ] && { [ -n "$channel" ] || [ -n "$build" ]; }; then
	echo "$version_env_name cannot be combined with --channel or --build." >&2
	exit 2
fi

sha256_file() {
	local path="$1"
	local result
	if command -v shasum >/dev/null 2>&1; then
		result="$(shasum -a 256 "$path")"
	elif command -v sha256sum >/dev/null 2>&1; then
		result="$(sha256sum "$path")"
	else
		echo "$product_name installer needs 'shasum' or 'sha256sum' for checksum verification." >&2
		exit 1
	fi
	printf '%s\n' "${result%% *}"
}

manifest_value() {
	local key="$1"
	awk -v key="$key" '
		$0 ~ "^[[:space:]]*\\\"" key "\\\"[[:space:]]*:" {
			line = $0
			sub("^[[:space:]]*\\\"" key "\\\"[[:space:]]*:[[:space:]]*\\\"", "", line)
			sub("\\\"[[:space:]]*$", "", line)
			value = line
			count++
		}
		END { if (count != 1) exit 1; print value }
	' "$2"
}

manifest_asset_hash() {
	local wanted="$1"
	awk -v wanted="$wanted" '
		{
			name = $0
			if (name !~ /"name"[[:space:]]*:[[:space:]]*"/) next
			sub(/^.*"name"[[:space:]]*:[[:space:]]*"/, "", name)
			sub(/".*$/, "", name)
			if (name != wanted) next
			hash = $0
			if (hash !~ /"sha256"[[:space:]]*:[[:space:]]*"/) next
			sub(/^.*"sha256"[[:space:]]*:[[:space:]]*"/, "", hash)
			sub(/".*$/, "", hash)
			value = hash
			count++
		}
		END { if (count != 1) exit 1; print value }
	' "$2"
}

embedded_installer_version() {
	awk '
		/^default_version="v[0-9][0-9A-Za-z.-]*"$/ {
			line = $0
			sub(/^default_version="/, "", line)
			sub(/"$/, "", line)
			value = line
			count++
		}
		END { if (count != 1) exit 1; print value }
	' "$1"
}

run_unpinned_installer() {
	need curl
	local bootstrap_tmp manifest_url manifest normalized objects tag schema manifest_version
	local base_version source_sha created_at expected_base expected_installer installer_hash actual_hash
	bootstrap_tmp="$(mktemp -d 2>/dev/null || mktemp -d -t "$bootstrap_tmp_prefix")"
	trap 'rm -rf "$bootstrap_tmp"' EXIT
	trap 'exit 130' INT
	trap 'exit 143' TERM

	if [ -z "$channel" ] && [ -z "$build" ]; then
		printf 'Resolving the latest numbered %s release...\n' "$product_name"
		if ! curl -fsSL "https://github.com/${repo}/releases/latest/download/${installer_name}-install.sh" \
			-o "$bootstrap_tmp/installer" 2>/dev/null; then
			echo "Could not download the latest numbered $product_name installer." >&2
			exit 1
		fi
		tag="$(embedded_installer_version "$bootstrap_tmp/installer" || true)"
		if [[ ! "$tag" =~ ^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]]; then
			echo "The latest numbered installer did not embed a canonical release tag." >&2
			exit 1
		fi
		printf 'Resolved latest numbered release to %s.\n' "$tag"
		bash "$bootstrap_tmp/installer"
		exit $?
	fi

	if [ -n "$build" ]; then
		if [[ ! "$build" =~ ^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)-nightly\.[0-9]{8}\.[0-9a-f]{40}$ ]]; then
			echo "--build requires vMAJOR.MINOR.PATCH-nightly.YYYYMMDD.FULL40CHARSHA." >&2
			exit 2
		fi
		manifest_url="https://github.com/${repo}/releases/download/${build}/nightly.json"
	else
		manifest_url="https://raw.githubusercontent.com/${repo}/nightly-channel/nightly.json"
	fi
	manifest="$bootstrap_tmp/nightly.json"
	if ! curl -fsSL "$manifest_url" -o "$manifest" 2>/dev/null; then
		echo "Could not download nightly metadata from $manifest_url" >&2
		exit 1
	fi
	# The producer validates the JSON before it advances the channel. Splitting
	# structural punctuation makes its scalar fields available to standard awk
	# without adding jq or Python as an installation prerequisite.
	normalized="$bootstrap_tmp/nightly.fields"
	tr '{}[],' '\n' <"$manifest" >"$normalized"
	objects="$bootstrap_tmp/nightly.objects"
	tr '\n}' ' \n' <"$manifest" >"$objects"
	schema="$(manifest_value schema_version "$normalized" || true)"
	tag="$(manifest_value tag "$normalized" || true)"
	manifest_version="$(manifest_value version "$normalized" || true)"
	base_version="$(manifest_value base_version "$normalized" || true)"
	source_sha="$(manifest_value source_sha "$normalized" || true)"
	created_at="$(manifest_value created_at "$normalized" || true)"
	if [ "$schema" != "registry-stack.nightly.v1" ] && [ "$schema" != "registry-stack.nightly.v2" ]; then
		echo "Refusing nightly metadata with a missing or unsupported schema_version." >&2
		exit 1
	fi
	if [[ ! "$tag" =~ ^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)-nightly\.[0-9]{8}\.([0-9a-f]{40})$ ]]; then
		echo "Refusing nightly metadata with a non-canonical immutable tag." >&2
		exit 1
	fi
	if [ -n "$build" ] && [ "$tag" != "$build" ]; then
		printf 'Refusing nightly metadata for %s while installing %s.\n' "$tag" "$build" >&2
		exit 1
	fi
	expected_base="${tag#v}"
	expected_base="${expected_base%%-nightly.*}"
	if [ "$manifest_version" != "${tag#v}" ] || [ "$base_version" != "$expected_base" ] || \
		[ "$source_sha" != "${BASH_REMATCH[4]}" ] || [ -z "$created_at" ]; then
		echo "Refusing internally inconsistent nightly metadata." >&2
		exit 1
	fi
	expected_installer="${installer_name}-${tag}-install.sh"
	installer_hash="$(manifest_asset_hash "$expected_installer" "$objects" || true)"
	if [[ ! "$installer_hash" =~ ^[0-9a-f]{64}$ ]]; then
		printf 'Nightly metadata has no valid checksum for %s.\n' "$expected_installer" >&2
		exit 1
	fi
	if ! curl -fsSL "https://github.com/${repo}/releases/download/${tag}/${expected_installer}" \
		-o "$bootstrap_tmp/installer" 2>/dev/null; then
		printf 'Could not download immutable nightly installer %s.\n' "$expected_installer" >&2
		exit 1
	fi
	actual_hash="$(sha256_file "$bootstrap_tmp/installer")"
	if [ "$actual_hash" != "$installer_hash" ]; then
		printf 'Checksum verification failed for %s.\n' "$expected_installer" >&2
		exit 1
	fi
	if [ "$(embedded_installer_version "$bootstrap_tmp/installer" || true)" != "$tag" ]; then
		echo "The verified nightly installer does not embed the manifest tag." >&2
		exit 1
	fi
	printf 'Resolved nightly build %s from source %s.\n' "$tag" "$source_sha"
	printf 'Verified %s against nightly.json.\n' "$expected_installer"
	bash "$bootstrap_tmp/installer"
	exit $?
}

if [ -z "$version" ]; then
	run_unpinned_installer
fi

verification_guide="release/VERIFY.md"
case "$version" in
*-nightly.*) verification_guide="release/NIGHTLY.md" ;;
esac
# END generated release channel resolver'''


def render(source: str) -> str:
    if BEGIN in source or END in source:
        if source.count(BEGIN) != 1 or source.count(END) != 1:
            raise ValueError("installer has an incomplete generated channel block")
        start = source.index(BEGIN)
        end = source.index(END, start) + len(END)
        return source[:start] + BLOCK + source[end:]

    # One-time migration from the duplicated implementation. The following
    # no-version diagnostic is deliberately outside the generated region.
    start = source.index('channel=""', source.index("need()"))
    search = start
    anchor = '\nif [ -z "$version" ]; then\n'
    while True:
        end = source.index(anchor, search)
        if source.startswith('\techo "No ', end + len(anchor)):
            break
        search = end + 1
    return source[:start] + BLOCK + "\n" + source[end + 1 :]


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    arguments = parser.parse_args()

    stale: list[str] = []
    for relative in INSTALLERS:
        path = arguments.root / relative
        source = path.read_text()
        rendered = render(source)
        if rendered == source:
            continue
        if arguments.write:
            path.write_text(rendered)
        else:
            stale.append(relative)
    if stale:
        print("stale generated release channel resolver: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
