//! `registry-render init`: scaffold a bundle that compiles offline in minutes —
//! zero edits, zero warnings, including for non-Latin label locales.

use std::path::Path;

use crate::problem::{ProblemKind, RenderProblem};

const MANIFEST: &str = r#"apiVersion: render.registrystack.org/v1alpha1
kind: RenderBundle
bundleVersion: 1
documents:
  - id: letter
    version: 1
    entry: templates/letter.typ
    schema: schemas/letter.schema.json
    labels: [en]
"#;

/// The template is generated per scaffold so `payload.labels.<locale>`
/// always points at a declared table.
const TEMPLATE_HEAD: &str = r#"// Starter document. It compiles offline: the binary embeds baseline
// Latin fonts, and the data contract below is checked before rendering.
//
// Everything the renderer gives you is in one value (see PAYLOAD.md in the
// product docs):
#let payload = json(bytes(sys.inputs.data))
#let d = payload.data
#let L = payload.labels.{LOCALE}
#set text(font: ("Libertinus Serif", "DejaVu Sans Mono"), size: 11pt, lang: "{LOCALE}")
#set page(paper: "a4", margin: 2.2cm, footer: context [
  #set text(size: 8pt)
  #line(length: 100%, stroke: 0.4pt + gray)
  #grid(
    columns: (1fr, auto),
    [#d.footer-note — #L.generated],
    [#L.reference: #d.reference],
  )
])

// Typst packages are vendored, never fetched at render time: put one
// under packages/<namespace>/<name>/<version>/ and import it by its
// package spec, for example
// #import "@preview/some-package:1.0.0": thing
// The Render example bundles ship a worked one (a QR carrying a
// verification URL).

#text(size: 16pt, weight: "bold")[#L.title]
#v(0.4em)
#d.body

#v(1fr)
#box(stroke: 0.6pt + black, inset: 8pt)[
  *#L.issued-at:* #payload.issuedAt \
  #L.version-note #payload.document.version
]
"#;

const SCHEMA: &str = r#"{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "required": ["reference", "body", "footer-note"],
  "properties": {
    "reference": { "type": "string", "minLength": 1 },
    "body": { "type": "string" },
    "footer-note": { "type": "string" }
  }
}
"#;

/// Every scaffolded label file gets the full key set the template reads,
/// in English as the seed values: the bundle compiles warning-free
/// offline, and the author localizes (adding a script font when the
/// locale needs one).
const LABEL_KEYS: &[(&str, &str)] = &[
    ("title", "Registry letter"),
    ("reference", "Reference"),
    ("generated", "generated by Registry Render"),
    ("issued-at", "Issued"),
    ("version-note", "document version"),
];

const FIXTURE_DATA: &str =
    "{\n  \"reference\": \"LTR-2026-000001\",\n  \"body\": \"Hello from the scaffold. Replace me.\",\n  \"footer-note\": \"demo document\"\n}\n";

const README: &str = r#"# Render bundle

- `manifest.yaml` — document types, versions, labels, and (after
  `registry-render seal`) per-file hashes.
- `templates/` — Typst entry points. Author them with any upstream Typst
  tooling; `registry-render compile` (and `--watch`) run unsealed bundles with a
  notice.
- `schemas/` — the JSON Schema each request's `data` must satisfy.
- `labels/` — one flat YAML string map per locale; seeded in English,
  localize at will. A script beyond Latin needs a font in `fonts/` (for
  example Noto Naskh Arabic); `registry-render check` names the gap.
- `fonts/` — starter fonts (Noto Sans + Noto Naskh Arabic, OFL — the
  license is in `fonts/OFL.txt`); replace them with your own. The binary
  already embeds a Latin baseline.
- `packages/` — create it when you need a Typst package. Packages are
  vendored, never fetched at render time: one lives under
  `packages/<namespace>/<name>/<version>/` and is imported by its package
  spec. The Render example bundles ship a worked one.
- `fixtures/data.json` — a valid first payload.

Workflow: edit → `registry-render compile --bundle . --type letter
--data fixtures/data.json --issued-at … --out letter.pdf` (or `--watch`) →
`registry-render seal` when ready → `registry-render serve` requires the sealed bundle.

Before writing a template that prints registry data, agree the field list
(the disclosure gate): what appears on paper leaves every access profile
behind.
"#;

/// Starter fonts (with their license), embedded the same way: a Latin text
/// face plus an Arabic one, so `fonts/` holds real, replaceable examples
/// and a non-Latin scaffold already has its script covered. Byte-identical
/// to the copies the example bundles ship.
const STARTER_FONT_FILES: &[(&str, &[u8])] = &[
    (
        "NotoSans-Regular.ttf",
        include_bytes!("../assets/starter-fonts/NotoSans-Regular.ttf"),
    ),
    (
        "NotoNaskhArabic-Regular.ttf",
        include_bytes!("../assets/starter-fonts/NotoNaskhArabic-Regular.ttf"),
    ),
    ("OFL.txt", include_bytes!("../assets/starter-fonts/OFL.txt")),
];

pub fn scaffold(dir: &Path, labels: &[String]) -> Result<i32, RenderProblem> {
    let mut seen = std::collections::BTreeSet::new();
    for locale in labels {
        if locale.is_empty() || !locale.chars().all(|c| c.is_ascii_lowercase() || c == '-') {
            return Err(RenderProblem::new(
                ProblemKind::InvalidArgument,
                format!("label locale must be kebab-case, got {locale:?}"),
            ));
        }
        // A repeat would scaffold one label file twice and list the locale
        // twice in the manifest; refuse it before anything is written.
        if !seen.insert(locale) {
            return Err(RenderProblem::new(
                ProblemKind::InvalidArgument,
                format!("label locale {locale:?} is listed more than once"),
            ));
        }
    }
    let labels = if labels.is_empty() {
        vec!["en".to_owned()]
    } else {
        labels.to_vec()
    };
    let first_locale = labels[0].clone();
    std::fs::create_dir_all(dir.join("templates")).map_err(io_problem)?;
    std::fs::create_dir_all(dir.join("schemas")).map_err(io_problem)?;
    std::fs::create_dir_all(dir.join("labels")).map_err(io_problem)?;
    std::fs::create_dir_all(dir.join("fonts")).map_err(io_problem)?;
    std::fs::create_dir_all(dir.join("fixtures")).map_err(io_problem)?;
    for (file, bytes) in STARTER_FONT_FILES {
        write_new_bytes(&dir.join("fonts").join(file), bytes)?;
    }

    let labels_field = format!(
        "labels: [{}]",
        labels
            .iter()
            .map(|l| format!("\"{l}\""))
            .collect::<Vec<_>>()
            .join(", ")
    );
    let manifest = match MANIFEST.find("labels: [en]") {
        Some(at) => {
            let mut m = MANIFEST.to_owned();
            m.replace_range(at..at + "labels: [en]".len(), &labels_field);
            m
        }
        None => {
            return Err(RenderProblem::new(
                ProblemKind::Internal,
                "scaffold template is malformed",
            ))
        }
    };
    let template = TEMPLATE_HEAD.replace("{LOCALE}", &first_locale);
    write_new(&dir.join("manifest.yaml"), &manifest)?;
    write_new(&dir.join("templates/letter.typ"), &template)?;
    write_new(&dir.join("schemas/letter.schema.json"), SCHEMA)?;
    for locale in &labels {
        let seeded: String = LABEL_KEYS
            .iter()
            .map(|(key, value)| format!("{key}: \"{value}\"\n"))
            .collect();
        if locale != "en" {
            eprintln!(
                "note: labels/{locale}.yaml is seeded in English; localize it, and if {locale:?} needs a script beyond Latin add a font to fonts/ (registry-render check names the gap)"
            );
        }
        write_new(&dir.join(format!("labels/{locale}.yaml")), &seeded)?;
    }
    write_new(&dir.join("fixtures/data.json"), FIXTURE_DATA)?;
    write_new(&dir.join("README.md"), README)?;
    println!(
        "scaffolded {} — first render:\n  registry-render compile --bundle {} --type letter --data fixtures/data.json --issued-at 2026-01-01T00:00:00Z --out letter.pdf",
        dir.display(),
        dir.display()
    );
    Ok(0)
}

fn write_new(path: &Path, contents: &str) -> Result<(), RenderProblem> {
    write_new_bytes(path, contents.as_bytes())
}

fn write_new_bytes(path: &Path, contents: &[u8]) -> Result<(), RenderProblem> {
    if path.exists() {
        return Err(RenderProblem::new(
            ProblemKind::InvalidArgument,
            format!(
                "{} already exists; init refuses to overwrite",
                path.display()
            ),
        ));
    }
    std::fs::write(path, contents).map_err(io_problem)
}

fn io_problem(err: std::io::Error) -> RenderProblem {
    RenderProblem::new(ProblemKind::InvalidArgument, format!("init: {err}"))
}
