/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DiscoveryClient {
  constructor(options: string | DiscoveryClientOptions)
  resolveEvidenceTypes(request: any): Promise<any>
  searchServices(filters: any): Promise<any>
  selectExact(response: any, request: any): any
}

export interface DiscoveryClientOptions {
  baseUrl: string
  requestTimeoutMilliseconds?: number
  connectTimeoutMilliseconds?: number
  maximumResponseBytes?: number
  trustedRootCertificates?: Buffer
}

export declare function selectExact(response: any, request: any): any
