[package]
name = "registry-platform-oidc"
version.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
publish = false

[lints]
workspace = true

[features]
schema = ["dep:schemars", "registry-platform-yaml/schema", "registry-platform-config/schema"]

[dependencies]
base64.workspace = true
jsonwebtoken.workspace = true
registry-platform-crypto = { workspace = true }
registry-platform-httputil = { workspace = true }
registry-platform-config.workspace = true
registry-platform-yaml.workspace = true
schemars = { workspace = true, optional = true }
uuid = { workspace = true, features = ["serde"] }
chrono.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
axum.workspace = true
tempfile.workspace = true
