// SPDX-License-Identifier: Apache-2.0
//! One-way lossy Registry Manifest projection.

use std::collections::{BTreeMap, BTreeSet};

use registry_manifest_core::{
    compile_manifest, render_base_dcat, AccessRights, AdmsStatus, ApplicationProfile,
    AuthorityManifest, CatalogManifest, CodelistConcept, CodelistManifest, DataServiceManifest,
    DatasetManifest, DistributionManifest, FieldConstraints, FieldManifest, FieldType,
    IdentifierManifest, LocalizedText, MetadataError, MetadataManifest, PublisherManifest,
    RelationshipManifest, Sensitivity, ServiceManifest, StandardsManifest,
};
use registry_platform_canonical_json::canonicalize_json;
use serde_json::Value;

use crate::artifacts::decimal_pattern;
use crate::contract::{
    Classification, FieldTypeSource, ManifestProjectionDatasetStatus,
    ManifestProjectionEntitySource, ManifestProjectionFieldSource, ManifestProjectionTextSource,
    ManifestProjectionVocabularySource, Operation,
};
use crate::diagnostics::Diagnostic;
use crate::model::{
    CompiledEntity, CompiledField, CompiledManifestDataset, CompiledManifestProjection,
};

pub(crate) struct ProjectedManifestArtifacts {
    pub manifest: Vec<u8>,
    pub dcat: Vec<u8>,
}

pub(crate) fn project_manifest_artifacts(
    registry_id: &str,
    projection: &CompiledManifestProjection,
    entities: &BTreeMap<String, CompiledEntity>,
) -> Result<ProjectedManifestArtifacts, Diagnostic> {
    let publication = ManifestPublicationContext {
        access_profile: &projection.access_profile,
        classification_ceiling: projection.classification_ceiling,
    };
    let visible_datasets = visible_dataset_ids(projection, publication);

    // Compile the complete typed source once so Registry Manifest remains the
    // owner of reference filtering and DCAT rendering. The complete source is
    // deliberately never canonicalized or rendered for this publication
    // context. Its filtered view is the only input to the DCAT renderer.
    let source = project_manifest(registry_id, projection, entities, None);
    let compiled = compile_manifest(&source).map_err(manifest_diagnostic)?;
    let compiled =
        compiled.filter(|dataset, _| visible_datasets.contains(dataset.dataset_id.as_str()));

    // The portable Manifest source is constructed from the same classified
    // publication slice. This keeps protected labels and identifiers out of
    // both generated byte streams, including relationship edges.
    let manifest = project_manifest(registry_id, projection, entities, Some(publication));
    let mut value =
        serde_json::to_value(&manifest).map_err(|_| manifest_canonicalization_diagnostic())?;
    strip_null_members(&mut value);
    let manifest: MetadataManifest = serde_json::from_value(value.clone())
        .map_err(|_| manifest_canonicalization_diagnostic())?;
    compile_manifest(&manifest).map_err(manifest_diagnostic)?;
    let manifest = canonicalize_json(&value).map_err(|_| manifest_canonicalization_diagnostic())?;
    let dcat = canonicalize_json(&render_base_dcat(&compiled))
        .map_err(|_| manifest_canonicalization_diagnostic())?;
    Ok(ProjectedManifestArtifacts { manifest, dcat })
}

#[derive(Clone, Copy)]
struct ManifestPublicationContext<'a> {
    access_profile: &'a str,
    classification_ceiling: Classification,
}

fn visible_dataset_ids<'a>(
    projection: &'a CompiledManifestProjection,
    publication: ManifestPublicationContext<'_>,
) -> BTreeSet<&'a str> {
    projection
        .datasets
        .values()
        .filter(|dataset| dataset_visible_in(dataset, publication))
        .map(|dataset| dataset.source.id.as_str())
        .collect()
}

fn dataset_visible_in(
    dataset: &CompiledManifestDataset,
    publication: ManifestPublicationContext<'_>,
) -> bool {
    dataset.effective_access_profile == publication.access_profile
        && dataset.effective_classification_ceiling <= publication.classification_ceiling
}

fn project_manifest(
    registry_id: &str,
    projection: &CompiledManifestProjection,
    entities: &BTreeMap<String, CompiledEntity>,
    publication: Option<ManifestPublicationContext<'_>>,
) -> MetadataManifest {
    let included_datasets = publication
        .map(|publication| visible_dataset_ids(projection, publication))
        .unwrap_or_else(|| {
            projection
                .datasets
                .values()
                .map(|dataset| dataset.source.id.as_str())
                .collect()
        });
    let visible_by_dataset = projection
        .datasets
        .iter()
        .filter(|(_, dataset)| included_datasets.contains(dataset.source.id.as_str()))
        .map(|(id, dataset)| (id.as_str(), visible_entities(dataset, entities)))
        .collect::<BTreeMap<_, _>>();
    let included_data_services = projection
        .data_services
        .values()
        .filter(|service| {
            service
                .serves_datasets
                .iter()
                .any(|dataset| included_datasets.contains(dataset.as_str()))
        })
        .map(|service| service.source.id.as_str())
        .collect::<BTreeSet<_>>();

    MetadataManifest {
        schema_version: "registry-manifest/v1".to_owned(),
        catalog: CatalogManifest {
            id: registry_id.to_owned(),
            base_url: projection.catalog.base_url.clone(),
            title: localized_text(&projection.catalog.title),
            description: projection.catalog.description.as_ref().map(localized_text),
            publisher: PublisherManifest {
                name: projection.catalog.publisher.name.clone(),
                iri: projection.catalog.publisher.iri.clone(),
                authority_type: projection.catalog.publisher.authority_type.clone(),
            },
            participant_id: projection.catalog.participant_id.clone(),
            conforms_to: projection.catalog.conforms_to.clone(),
            standards: StandardsManifest {
                dcat: projection.catalog.standards.dcat.clone(),
                shacl: projection.catalog.standards.shacl.clone(),
                json_schema: projection.catalog.standards.json_schema.clone(),
            },
            application_profiles: projection
                .catalog
                .application_profiles
                .iter()
                .map(|profile| ApplicationProfile {
                    id: profile.id.clone(),
                    version: profile.version.clone(),
                })
                .collect(),
        },
        vocabularies: BTreeMap::new(),
        profiles: Vec::new(),
        evaluation_profiles: Vec::new(),
        ecosystem_bindings: Vec::new(),
        requirements: Vec::new(),
        evidence_types: Vec::new(),
        authorities: vec![AuthorityManifest {
            id: projection.primary_authority.id.clone(),
            iri: Some(projection.primary_authority.iri.clone()),
            name: projection.primary_authority.name.clone(),
            authority_type: projection.primary_authority.authority_type.clone(),
            spatial: None,
        }],
        public_services: vec![ServiceManifest {
            id: projection.public_service.source.id.clone(),
            iri: Some(projection.public_service.iri.clone()),
            title: localized_text(&projection.public_service.source.title),
            // Registry Manifest v1 currently requires this field. Reusing the
            // governed title avoids inventing a second descriptive value.
            description: Some(localized_text(&projection.public_service.source.title)),
            competent_authority: Some(projection.public_service.competent_authority.clone()),
            jurisdiction: None,
            channels: Vec::new(),
            holds_requirements: Vec::new(),
            produces: projection
                .public_service
                .produces
                .iter()
                .filter(|dataset| included_datasets.contains(dataset.as_str()))
                .cloned()
                .collect(),
            data_services: projection
                .public_service
                .data_services
                .iter()
                .filter(|service| included_data_services.contains(service.as_str()))
                .cloned()
                .collect(),
            forms: Vec::new(),
        }],
        data_services: projection
            .data_services
            .values()
            .filter(|service| included_data_services.contains(service.source.id.as_str()))
            .map(|service| DataServiceManifest {
                id: service.source.id.clone(),
                iri: Some(service.iri.clone()),
                title: localized_text(&service.source.title),
                description: service.source.description.as_ref().map(localized_text),
                endpoint_url: Some(service.source.endpoint_url.clone()),
                endpoint_description: service.source.endpoint_description.clone(),
                serves_datasets: service
                    .serves_datasets
                    .iter()
                    .filter(|dataset| included_datasets.contains(dataset.as_str()))
                    .cloned()
                    .collect(),
                conforms_to: service.source.conforms_to.clone(),
            })
            .collect(),
        distributions: projection
            .distributions
            .values()
            .filter(|distribution| included_datasets.contains(distribution.dataset.as_str()))
            .filter(|distribution| {
                distribution
                    .source
                    .access_service
                    .as_deref()
                    .is_none_or(|service| included_data_services.contains(service))
            })
            .map(|distribution| DistributionManifest {
                id: distribution.source.id.clone(),
                dataset: distribution.dataset.clone(),
                access_service: distribution.access_service.clone(),
                access_url: distribution.source.access_url.clone(),
                download_url: distribution.source.download_url.clone(),
                media_type: distribution.source.media_type.clone(),
                format: distribution.source.format.clone(),
                title: distribution.source.title.as_ref().map(localized_text),
                description: distribution.source.description.as_ref().map(localized_text),
                iri: Some(distribution.iri.clone()),
            })
            .collect(),
        forms: Vec::new(),
        datasets: projection
            .datasets
            .values()
            .filter(|dataset| included_datasets.contains(dataset.source.id.as_str()))
            .map(|dataset| {
                let visible_entities = &visible_by_dataset[dataset.source.id.as_str()];
                DatasetManifest {
                    id: dataset.source.id.clone(),
                    iri: Some(dataset.iri.clone()),
                    version: dataset.source.version.clone(),
                    title: localized_text(&dataset.source.title),
                    description: dataset.source.description.as_ref().map(localized_text),
                    owner: dataset.source.owner.clone(),
                    sensitivity: sensitivity(dataset.effective_classification_ceiling),
                    access_rights: if selected_profile_is_anonymous(dataset, visible_entities) {
                        AccessRights::Public
                    } else {
                        AccessRights::Restricted
                    },
                    update_frequency: Default::default(),
                    conforms_to: dataset.source.conforms_to.clone(),
                    applicable_legislation: dataset.source.applicable_legislation.clone(),
                    spatial_coverage: dataset.source.spatial_coverage.clone(),
                    status: dataset.source.status.map(adms_status),
                    public_services: Vec::new(),
                    policy: None,
                    evidence_offerings: Vec::new(),
                    entities: visible_entities
                        .iter()
                        .map(|entity| project_entity(projection, dataset, entity, visible_entities))
                        .collect(),
                }
            })
            .collect(),
        codelists: project_codelists(projection, entities, &included_datasets),
    }
}

fn localized_text(source: &ManifestProjectionTextSource) -> LocalizedText {
    match source {
        ManifestProjectionTextSource::Plain(value) => LocalizedText::Plain(value.clone()),
        ManifestProjectionTextSource::Localized(values) => LocalizedText::Localized(values.clone()),
    }
}

fn visible_entities<'a>(
    dataset: &CompiledManifestDataset,
    entities: &'a BTreeMap<String, CompiledEntity>,
) -> Vec<&'a CompiledEntity> {
    entities
        .values()
        .filter(|entity| dataset.entities.contains(&entity.id))
        .filter(|entity| entity.classification <= dataset.effective_classification_ceiling)
        .filter(|entity| {
            entity
                .access_profiles
                .get(&dataset.effective_access_profile)
                .is_some_and(|profile| {
                    profile.operations.contains(&Operation::Get)
                        || profile.operations.contains(&Operation::List)
                })
        })
        .collect()
}

fn selected_profile_is_anonymous(
    dataset: &CompiledManifestDataset,
    visible_entities: &[&CompiledEntity],
) -> bool {
    visible_entities.iter().all(|entity| {
        entity
            .access_profiles
            .get(&dataset.effective_access_profile)
            .is_some_and(|profile| profile.anonymous)
    })
}

fn project_entity(
    projection: &CompiledManifestProjection,
    dataset: &CompiledManifestDataset,
    entity: &CompiledEntity,
    visible_entities: &[&CompiledEntity],
) -> registry_manifest_core::EntityManifest {
    let metadata = projection
        .entities
        .iter()
        .find(|metadata| metadata.id == entity.id);
    let visible_entity_ids = visible_entities
        .iter()
        .map(|entity| entity.id.as_str())
        .collect::<BTreeSet<_>>();
    let readable_fields = entity
        .access_profiles
        .get(&dataset.effective_access_profile)
        .map(|profile| profile.readable_fields.clone())
        .unwrap_or_default();

    let fields = entity
        .fields
        .values()
        .filter(|field| readable_fields.contains(&field.id))
        .filter(|field| field.classification <= dataset.effective_classification_ceiling)
        .filter_map(|field| {
            project_field(
                field,
                field_metadata(metadata, &field.id),
                &projection.vocabularies,
            )
        })
        .collect();
    let relationships = entity
        .fields
        .values()
        .filter(|field| readable_fields.contains(&field.id))
        .filter(|field| field.classification <= dataset.effective_classification_ceiling)
        .filter_map(|field| {
            project_relationship(
                field,
                field_metadata(metadata, &field.id),
                &visible_entity_ids,
            )
        })
        .collect();

    registry_manifest_core::EntityManifest {
        name: entity.id.clone(),
        title: metadata
            .and_then(|metadata| metadata.title.as_ref())
            .map(localized_text),
        description: metadata
            .and_then(|metadata| metadata.description.as_ref())
            .map(localized_text),
        concept_uri: metadata.and_then(|metadata| metadata.concept_uri.clone()),
        identifiers: metadata
            .map(|metadata| {
                metadata
                    .identifiers
                    .iter()
                    .map(|identifier| IdentifierManifest {
                        name: identifier.field.clone(),
                        kind: identifier.kind.clone(),
                    })
                    .collect()
            })
            .unwrap_or_default(),
        fields,
        relationships,
    }
}

fn field_metadata<'a>(
    entity: Option<&'a ManifestProjectionEntitySource>,
    field_id: &str,
) -> Option<&'a ManifestProjectionFieldSource> {
    entity.and_then(|entity| entity.fields.iter().find(|field| field.id == field_id))
}

fn project_field(
    field: &CompiledField,
    metadata: Option<&ManifestProjectionFieldSource>,
    vocabularies: &[ManifestProjectionVocabularySource],
) -> Option<FieldManifest> {
    let (field_type, constraints) = match &field.field_type {
        FieldTypeSource::Boolean => (FieldType::Boolean, FieldConstraints::default()),
        FieldTypeSource::String {
            min_length,
            max_length,
        } => (
            FieldType::String,
            FieldConstraints {
                min_length: Some(u64::from(*min_length)),
                max_length: Some(u64::from(*max_length)),
                ..FieldConstraints::default()
            },
        ),
        FieldTypeSource::Text { max_length } => (
            FieldType::String,
            FieldConstraints {
                max_length: Some(u64::from(*max_length)),
                ..FieldConstraints::default()
            },
        ),
        FieldTypeSource::Int64 => (FieldType::Integer, FieldConstraints::default()),
        FieldTypeSource::Decimal {
            precision, scale, ..
        } => (
            FieldType::String,
            FieldConstraints {
                pattern: Some(decimal_pattern(*precision, *scale)),
                ..FieldConstraints::default()
            },
        ),
        FieldTypeSource::Date => (FieldType::Date, FieldConstraints::default()),
        FieldTypeSource::Timestamp => (FieldType::Timestamp, FieldConstraints::default()),
        FieldTypeSource::Uuid => (FieldType::String, FieldConstraints::default()),
        FieldTypeSource::VocabularyCode { values, .. } => (
            FieldType::Code,
            FieldConstraints {
                values: values.clone(),
                ..FieldConstraints::default()
            },
        ),
        FieldTypeSource::Reference { .. }
        | FieldTypeSource::Crs84Point { .. }
        | FieldTypeSource::Structured { .. } => return None,
    };
    Some(FieldManifest {
        name: field.id.clone(),
        field_type,
        required: field.required,
        constraints,
        concepts: metadata
            .map(|metadata| metadata.concepts.clone())
            .unwrap_or_default(),
        codelist: match &field.field_type {
            FieldTypeSource::VocabularyCode { vocabulary, .. }
                if vocabularies
                    .iter()
                    .any(|metadata| metadata.id.as_str() == vocabulary) =>
            {
                Some(vocabulary.clone())
            }
            _ => None,
        },
        unit: metadata.and_then(|metadata| metadata.unit.clone()),
        language: metadata.and_then(|metadata| metadata.language.clone()),
    })
}

fn project_relationship(
    field: &CompiledField,
    metadata: Option<&ManifestProjectionFieldSource>,
    visible_entity_ids: &BTreeSet<&str>,
) -> Option<RelationshipManifest> {
    let FieldTypeSource::Reference { target, .. } = &field.field_type else {
        return None;
    };
    visible_entity_ids
        .contains(target.as_str())
        .then(|| RelationshipManifest {
            name: field.id.clone(),
            target_entity: Some(target.clone()),
            target: None,
            cardinality: Some(if field.required {
                "one".to_owned()
            } else {
                "zero_or_one".to_owned()
            }),
            role: metadata.and_then(|metadata| metadata.relationship_role.clone()),
            concept_uri: metadata.and_then(|metadata| metadata.relationship_concept_uri.clone()),
        })
}

fn project_codelists(
    projection: &CompiledManifestProjection,
    entities: &BTreeMap<String, CompiledEntity>,
    included_datasets: &BTreeSet<&str>,
) -> Vec<CodelistManifest> {
    let used = projection
        .datasets
        .values()
        .filter(|dataset| included_datasets.contains(dataset.source.id.as_str()))
        .flat_map(|dataset| {
            visible_entities(dataset, entities)
                .into_iter()
                .map(move |entity| (dataset, entity))
        })
        .flat_map(|(dataset, entity)| {
            let readable_fields = entity
                .access_profiles
                .get(&dataset.effective_access_profile)
                .map(|profile| &profile.readable_fields);
            entity.fields.values().filter(move |field| {
                readable_fields.is_some_and(|fields| fields.contains(&field.id))
                    && field.classification <= dataset.effective_classification_ceiling
            })
        })
        .filter_map(|field| match &field.field_type {
            FieldTypeSource::VocabularyCode { vocabulary, values } => {
                Some((vocabulary.as_str(), values.as_slice()))
            }
            _ => None,
        })
        .collect::<BTreeMap<_, _>>();
    projection
        .vocabularies
        .iter()
        .filter_map(|metadata| {
            let values = used.get(metadata.id.as_str())?;
            let concepts = values
                .iter()
                .map(|code| project_codelist_concept(metadata, code))
                .collect();
            Some(CodelistManifest {
                id: metadata.id.clone(),
                scheme_iri: metadata.scheme_iri.clone(),
                version: metadata.version.clone(),
                valid_from: None,
                valid_to: None,
                external_ref: metadata.external_ref.clone(),
                concepts,
            })
        })
        .collect()
}

fn project_codelist_concept(
    metadata: &ManifestProjectionVocabularySource,
    code: &str,
) -> CodelistConcept {
    let authored = metadata
        .concepts
        .iter()
        .find(|concept| concept.code == code);
    CodelistConcept {
        code: code.to_owned(),
        iri: authored.and_then(|concept| concept.iri.clone()),
        label: authored
            .and_then(|concept| concept.label.as_ref())
            .map(localized_text),
    }
}

fn sensitivity(classification: Classification) -> Sensitivity {
    match classification {
        Classification::Public => Sensitivity::Public,
        Classification::Internal => Sensitivity::Internal,
        Classification::Restricted => Sensitivity::Confidential,
    }
}

fn adms_status(status: ManifestProjectionDatasetStatus) -> AdmsStatus {
    match status {
        ManifestProjectionDatasetStatus::UnderDevelopment => AdmsStatus::UnderDevelopment,
        ManifestProjectionDatasetStatus::Active => AdmsStatus::Active,
        ManifestProjectionDatasetStatus::Completed => AdmsStatus::Completed,
        ManifestProjectionDatasetStatus::Deprecated => AdmsStatus::Deprecated,
        ManifestProjectionDatasetStatus::Withdrawn => AdmsStatus::Withdrawn,
    }
}

fn strip_null_members(value: &mut Value) {
    match value {
        Value::Object(object) => {
            object.retain(|_, child| {
                strip_null_members(child);
                !child.is_null()
            });
        }
        Value::Array(values) => {
            for child in values {
                strip_null_members(child);
            }
        }
        Value::Null | Value::Bool(_) | Value::Number(_) | Value::String(_) => {}
    }
}

fn manifest_diagnostic(error: MetadataError) -> Diagnostic {
    match error {
        MetadataError::VersionUnsupported => Diagnostic::error(
            "manifest_projection.invalid",
            "project.manifestProjection",
            "the Registry Manifest projection is invalid",
        ),
        MetadataError::Validation { errors } => {
            let path = errors
                .first()
                .map(|error| format!("project.manifestProjection.{}", error.path))
                .unwrap_or_else(|| "project.manifestProjection".to_owned());
            Diagnostic::error(
                "manifest_projection.invalid",
                path,
                "the Registry Manifest projection is invalid",
            )
        }
    }
}

fn manifest_canonicalization_diagnostic() -> Diagnostic {
    Diagnostic::error(
        "manifest_projection.canonicalization_failed",
        "project.manifestProjection",
        "the Registry Manifest projection could not be canonicalized",
    )
}

#[cfg(test)]
mod tests {
    use registry_manifest_core::FieldType;

    use super::project_field;
    use crate::contract::{Classification, FieldTypeSource};
    use crate::model::CompiledField;

    #[test]
    fn decimal_projection_preserves_the_canonical_string_wire_contract() {
        let projected = project_field(
            &CompiledField {
                id: "measurement".to_owned(),
                field_type: FieldTypeSource::Decimal {
                    precision: 12,
                    scale: 4,
                    minimum: None,
                    maximum: None,
                },
                required: true,
                classification: Classification::Internal,
                valid_time_role: None,
                physical_name: "field_measurement".to_owned(),
            },
            None,
            &[],
        )
        .expect("decimal is representable in the portable Manifest");

        assert_eq!(projected.field_type, FieldType::String);
        assert_eq!(
            projected.constraints.pattern.as_deref(),
            Some("^-?(0|[1-9][0-9]{0,7})\\.[0-9]{4}$")
        );
    }
}
