#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""
Synthetic API-key generator for data_gate performance testing.

Hashing scheme: data_gate expects env vars holding sha256:<64 lowercase hex chars>
where the hex is SHA-256(raw_token_bytes). This is stdlib hashlib; no external
deps needed.

Generates 5 tokens, writes an env file, and prints only the variable names and
the output path. Raw tokens and hashes are never printed to stdout.

Usage:
    uv run perf/scripts/generate_perf_keys.py --env-file target/perf/perf.env
    uv run perf/scripts/generate_perf_keys.py --env-file target/perf/perf.env --force
"""

import argparse
import hashlib
import os
import secrets
import sys
from pathlib import Path


# Key definitions: (id, hash_env_var, scopes list or None)
# Scopes are informational for the comment; the env file carries the hash only.
KEY_DEFS = [
    ("perf_rows",      "PERF_ROWS_KEY_HASH",      ["clinic_capacity:rows"]),
    ("perf_metadata",  "PERF_METADATA_KEY_HASH",   ["clinic_capacity:metadata"]),
    ("perf_aggregate", "PERF_AGGREGATE_KEY_HASH",  ["clinic_capacity:aggregate"]),
    ("perf_no_scope",  "PERF_NO_SCOPE_KEY_HASH",   ["other:metadata"]),
]

INVALID_TOKEN_VALUE = "not-a-real-token-xxxx"


def sha256_fingerprint(raw: str) -> str:
    """Return sha256:<64 lowercase hex chars> of the UTF-8-encoded raw token."""
    digest = hashlib.sha256(raw.encode("utf-8")).hexdigest()
    return f"sha256:{digest}"


def generate_token() -> str:
    """Return a URL-safe random token (~32 bytes of entropy, 43 chars)."""
    return secrets.token_urlsafe(32)


def build_env_lines(tokens: dict[str, str]) -> list[str]:
    """Build the env file lines from the token map. Never includes raw tokens."""
    lines = [
        "# data_gate perf test environment",
        "# Generated by generate_perf_keys.py. Do NOT commit this file.",
        "#",
        "# Token variables (raw bearer tokens for k6 / curl)",
        f"DATA_GATE_TOKEN={tokens['perf_rows']}",
        f"DATA_GATE_TOKEN_METADATA={tokens['perf_metadata']}",
        f"DATA_GATE_TOKEN_AGGREGATE={tokens['perf_aggregate']}",
        f"DATA_GATE_TOKEN_NO_SCOPE={tokens['perf_no_scope']}",
        f"DATA_GATE_TOKEN_INVALID={INVALID_TOKEN_VALUE}",
        "#",
        "# Routing defaults",
        "DATA_GATE_BASE_URL=http://127.0.0.1:18080",
        "DATA_GATE_DATASET_ID=clinic_capacity",
        "DATA_GATE_ENTITY=facility",
        "#",
        "# SHA-256 fingerprints consumed by data_gate at startup",
        "# (sha256:<64 lowercase hex chars> of the raw token above)",
    ]
    for key_id, hash_env, _ in KEY_DEFS:
        fingerprint = sha256_fingerprint(tokens[key_id])
        lines.append(f"{hash_env}={fingerprint}")
    return lines


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate synthetic API keys for data_gate perf testing."
    )
    parser.add_argument(
        "--env-file",
        default="target/perf/perf.env",
        help="Destination env file (default: target/perf/perf.env).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing env file.",
    )
    args = parser.parse_args()

    env_path = Path(args.env_file)

    if env_path.exists() and not args.force:
        print(
            f"Error: {env_path} already exists. Use --force to overwrite.",
            file=sys.stderr,
        )
        sys.exit(1)

    env_path.parent.mkdir(parents=True, exist_ok=True)

    # Generate one random token per keyed entry.
    tokens: dict[str, str] = {key_id: generate_token() for key_id, _, _ in KEY_DEFS}

    env_lines = build_env_lines(tokens)
    env_content = "\n".join(env_lines) + "\n"

    env_path.write_text(env_content, encoding="utf-8")
    # Restrict to owner read/write only.
    os.chmod(env_path, 0o600)

    # Report only the path and variable names, never values.
    print(f"Wrote: {env_path}")
    print("Variables written:")
    var_names = [
        "DATA_GATE_TOKEN",
        "DATA_GATE_TOKEN_METADATA",
        "DATA_GATE_TOKEN_AGGREGATE",
        "DATA_GATE_TOKEN_NO_SCOPE",
        "DATA_GATE_TOKEN_INVALID",
        "DATA_GATE_BASE_URL",
        "DATA_GATE_DATASET_ID",
        "DATA_GATE_ENTITY",
    ] + [hash_env for _, hash_env, _ in KEY_DEFS]
    for name in var_names:
        print(f"  {name}")


if __name__ == "__main__":
    main()
