// SPDX-License-Identifier: Apache-2.0
//! Integration tests for `XlsxFormat`.
//!
//! Covers the six mandatory cases from `decisions/wave-1.md` Section 6
//! (Track 3). Each test loads a fixture from `tests/fixtures_xlsx/`, calls
//! `XlsxFormat::decode`, and asserts the resulting `DecodedStream`.
//!
//! Fixtures are generated by `tests/fixtures_xlsx/generate.sh` (Python +
//! openpyxl). Commit the `.xlsx` files so CI does not need openpyxl.

use std::fs;
use std::path::Path;
use std::pin::Pin;
use std::sync::Arc;

use datafusion::arrow::array::{
    Array, BooleanArray, Date32Array, Float64Array, Int64Array, StringArray,
};
use datafusion::arrow::datatypes::{DataType, TimeUnit};
use futures::StreamExt;
use tokio::io::AsyncRead;

use data_gate::config::FieldType;
use data_gate::format::xlsx::XlsxFormat;
use data_gate::format::{Format, FormatError, FormatHints};
use data_gate::ingest::declared_schema::{DeclaredField, DeclaredSchema};

// ── helpers ──────────────────────────────────────────────────────────────────

fn fixture(name: &str) -> Pin<Box<dyn AsyncRead + Send + Unpin>> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures_xlsx")
        .join(name);
    let bytes = fs::read(&path).unwrap_or_else(|e| panic!("could not read {name}: {e}"));
    Box::pin(std::io::Cursor::new(bytes))
}

fn hints_default() -> FormatHints {
    FormatHints {
        sheet: None,
        header_row: Some(1),
        data_range: None,
        delimiter: None,
        quote: None,
        declared: DeclaredSchema::empty(),
    }
}

fn schema_with(fields: Vec<DeclaredField>) -> Arc<DeclaredSchema> {
    Arc::new(DeclaredSchema {
        strict: false,
        fields,
    })
}

fn field(name: &str, ty: FieldType) -> DeclaredField {
    DeclaredField {
        name: name.to_string(),
        ty,
        nullable: true,
        concept_uri: None,
        codelist: None,
        unit: None,
        language: None,
    }
}

// ── Test 1 ────────────────────────────────────────────────────────────────────

/// No sheet hint: should pick the first sheet ("data") and decode all 5 rows.
/// Asserts row count and Arrow types for each declared column.
#[tokio::test]
async fn decodes_simple_xlsx_first_sheet_by_default() {
    let hints = FormatHints {
        declared: schema_with(vec![
            field("id", FieldType::Integer),
            field("name", FieldType::String),
            field("amount", FieldType::Number),
            field("active", FieldType::Boolean),
            field("joined", FieldType::Date),
        ]),
        ..hints_default()
    };

    let decoded = XlsxFormat::new()
        .decode(fixture("simple.xlsx"), hints)
        .await
        .expect("decode should succeed");

    assert_eq!(
        decoded
            .observed_schema
            .field_with_name("id")
            .unwrap()
            .data_type(),
        &DataType::Int64
    );
    assert_eq!(
        decoded
            .observed_schema
            .field_with_name("name")
            .unwrap()
            .data_type(),
        &DataType::Utf8
    );
    assert_eq!(
        decoded
            .observed_schema
            .field_with_name("amount")
            .unwrap()
            .data_type(),
        &DataType::Float64
    );
    assert_eq!(
        decoded
            .observed_schema
            .field_with_name("active")
            .unwrap()
            .data_type(),
        &DataType::Boolean
    );
    assert_eq!(
        decoded
            .observed_schema
            .field_with_name("joined")
            .unwrap()
            .data_type(),
        &DataType::Date32
    );

    let batches: Vec<_> = decoded.batches.collect::<Vec<_>>().await;
    assert_eq!(batches.len(), 1, "V1 yields one batch");
    let batch = batches[0].as_ref().expect("batch should be Ok");
    assert_eq!(batch.num_rows(), 5, "five data rows");
    assert_eq!(batch.num_columns(), 5);

    // Spot-check the id column.
    let ids = batch
        .column_by_name("id")
        .expect("id column")
        .as_any()
        .downcast_ref::<Int64Array>()
        .expect("id: Int64Array");
    assert_eq!(ids.value(0), 1);
    assert_eq!(ids.value(4), 5);

    // Spot-check name.
    let names = batch
        .column_by_name("name")
        .expect("name column")
        .as_any()
        .downcast_ref::<StringArray>()
        .expect("name: StringArray");
    assert_eq!(names.value(0), "Alice");
    assert_eq!(names.value(1), "Bob");

    // Spot-check amount.
    let amounts = batch
        .column_by_name("amount")
        .expect("amount column")
        .as_any()
        .downcast_ref::<Float64Array>()
        .expect("amount: Float64Array");
    assert!((amounts.value(0) - 1250.50).abs() < 1e-6);

    // Spot-check active.
    let active = batch
        .column_by_name("active")
        .expect("active column")
        .as_any()
        .downcast_ref::<BooleanArray>()
        .expect("active: BooleanArray");
    assert!(active.value(0));
    assert!(!active.value(1));

    // joined is Date32; just assert it's present and non-null.
    let joined = batch
        .column_by_name("joined")
        .expect("joined column")
        .as_any()
        .downcast_ref::<Date32Array>()
        .expect("joined: Date32Array");
    assert!(!joined.is_null(0));
}

// ── Test 2 ────────────────────────────────────────────────────────────────────

/// `sheet: Some("details")` selects the second sheet in `two_sheets.xlsx`.
/// The "summary" sheet only has metadata; "details" has country/population.
#[tokio::test]
async fn selects_named_sheet_when_hint_present() {
    let hints = FormatHints {
        sheet: Some("details".to_string()),
        declared: schema_with(vec![
            field("country", FieldType::String),
            field("population", FieldType::Integer),
        ]),
        ..hints_default()
    };

    let decoded = XlsxFormat::new()
        .decode(fixture("two_sheets.xlsx"), hints)
        .await
        .expect("decode should succeed");

    let batches: Vec<_> = decoded.batches.collect::<Vec<_>>().await;
    let batch = batches[0].as_ref().expect("batch Ok");
    assert_eq!(batch.num_rows(), 3, "three country rows");

    let countries = batch
        .column_by_name("country")
        .expect("country")
        .as_any()
        .downcast_ref::<StringArray>()
        .expect("StringArray");
    assert_eq!(countries.value(0), "France");
    assert_eq!(countries.value(1), "Germany");
    assert_eq!(countries.value(2), "Italy");

    let pops = batch
        .column_by_name("population")
        .expect("population")
        .as_any()
        .downcast_ref::<Int64Array>()
        .expect("Int64Array");
    assert_eq!(pops.value(0), 68_000_000);
}

// ── Test 3 ────────────────────────────────────────────────────────────────────

/// `data_range: Some("A5:E10")` with `header_row: Some(5)`:
/// rows 1-4 are metadata to skip; row 5 is the header; rows 6-10 are data.
#[tokio::test]
async fn honors_data_range_anchors_header_and_body() {
    let hints = FormatHints {
        sheet: None,
        header_row: Some(5),
        data_range: Some("A5:E10".to_string()),
        declared: schema_with(vec![
            field("id", FieldType::Integer),
            field("name", FieldType::String),
            field("amount", FieldType::Number),
            field("active", FieldType::Boolean),
            field("joined", FieldType::Date),
        ]),
        ..hints_default()
    };

    let decoded = XlsxFormat::new()
        .decode(fixture("with_data_range.xlsx"), hints)
        .await
        .expect("decode should succeed");

    let batches: Vec<_> = decoded.batches.collect::<Vec<_>>().await;
    let batch = batches[0].as_ref().expect("batch Ok");
    assert_eq!(
        batch.num_rows(),
        5,
        "five data rows after skipping metadata"
    );
    assert_eq!(batch.num_columns(), 5);

    let ids = batch
        .column_by_name("id")
        .expect("id")
        .as_any()
        .downcast_ref::<Int64Array>()
        .expect("Int64Array");
    assert_eq!(ids.value(0), 10);
    assert_eq!(ids.value(4), 14);
}

// ── Test 4 ────────────────────────────────────────────────────────────────────

/// Excel serial date cells declared as Date should come out as Arrow Date32.
/// `simple.xlsx` has a "joined" column stored as Excel dates (openpyxl writes
/// them as DateTime values with a date format).
#[tokio::test]
async fn coerces_excel_date_serial_to_date32() {
    let hints = FormatHints {
        declared: schema_with(vec![
            field("id", FieldType::Integer),
            field("name", FieldType::String),
            field("amount", FieldType::Number),
            field("active", FieldType::Boolean),
            field("joined", FieldType::Date),
        ]),
        ..hints_default()
    };

    let decoded = XlsxFormat::new()
        .decode(fixture("simple.xlsx"), hints)
        .await
        .expect("decode should succeed");

    assert_eq!(
        decoded
            .observed_schema
            .field_with_name("joined")
            .unwrap()
            .data_type(),
        &DataType::Date32
    );

    let batches: Vec<_> = decoded.batches.collect::<Vec<_>>().await;
    let batch = batches[0].as_ref().expect("batch Ok");
    let joined = batch
        .column_by_name("joined")
        .expect("joined")
        .as_any()
        .downcast_ref::<Date32Array>()
        .expect("Date32Array");

    // Alice's date is 2020-01-15; days since UNIX epoch (1970-01-01) = 18276
    let expected_days = (date_to_days(2020, 1, 15)) as i32;
    assert_eq!(joined.value(0), expected_days, "Alice: 2020-01-15");

    // Eve's date is 2018-07-22
    let expected_eve = date_to_days(2018, 7, 22) as i32;
    assert_eq!(joined.value(4), expected_eve, "Eve: 2018-07-22");
}

/// Returns days since 1970-01-01 (UNIX epoch) for a given date.
fn date_to_days(year: i32, month: u32, day: u32) -> i64 {
    // Simple calculation: use chrono-compatible logic via time crate
    // We compute based on known leap-year rules.
    let y = year;
    let m = month as i32;
    let d = day as i32;
    // Days from 1970-01-01
    let days_from_year = |yr: i32| -> i64 {
        let yr = yr as i64 - 1;
        365 * yr + yr / 4 - yr / 100 + yr / 400
    };
    let days_in_months = [0i64, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334];
    let is_leap = (y % 4 == 0 && y % 100 != 0) || (y % 400 == 0);
    let leap_day = if is_leap && m > 2 { 1i64 } else { 0 };
    let doy = days_in_months[(m - 1) as usize] + d as i64 + leap_day;
    days_from_year(y) + doy - days_from_year(1970) - 1
}

// ── Test 5 ────────────────────────────────────────────────────────────────────

/// A column declared as Date that contains a non-parsable string cell should
/// yield `FormatError::Parse` with row and column context.
#[tokio::test]
async fn rejects_mistyped_date_column_with_parse_error() {
    let hints = FormatHints {
        declared: schema_with(vec![
            field("id", FieldType::Integer),
            field("name", FieldType::String),
            field("joined", FieldType::Date),
        ]),
        ..hints_default()
    };

    let result = XlsxFormat::new()
        .decode(fixture("mistyped_date.xlsx"), hints)
        .await;

    match result {
        Err(FormatError::Parse(msg)) => {
            // Error message should mention the bad value or column.
            assert!(
                msg.contains("joined") || msg.contains("not-a-date") || msg.contains("row"),
                "parse error should have context: {msg}"
            );
        }
        Ok(decoded) => {
            // Error may also surface in the batch stream (acceptable).
            let batches: Vec<_> = decoded.batches.collect::<Vec<_>>().await;
            let has_error = batches.iter().any(|b| b.is_err());
            assert!(has_error, "expected a parse error for mistyped date");
            let err_msg = batches
                .iter()
                .filter_map(|b| b.as_ref().err())
                .next()
                .unwrap()
                .to_string();
            assert!(
                err_msg.contains("joined")
                    || err_msg.contains("not-a-date")
                    || err_msg.contains("row"),
                "parse error should have context: {err_msg}"
            );
        }
        Err(other) => {
            panic!("expected FormatError::Parse, got: {other}");
        }
    }
}

// ── Test 6 ────────────────────────────────────────────────────────────────────

/// With `DeclaredSchema::empty()`, all columns from `simple.xlsx` should be
/// inferred and default to Utf8 (since the decoder has no type hints).
#[tokio::test]
async fn infers_utf8_when_no_declared_schema() {
    let decoded = XlsxFormat::new()
        .decode(fixture("simple.xlsx"), hints_default())
        .await
        .expect("decode should succeed");

    let schema = &decoded.observed_schema;
    for f in schema.fields() {
        assert_eq!(
            *f.data_type(),
            DataType::Utf8,
            "field {} should be Utf8 without declared schema",
            f.name()
        );
    }

    let batches: Vec<_> = decoded.batches.collect::<Vec<_>>().await;
    let batch = batches[0].as_ref().expect("batch Ok");
    assert_eq!(batch.num_rows(), 5);
    assert_eq!(batch.num_columns(), 5);
}

// ── Decompression-bomb guard (security review 2026-05-16) ─────────────────

/// Build a minimal, valid XLSX (a ZIP) whose `<dimension>` element advertises
/// a huge cell count while the on-disk payload is tiny. Used to reproduce the
/// XLSX cell-count bomb described in `docs/security-review-2026-05-16.md`.
///
/// `dim_ref` is the A1-notation reference to embed in the sheet's `<dimension>`
/// element (e.g. `"A1:Z10000000"` for a 26 col x 10M row sheet).
fn build_bomb_xlsx(dim_ref: &str) -> Vec<u8> {
    use std::io::Write;
    use zip::write::SimpleFileOptions;
    use zip::ZipWriter;

    // Minimal OOXML package. We only need: [Content_Types].xml, the
    // workbook _rels, the workbook itself, and one worksheet whose
    // <dimension> advertises the bomb. Shared strings are unnecessary
    // because the single data cell carries an inline string.
    let content_types = br#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
</Types>"#;

    let root_rels = br#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>"#;

    let workbook = br#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
          xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <sheets>
    <sheet name="data" sheetId="1" r:id="rId1"/>
  </sheets>
</workbook>"#;

    let workbook_rels = br#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
</Relationships>"#;

    // The sheet declares a giant dimension via `<dimension ref="...">`,
    // but the actual <sheetData> contains a single inline-string cell.
    let sheet = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <dimension ref="{dim_ref}"/>
  <sheetData>
    <row r="1"><c r="A1" t="inlineStr"><is><t>hdr</t></is></c></row>
  </sheetData>
</worksheet>"#
    );

    let mut buf: Vec<u8> = Vec::new();
    {
        let cursor = std::io::Cursor::new(&mut buf);
        let mut zip = ZipWriter::new(cursor);
        let opts =
            SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated);

        zip.start_file("[Content_Types].xml", opts).unwrap();
        zip.write_all(content_types).unwrap();
        zip.start_file("_rels/.rels", opts).unwrap();
        zip.write_all(root_rels).unwrap();
        zip.start_file("xl/workbook.xml", opts).unwrap();
        zip.write_all(workbook).unwrap();
        zip.start_file("xl/_rels/workbook.xml.rels", opts).unwrap();
        zip.write_all(workbook_rels).unwrap();
        zip.start_file("xl/worksheets/sheet1.xml", opts).unwrap();
        zip.write_all(sheet.as_bytes()).unwrap();
        zip.finish().unwrap();
    }
    buf
}

/// The synthetic-bomb helper above must actually be a workbook calamine
/// will open. This sanity test uses a tiny dimension so `worksheet_range`
/// is cheap and the bomb-guard path is not exercised. If this fails, the
/// bomb tests below are also untrustworthy.
#[tokio::test]
async fn synthetic_xlsx_helper_produces_a_workbook_calamine_can_open() {
    let bytes = build_bomb_xlsx("A1:A1");
    let decoded = XlsxFormat::new()
        .decode(Box::pin(std::io::Cursor::new(bytes)), hints_default())
        .await
        .expect("synthetic xlsx should decode");
    let batches: Vec<_> = decoded.batches.collect::<Vec<_>>().await;
    let batch = batches[0].as_ref().expect("batch");
    // Header row only; no data rows.
    assert_eq!(batch.num_rows(), 0);
}

/// A workbook whose `<dimension>` advertises more than `MAX_XLSX_CELLS`
/// cells must be rejected with a `LimitExceeded` error before calamine's
/// `from_sparse` allocates `vec![Default; height*width]`. Reproduces the
/// XLSX bomb from the 2026-05-16 security review.
///
/// The cap in `src/format/xlsx.rs` is 10_000_000. The dimension below
/// (`A1:L1000000` = 12 columns x 1,000,000 rows = 12,000,000 cells) is
/// just over the cap; small enough that this test does not OOM the
/// process when the cap is absent (defensive against false negatives).
#[tokio::test]
async fn rejects_xlsx_when_declared_dimension_exceeds_cell_cap() {
    let bytes = build_bomb_xlsx("A1:L1000000");
    let result = XlsxFormat::new()
        .decode(Box::pin(std::io::Cursor::new(bytes)), hints_default())
        .await;

    match result {
        Err(FormatError::LimitExceeded(_)) => {}
        Err(other) => panic!("expected FormatError::LimitExceeded, got {other:?}"),
        Ok(_) => panic!("expected the cell-count cap to reject this workbook"),
    }
}

// ── Timestamp test (bonus) ─────────────────────────────────────────────────

/// A column declared as Timestamp from a Date cell (Excel DateTime) should
/// come out as Timestamp(Millisecond, "UTC").
#[tokio::test]
async fn coerces_excel_date_serial_to_timestamp_millis() {
    let hints = FormatHints {
        declared: schema_with(vec![
            field("id", FieldType::Integer),
            field("name", FieldType::String),
            field("amount", FieldType::Number),
            field("active", FieldType::Boolean),
            field("joined", FieldType::Timestamp),
        ]),
        ..hints_default()
    };

    let decoded = XlsxFormat::new()
        .decode(fixture("simple.xlsx"), hints)
        .await
        .expect("decode should succeed");

    let joined_field = decoded.observed_schema.field_with_name("joined").unwrap();
    assert_eq!(
        joined_field.data_type(),
        &DataType::Timestamp(TimeUnit::Millisecond, Some("UTC".into())),
        "joined should be Timestamp(Millisecond, UTC)"
    );
}
