# SPDX-License-Identifier: Apache-2.0

FROM python:3.12.3-slim-bookworm AS python-runtime

FROM postgres:bookworm

COPY --from=python-runtime /usr/local/ /usr/local/

ENV PATH="/usr/local/bin:${PATH}"
