PRAGMA foreign_keys = ON;

CREATE TABLE source_assistance_enrolments (
    enrolment_reference TEXT PRIMARY KEY NOT NULL,
    masked_enrolment_reference TEXT NOT NULL,
    record_revision TEXT NOT NULL,
    lifecycle_state TEXT NOT NULL,
    recorded_at TEXT NOT NULL,
    programme_code TEXT NOT NULL,
    enrolment_status TEXT NOT NULL,
    valid_through TEXT,
    service_area_code TEXT NOT NULL,
    case_reference TEXT NOT NULL,
    person_reference TEXT NOT NULL
) STRICT;

INSERT INTO source_assistance_enrolments VALUES
('ENROL-SYNTH-0001', 'ENROL-SYNTH-0001', '3', 'ACTIVE', '2026-07-01T09:00:00Z', 'PROGRAMME-A', 'ELIGIBLE', '2026-12-31', 'AREA-A', 'CASE-SYNTH-0001', 'PERSON-SYNTH-0001'),
('ENROL-SYNTH-0002', 'ENROL-SYNTH-0002', '2', 'SUSPENDED', '2026-07-02T09:00:00Z', 'PROGRAMME-B', 'SUSPENDED', NULL, 'AREA-B', 'CASE-SYNTH-0002', 'PERSON-SYNTH-0002'),
('ENROL-SYNTH-0101', 'ENROL-SYNTH-0101', '1', 'ACTIVE', '2026-07-03T09:00:00Z', 'PROGRAMME-A', 'ELIGIBLE', '2026-12-31', 'AREA-A', 'CASE-SYNTH-AMBIG', 'PERSON-SYNTH-AMBIG'),
('ENROL-SYNTH-0102', 'ENROL-SYNTH-0102', '1', 'ACTIVE', '2026-07-03T09:05:00Z', 'PROGRAMME-B', 'ELIGIBLE', '2026-12-31', 'AREA-A', 'CASE-SYNTH-AMBIG', 'PERSON-SYNTH-AMBIG'),
('ENROL-SYNTH-BAD1', 'ENROL-SYNTH-BAD1', '', 'ACTIVE', '2026-07-04T09:00:00Z', 'PROGRAMME-A', 'ELIGIBLE', '2026-12-31', 'AREA-A', 'CASE-SYNTH-BAD1', 'PERSON-SYNTH-BAD1'),
('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', '1', 'ACTIVE', '2026-07-05T09:00:00Z', 'PROGRAMME-A', 'ELIGIBLE', '2026-12-31', 'AREA-A', 'CASE-SYNTH-BAD2', 'PERSON-SYNTH-BAD2'),
('ENROL-SYNTH-XFORM', replace(hex(zeroblob(2050)), '0', 'A'), '1', 'ACTIVE', '2026-07-06T09:00:00Z', 'PROGRAMME-A', 'ELIGIBLE', '2026-12-31', 'AREA-A', 'CASE-SYNTH-XFORM', 'PERSON-SYNTH-XFORM');

CREATE VIEW relay_assistance_enrolments AS
SELECT enrolment_reference,
       masked_enrolment_reference,
       record_revision,
       lifecycle_state,
       recorded_at,
       programme_code,
       enrolment_status,
       valid_through,
       service_area_code,
       case_reference,
       person_reference
FROM source_assistance_enrolments;
