// The package's actual entry point. `index.d.ts` is auto-generated by
// `napi build --platform` on every build and is what `check:types` diffs
// byte-for-byte; the hand-written surface below is checked separately, by
// `__test__/drift.test.js`, against the real module.
export * from './index'

/** The signed response encoding closed before one request is sent. */
export type EvidenceResponseFormat = 'signed-jws' | 'sd-jwt-vc'

/** The request-spec input accepted by `EvidenceClient.prepare`. */
export interface EvidenceRequestSpec {
  responseFormat: EvidenceResponseFormat
  requirement: string
  purpose: string
  audience: string
  evidenceType: string
  issuedBy: string
  providedBy: string
  configurationRevision: string
  expectedAssuranceProfile: unknown
  subjects: ReadonlyArray<{
    role: string
    selectorProfile: string
    selectorValues?: Readonly<Record<string, string | number | boolean>> | null
  }>
  expectedOutputs: ReadonlyArray<Readonly<Record<string, unknown>>>
  maximumAssertionLifetimeSeconds: number
  clockSkewSeconds: number
  subjectExpectations:
    | 'acceptFirstUse'
    | { pinned: ReadonlyArray<{ role: string; binding: string }> }
}

/**
 * The stable eight-kind error envelope every mapped Evidence Node failure
 * carries, as properties on a thrown `Error` (see `src/lib.rs`'s
 * `to_napi_error` and `src/convert.rs`'s `map_client_error` for the Rust side
 * of this contract).
 *
 * `kind` is always present. The rest are present only when the underlying
 * failure carries them:
 * - `status`: `denied`, `protocol`, and any `token` failure whose `tokenKind`
 *   is `protocol`
 * - `code`: `denied`, `protocol` (optional), `verification`, and any `token`
 *   failure whose `tokenKind` is `refused`
 * - `operation`: `denied`, `not_available`, `protocol` (all optional)
 * - `retryAfterSeconds`: `denied`, `protocol` (both optional)
 * - `transportKind`: `transport`, and any `token` failure whose `tokenKind`
 *   is `transport`
 * - `tokenKind`: every `token` failure
 */
export declare class EvidenceClientError extends Error {
  readonly kind: string
  readonly status?: number
  readonly code?: string
  readonly operation?: string
  readonly retryAfterSeconds?: number
  readonly transportKind?: string
  readonly tokenKind?: string
}
