// The package's actual entry point. `index.d.ts` is auto-generated by
// `napi build --platform` on every build and is what `check:types` diffs
// byte-for-byte; the hand-written surface below is checked separately, by
// `__test__/drift.test.js`, against the real module.
export * from './index'

/** The signed response encoding closed before one request is sent. */
export type EvidenceResponseFormat = 'signed-jws' | 'sd-jwt-vc'

/**
 * A holder public key a request may present, as a public JWK.
 *
 * Public material only. There is no member here for a private key half, and
 * a key carrying one (`d`, or any other private JWK member) is refused with
 * that stated as the reason: the private half stays with whoever holds it,
 * and this package never asks for it, holds it, or sends it.
 */
export interface HolderPublicKey {
  kty: 'EC'
  crv: 'P-256'
  /** The x coordinate, unpadded base64url. */
  x: string
  /** The y coordinate, unpadded base64url. */
  y: string
  alg?: 'ES256'
  kid?: string
}

/** The request-spec input accepted by `EvidenceClient.prepare`. */
export interface EvidenceRequestSpec {
  responseFormat: EvidenceResponseFormat
  requirement: string
  purpose: string
  audience: string
  evidenceType: string
  issuedBy: string
  providedBy: string
  configurationRevision: string
  expectedAssuranceProfile: unknown
  subjects: ReadonlyArray<{
    role: string
    selectorProfile: string
    selectorValues?: Readonly<Record<string, string | number | boolean>> | null
  }>
  /**
   * Holder public keys this request presents, in the order the caller wants
   * them answered. Omit it (or pass an empty array) to present none, which is
   * the request this package has always sent.
   *
   * A request presenting several keys can be answered with one credential per
   * key, in that same order; see `SdJwtVcBatchResponse`.
   */
  holderKeys?: ReadonlyArray<HolderPublicKey>
  expectedOutputs: ReadonlyArray<Readonly<Record<string, unknown>>>
  maximumAssertionLifetimeSeconds: number
  clockSkewSeconds: number
  subjectExpectations:
    | 'acceptFirstUse'
    | { pinned: ReadonlyArray<{ role: string; binding: string }> }
}

/** One positional item in a multi-subject Evidence request batch. */
export interface EvidenceRequestBatchItemSpec {
  subjects: ReadonlyArray<{
    role: string
    selectorProfile: string
    selectorValues?: Readonly<Record<string, string | number | boolean>> | null
  }>
  subjectExpectations:
    | 'acceptFirstUse'
    | { pinned: ReadonlyArray<{ role: string; binding: string }> }
}

/**
 * The common request inputs and ordered item inputs accepted by
 * `EvidenceClient.prepareBatch`.
 */
export interface EvidenceRequestBatchSpec {
  requirement: string
  purpose: string
  audience: string
  evidenceType: string
  issuedBy: string
  providedBy: string
  configurationRevision: string
  expectedAssuranceProfile: unknown
  expectedOutputs: ReadonlyArray<Readonly<Record<string, unknown>>>
  maximumAssertionLifetimeSeconds: number
  clockSkewSeconds: number
  items: ReadonlyArray<EvidenceRequestBatchItemSpec>
}

/**
 * The stable eight-kind error envelope every mapped Evidence Node failure
 * carries, as properties on a thrown `Error` (see `src/lib.rs`'s
 * `to_napi_error` and `src/convert.rs`'s `map_client_error` for the Rust side
 * of this contract).
 *
 * `kind` is always present. The rest are present only when the underlying
 * failure carries them:
 * - `status`: `denied`, `protocol`, and any `token` failure whose `tokenKind`
 *   is `protocol`
 * - `code`: `denied`, `protocol` (optional), `verification`, and any `token`
 *   failure whose `tokenKind` is `refused`
 * - `operation`: `denied`, `not_available`, `protocol` (all optional)
 * - `retryAfterSeconds`: `denied`, `protocol` (both optional)
 * - `transportKind`: `transport`, and any `token` failure whose `tokenKind`
 *   is `transport`
 * - `tokenKind`: every `token` failure
 */
export declare class EvidenceClientError extends Error {
  readonly kind: string
  readonly status?: number
  readonly code?: string
  readonly operation?: string
  readonly retryAfterSeconds?: number
  readonly transportKind?: string
  readonly tokenKind?: string
}
