/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A relying party's connection to one Evidence deployment. */
export declare class EvidenceClient {
  /**
   * Build a client for one deployment. `trustedJwks` and `revokedKeyIds` are
   * mandatory trust inputs. A key set or revoked-key list the verifier could
   * never use is refused, exactly as the Rust configuration refuses it.
   *
   * `maxResponseBytes` bounds the signed response `send` reads.
   * `maxMetadataBytes` bounds the documents `discover` and `fetchJwks` read,
   * which are neither signed nor verified, and is a separate decision.
   */
  constructor(config: any)
  /**
   * Close the expectations for one request and generate its nonce. No I/O
   * happens here. The returned request is good for exactly one exchange:
   * spend it with `send` or `requestAndVerify`.
   */
  prepare(spec: { responseFormat: 'signed-jws' | 'sd-jwt-vc'; [key: string]: any }): PreparedEvidenceRequest
  /**
   * Read the request shapes this requester is entitled to send. Discovery
   * is authoring input, not a trust anchor: it never supplies verification
   * expectations for a request already in flight.
   */
  discover(): Promise<any>
  /**
   * Read the deployment's published verification key set, for an
   * out-of-band pinning workflow. Verification never calls this: a key set
   * fetched from the same origin as the response it would verify
   * establishes nothing.
   */
  fetchJwks(): Promise<any>
  /**
   * Send one prepared request and read the signed response.
   *
   * `prepared` allows exactly one send: a second call with the same object
   * rejects with the configuration failure the Rust layer already
   * produces, without reaching the deployment. Retrying means preparing
   * again, for a fresh nonce.
   */
  send(prepared: PreparedEvidenceRequest): Promise<RawEvidenceResponse>
  /**
   * Verify a signed response against the policy its request closed, as of
   * now. The trusted key set is the one pinned at construction, always.
   *
   * Unlike sending, verifying is unrestricted: it is offline and
   * idempotent, so a retained response may be re-verified against a
   * retained prepared request as often as needed, including after the
   * single send has been spent.
   */
  verify(prepared: PreparedEvidenceRequest, response: RawEvidenceResponse): VerifiedEvidence
  /**
   * Request evidence and verify it in one step. This spends the single
   * send `prepared` allows, exactly as `send` does, so calling it twice
   * with one prepared request fails locally on the second call.
   */
  requestAndVerify(prepared: PreparedEvidenceRequest): Promise<VerifiedEvidence>
  /**
   * Verify a retained response as of an explicit instant, given as
   * milliseconds since the Unix epoch.
   *
   * `verify` judges a response against the current clock, which is right
   * when the response has just arrived. This variant names the instant
   * instead, for re-verifying a retained response or replaying a retained
   * transaction record at the instant the original decision was made.
   *
   * A past instant is the direction that costs something: naming a stale
   * instant accepts an assertion whose validity interval has since
   * elapsed, because the question asked is whether it was acceptable then,
   * and the answer stays yes forever. A live trust decision calls `verify`,
   * not this.
   */
  verifyAsOf(prepared: PreparedEvidenceRequest, response: RawEvidenceResponse, asOfMillis: number): VerifiedEvidence
}

/**
 * One request, closed and nonce-bearing, before any byte has left the
 * process.
 *
 * There is no constructor exposed to JS: the only way to obtain one is
 * `EvidenceClient.prepare`, which mirrors the real type having no public
 * constructor of its own either.
 */
export declare class PreparedEvidenceRequest {
  /** The nonce this request carries. Retain it with the transaction record. */
  get requestNonce(): string
  /**
   * The closed verification policy, with the subject set as `prepare` left
   * it.
   */
  get policyDocument(): any
  /**
   * `"acceptFirstUse"` or `{ pinned: [{ role, binding }, ...] }`, exactly as
   * this request was prepared.
   */
  get subjectExpectations(): any
}

/**
 * A signed response, read but not yet judged.
 *
 * There is no constructor exposed to JS: the real Rust type has no public
 * constructor either, so the only way to obtain one is `EvidenceClient.send`.
 */
export declare class RawEvidenceResponse {
  /**
   * The signed response bytes, exactly as received. Nothing in them has
   * been trusted yet; `verify` is what judges them.
   */
  get body(): Buffer
  /**
   * The deployment's opaque identifier for this exchange, for support
   * correlation.
   */
  get operation(): string | null
}

/**
 * A response that satisfied every expectation.
 *
 * Unlike the two classes above, this crosses as a plain object: it is a
 * terminal result nothing hands back into a later call, so there is no
 * single-send flag or unconstructible real type to protect by staying
 * opaque.
 */
export interface VerifiedEvidence {
  /** The verified payload, serialized field for field with no hand mapping. */
  evidence: any
  /**
   * The deployment's opaque identifier for the exchange that produced this
   * payload.
   */
  operation?: string
  /**
   * The role-bound subject bindings this payload carries. Persist these
   * after a first-use acceptance and pass them back as `subjectExpectations:
   * { pinned: [...] }` from then on.
   */
  pinnedSubjectExpectations: any
}
