#!/bin/sh
# Generated by docs/site/scripts/generate-registryctl-example-overlays.mjs.
# Apply only to the pristine HTTP starter embedded in the matching Registryctl release.
set -eu

if ! command -v python3 >/dev/null 2>&1; then
  printf '%s\n' 'python3 is required to verify the HTTP starter closure' >&2
  exit 1
fi

python3 - <<'REGISTRYCTL_STARTER_VALIDATION_PY'
import hashlib
from pathlib import Path

expected = {
  ".gitignore": "84a80d00398b512ef755f17c1764c15b491058265d06d2cea71af37641324b83",
  "environments/local.yaml": "0ae0ce73cd6a775e188aaa0caed37cccce378c392aa021544872b16d6f0047a6",
  "integrations/person-record/fixtures/active.yaml": "4f0b0afa2cd1ac597e2d55a6bef4accee4549e7b74520fd23df10dde2fc02fc3",
  "integrations/person-record/fixtures/ambiguous.yaml": "6a375aa916a0b6b8dba04702b50cd7b1ec600063073c64881a9b62c31f16f232",
  "integrations/person-record/fixtures/no-match.yaml": "f7968b31cee08af79d6160e1a3bb99fdc4962fcfc7ccd13b92fe35f0d87367a5",
  "integrations/person-record/integration.yaml": "2b4950e1938e4d8345b7952480daa46e17abfd13ba2a8b42666b34adf7e02412",
  "README.md": "fb9994c4d4859c9d8672ac90b5960edb58eef63a65a4b096068409dc964be63b",
  "registry-stack.yaml": "b92ffdaffc401e5853570bad714eeba93a5f47685da9cffbd4f533fe010330b9"
}
ignored_roots = {".registry-stack-editor", ".vscode", ".zed"}
transport_files = {"jsonplaceholder-todo-live-overlay-v1.sh", "jsonplaceholder-todo-live-overlay-v1.sh.sha256"}
root = Path.cwd()

for name in ignored_roots:
    path = root / name
    if path.exists() and (path.is_symlink() or not path.is_dir()):
        raise SystemExit(f"HTTP starter editor path is not a real directory: {name}")
for name in transport_files:
    path = root / name
    if path.exists() and (path.is_symlink() or not path.is_file()):
        raise SystemExit(f"overlay transport path is not a regular file: {name}")

actual = {}
for path in root.rglob("*"):
    relative = path.relative_to(root).as_posix()
    if relative.split("/", 1)[0] in ignored_roots or relative in transport_files:
        continue
    if path.is_symlink():
        raise SystemExit(f"HTTP starter closure contains a symbolic link: {relative}")
    if path.is_file():
        actual[relative] = hashlib.sha256(path.read_bytes()).hexdigest()
    elif not path.is_dir():
        raise SystemExit(f"HTTP starter closure contains a non-file entry: {relative}")

missing = sorted(set(expected) - set(actual))
unexpected = sorted(set(actual) - set(expected))
changed = sorted(path for path in expected.keys() & actual.keys() if expected[path] != actual[path])
if missing or unexpected or changed:
    details = []
    if missing:
        details.append("missing=" + ",".join(missing))
    if unexpected:
        details.append("unexpected=" + ",".join(unexpected))
    if changed:
        details.append("changed=" + ",".join(changed))
    raise SystemExit("HTTP starter closure does not match this release: " + "; ".join(details))
REGISTRYCTL_STARTER_VALIDATION_PY

rm -r integrations/person-record

mkdir -p 'environments'
cat >'environments/local.yaml' <<'REGISTRYCTL_ENVIRONMENTS_LOCAL_YAML_EOF'
version: 1

development:
  source_mode: synthetic
  default_integration: public-todo
  default_fixture: completed-todo

integrations:
  public-todo:
    source:
      origin: https://public-json-source.invalid

issuance:
  issuer: did:web:notary.invalid
  signing_kid: project-issuer-key
  signing_key: { secret: REGISTRY_NOTARY_ISSUER_JWK }
  generation: 1

callers:
  evidence-client:
    api_key_fingerprint: { secret: EVIDENCE_CLIENT_TOKEN_HASH }
    scopes: ["evidence:todo:read"]

relay:
  origin: https://relay.internal.invalid
  issuer: https://workload-issuer.internal.invalid
  jwks_url: https://workload-issuer.internal.invalid/.well-known/jwks.json
  audience: registry-relay
  allowed_clients: [fictional-relay-client]

notary_relay:
  base_url: http://registry-relay-consultation:8080
  workload_client_id: fictional-registry-notary
  token_file: /run/secrets/relay-workload-token

deployment:
  profile: local
  relay: { service: fictional-registry-relay }
  notary: { service: fictional-registry-notary }
REGISTRYCTL_ENVIRONMENTS_LOCAL_YAML_EOF

mkdir -p 'environments'
cat >'environments/public-demo-missing.yaml' <<'REGISTRYCTL_ENVIRONMENTS_PUBLIC_DEMO_MISSING_YAML_EOF'
version: 1

development:
  source_mode: operator_bound
  default_integration: public-todo
  default_fixture: no-todo

integrations:
  public-todo:
    source:
      origin: https://jsonplaceholder.typicode.com

issuance:
  issuer: did:web:notary.invalid
  signing_kid: project-issuer-key
  signing_key: { secret: REGISTRY_NOTARY_ISSUER_JWK }
  generation: 1

callers:
  evidence-client:
    api_key_fingerprint: { secret: EVIDENCE_CLIENT_TOKEN_HASH }
    scopes: ["evidence:todo:read"]

relay:
  origin: https://relay.internal.invalid
  issuer: https://workload-issuer.internal.invalid
  jwks_url: https://workload-issuer.internal.invalid/.well-known/jwks.json
  audience: registry-relay
  allowed_clients: [fictional-relay-client]

notary_relay:
  base_url: http://registry-relay-consultation:8080
  workload_client_id: fictional-registry-notary
  token_file: /run/secrets/relay-workload-token

deployment:
  profile: local
  relay: { service: fictional-registry-relay }
  notary: { service: fictional-registry-notary }
REGISTRYCTL_ENVIRONMENTS_PUBLIC_DEMO_MISSING_YAML_EOF

mkdir -p 'environments'
cat >'environments/public-demo.yaml' <<'REGISTRYCTL_ENVIRONMENTS_PUBLIC_DEMO_YAML_EOF'
version: 1

development:
  source_mode: operator_bound
  default_integration: public-todo
  default_fixture: completed-todo

integrations:
  public-todo:
    source:
      origin: https://jsonplaceholder.typicode.com

issuance:
  issuer: did:web:notary.invalid
  signing_kid: project-issuer-key
  signing_key: { secret: REGISTRY_NOTARY_ISSUER_JWK }
  generation: 1

callers:
  evidence-client:
    api_key_fingerprint: { secret: EVIDENCE_CLIENT_TOKEN_HASH }
    scopes: ["evidence:todo:read"]

relay:
  origin: https://relay.internal.invalid
  issuer: https://workload-issuer.internal.invalid
  jwks_url: https://workload-issuer.internal.invalid/.well-known/jwks.json
  audience: registry-relay
  allowed_clients: [fictional-relay-client]

notary_relay:
  base_url: http://registry-relay-consultation:8080
  workload_client_id: fictional-registry-notary
  token_file: /run/secrets/relay-workload-token

deployment:
  profile: local
  relay: { service: fictional-registry-relay }
  notary: { service: fictional-registry-notary }
REGISTRYCTL_ENVIRONMENTS_PUBLIC_DEMO_YAML_EOF

mkdir -p 'integrations/public-todo/fixtures'
cat >'integrations/public-todo/fixtures/ambiguous.yaml' <<'REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_FIXTURES_AMBIGUOUS_YAML_EOF'
name: ambiguous-todo
classification: synthetic
input: { todo_id: "4" }
interactions:
  - expect:
      method: GET
      path: /todos/4
    respond: { status: 409, body: {} }
expect: { outcome: ambiguous }
REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_FIXTURES_AMBIGUOUS_YAML_EOF

mkdir -p 'integrations/public-todo/fixtures'
cat >'integrations/public-todo/fixtures/completed.yaml' <<'REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_FIXTURES_COMPLETED_YAML_EOF'
name: completed-todo
classification: synthetic
request:
  target:
    type: Person
    identifiers: [{ scheme: public_todo_id, value: "4" }]
  claims: [todo-record-exists]
  disclosure: predicate
  format: application/vnd.registry-notary.claim-result+json
  purpose: public-source-connection-demonstration
input: { todo_id: "4" }
interactions:
  - expect:
      method: GET
      path: /todos/4
    respond:
      status: 200
      body:
        userId: 1
        id: 4
        title: et porro tempora
        completed: true
expect:
  outcome: match
  outputs: { completed: true }
  claims: { todo-record-exists: true, todo-completed: true }
REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_FIXTURES_COMPLETED_YAML_EOF

mkdir -p 'integrations/public-todo/fixtures'
cat >'integrations/public-todo/fixtures/no-match.yaml' <<'REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_FIXTURES_NO_MATCH_YAML_EOF'
name: no-todo
classification: synthetic
request:
  target:
    type: Person
    identifiers: [{ scheme: public_todo_id, value: "999999" }]
  claims: [todo-record-exists]
  disclosure: predicate
  format: application/vnd.registry-notary.claim-result+json
  purpose: public-source-connection-demonstration
input: { todo_id: "999999" }
interactions:
  - expect:
      method: GET
      path: /todos/999999
    respond: { status: 404, body: {} }
expect:
  outcome: no_match
  outputs: {}
  claims: { todo-record-exists: false, todo-completed: null }
REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_FIXTURES_NO_MATCH_YAML_EOF

mkdir -p 'integrations/public-todo'
cat >'integrations/public-todo/integration.yaml' <<'REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_INTEGRATION_YAML_EOF'
version: 1
id: public-todo
revision: 1

source:
  product: jsonplaceholder
  versions:
    unverified: [public-demo-api]
  auth: { type: none }

input:
  todo_id:
    role: selector
    type: string
    maxLength: 16

capability:
  http:
    request:
      method: GET
      path: /todos/{input.todo_id}
    response:
      no_match: [404]
      ambiguous: [409]

outputs:
  completed:
    type: boolean
    x-registry-source: /completed

not_applicable:
  subject_mismatch:
    rationale: The public demonstration response has no reviewed institutional identifier contract to compare with the requested todo identifier.
    request_fixture: completed-todo
REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_INTEGRATION_YAML_EOF

mkdir -p '.'
cat >'registry-stack.yaml' <<'REGISTRYCTL_REGISTRY_STACK_YAML_EOF'
version: 1

registry:
  id: public-json-live-demo

integrations:
  public-todo:
    file: integrations/public-todo/integration.yaml

services:
  todo-verification:
    kind: evidence
    version: 1
    purpose: public-source-connection-demonstration
    legal_basis: public-service-delivery
    consent: not_required
    access:
      scopes: ["evidence:todo:read"]
    consultations:
      todo:
        integration: public-todo
        input:
          todo_id: request.target.identifiers.public_todo_id
    claims:
      todo-record-exists:
        cel: todo.matched
        disclosure: predicate
      todo-completed:
        output: todo.completed
        disclosure: value
    credential_profiles:
      todo-status:
        format: dc+sd-jwt
        type: https://credentials.invalid/public-todo-status/v1
        validity: 10m
        claims: [todo-record-exists, todo-completed]
REGISTRYCTL_REGISTRY_STACK_YAML_EOF

printf '%s\n' 'Applied the optional no-credential public JSON source demonstration overlay.'
