#!/bin/sh
# Generated by docs/site/scripts/generate-registryctl-example-overlays.mjs.
# Apply only to the pristine HTTP starter embedded in the matching Registryctl release.
set -eu

if ! command -v python3 >/dev/null 2>&1; then
  printf '%s\n' 'python3 is required to verify the HTTP starter closure' >&2
  exit 1
fi

python3 - <<'REGISTRYCTL_STARTER_VALIDATION_PY'
import hashlib
from pathlib import Path

expected = {
  ".gitignore": "84a80d00398b512ef755f17c1764c15b491058265d06d2cea71af37641324b83",
  "environments/local.yaml": "3af49441f405f725b25c9b1075c408fcd4b768b2b0bbd70a59b04c878ae8df45",
  "integrations/person-record/fixtures/active.yaml": "df873d90889c90ccc30132c5b911e555d1a9816ba409bc9cb37504a6466650b7",
  "integrations/person-record/fixtures/ambiguous.yaml": "6a375aa916a0b6b8dba04702b50cd7b1ec600063073c64881a9b62c31f16f232",
  "integrations/person-record/fixtures/no-match.yaml": "415ac27bc7e212e2a92b46e51c9e7282bddd9722aeaf4530557061f10d89b33e",
  "integrations/person-record/integration.yaml": "2b4950e1938e4d8345b7952480daa46e17abfd13ba2a8b42666b34adf7e02412",
  "README.md": "fb9994c4d4859c9d8672ac90b5960edb58eef63a65a4b096068409dc964be63b",
  "registry-stack.yaml": "cb76d3a49093ab2567a68bfc6142cf5b1b2961cf62d6ca295c0ed50044301d98"
}
ignored_roots = {".registry-stack-editor", ".vscode", ".zed"}
transport_files = {"jsonplaceholder-todo-live-overlay-v1.sh", "jsonplaceholder-todo-live-overlay-v1.sh.sha256"}
root = Path.cwd()

for name in ignored_roots:
    path = root / name
    if path.exists() and (path.is_symlink() or not path.is_dir()):
        raise SystemExit(f"HTTP starter editor path is not a real directory: {name}")
for name in transport_files:
    path = root / name
    if path.exists() and (path.is_symlink() or not path.is_file()):
        raise SystemExit(f"overlay transport path is not a regular file: {name}")

actual = {}
for path in root.rglob("*"):
    relative = path.relative_to(root).as_posix()
    if relative.split("/", 1)[0] in ignored_roots or relative in transport_files:
        continue
    if path.is_symlink():
        raise SystemExit(f"HTTP starter closure contains a symbolic link: {relative}")
    if path.is_file():
        actual[relative] = hashlib.sha256(path.read_bytes()).hexdigest()
    elif not path.is_dir():
        raise SystemExit(f"HTTP starter closure contains a non-file entry: {relative}")

missing = sorted(set(expected) - set(actual))
unexpected = sorted(set(actual) - set(expected))
changed = sorted(path for path in expected.keys() & actual.keys() if expected[path] != actual[path])
if missing or unexpected or changed:
    details = []
    if missing:
        details.append("missing=" + ",".join(missing))
    if unexpected:
        details.append("unexpected=" + ",".join(unexpected))
    if changed:
        details.append("changed=" + ",".join(changed))
    raise SystemExit("HTTP starter closure does not match this release: " + "; ".join(details))
REGISTRYCTL_STARTER_VALIDATION_PY

rm -r integrations/person-record

mkdir -p 'environments'
cat >'environments/local.yaml' <<'REGISTRYCTL_ENVIRONMENTS_LOCAL_YAML_EOF'
version: 1

development:
  source_mode: synthetic
  default_integration: public-todo
  default_fixture: completed-todo

integrations:
  public-todo:
    source:
      origin: https://public-json-source.invalid

relay:
  origin: https://relay.internal.invalid
  issuer: https://workload-issuer.internal.invalid
  jwks_url: https://workload-issuer.internal.invalid/.well-known/jwks.json
  audience: registry-relay
  allowed_clients: [fictional-relay-client]
  consultation: { client_id: fictional-consultation-client, principal_id: fictional-consultation-principal }

deployment:
  profile: local
  relay: { service: fictional-registry-relay }
REGISTRYCTL_ENVIRONMENTS_LOCAL_YAML_EOF

mkdir -p 'environments'
cat >'environments/public-demo-missing.yaml' <<'REGISTRYCTL_ENVIRONMENTS_PUBLIC_DEMO_MISSING_YAML_EOF'
version: 1

development:
  source_mode: operator_bound
  default_integration: public-todo
  default_fixture: no-todo

integrations:
  public-todo:
    source:
      origin: https://jsonplaceholder.typicode.com

relay:
  origin: https://relay.internal.invalid
  issuer: https://workload-issuer.internal.invalid
  jwks_url: https://workload-issuer.internal.invalid/.well-known/jwks.json
  audience: registry-relay
  allowed_clients: [fictional-relay-client]
  consultation: { client_id: fictional-consultation-client, principal_id: fictional-consultation-principal }

deployment:
  profile: local
  relay: { service: fictional-registry-relay }
REGISTRYCTL_ENVIRONMENTS_PUBLIC_DEMO_MISSING_YAML_EOF

mkdir -p 'environments'
cat >'environments/public-demo.yaml' <<'REGISTRYCTL_ENVIRONMENTS_PUBLIC_DEMO_YAML_EOF'
version: 1

development:
  source_mode: operator_bound
  default_integration: public-todo
  default_fixture: completed-todo

integrations:
  public-todo:
    source:
      origin: https://jsonplaceholder.typicode.com

relay:
  origin: https://relay.internal.invalid
  issuer: https://workload-issuer.internal.invalid
  jwks_url: https://workload-issuer.internal.invalid/.well-known/jwks.json
  audience: registry-relay
  allowed_clients: [fictional-relay-client]
  consultation: { client_id: fictional-consultation-client, principal_id: fictional-consultation-principal }

deployment:
  profile: local
  relay: { service: fictional-registry-relay }
REGISTRYCTL_ENVIRONMENTS_PUBLIC_DEMO_YAML_EOF

mkdir -p 'integrations/public-todo/fixtures'
cat >'integrations/public-todo/fixtures/ambiguous.yaml' <<'REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_FIXTURES_AMBIGUOUS_YAML_EOF'
name: ambiguous-todo
classification: synthetic
input: { todo_id: "4" }
interactions:
  - expect:
      method: GET
      path: /todos/4
    respond: { status: 409, body: {} }
expect: { outcome: ambiguous }
REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_FIXTURES_AMBIGUOUS_YAML_EOF

mkdir -p 'integrations/public-todo/fixtures'
cat >'integrations/public-todo/fixtures/completed.yaml' <<'REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_FIXTURES_COMPLETED_YAML_EOF'
name: completed-todo
classification: synthetic
input: { todo_id: "4" }
interactions:
  - expect:
      method: GET
      path: /todos/4
    respond:
      status: 200
      body:
        userId: 1
        id: 4
        title: et porro tempora
        completed: true
expect:
  outcome: match
  outputs: { completed: true }
REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_FIXTURES_COMPLETED_YAML_EOF

mkdir -p 'integrations/public-todo/fixtures'
cat >'integrations/public-todo/fixtures/no-match.yaml' <<'REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_FIXTURES_NO_MATCH_YAML_EOF'
name: no-todo
classification: synthetic
input: { todo_id: "999999" }
interactions:
  - expect:
      method: GET
      path: /todos/999999
    respond: { status: 404, body: {} }
expect:
  outcome: no_match
  outputs: {}
REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_FIXTURES_NO_MATCH_YAML_EOF

mkdir -p 'integrations/public-todo'
cat >'integrations/public-todo/integration.yaml' <<'REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_INTEGRATION_YAML_EOF'
version: 1
id: public-todo
revision: 1

source:
  product: jsonplaceholder
  versions:
    unverified: [public-demo-api]
  auth: { type: none }

input:
  todo_id:
    role: selector
    type: string
    maxLength: 16

capability:
  http:
    request:
      method: GET
      path: /todos/{input.todo_id}
    response:
      no_match: [404]
      ambiguous: [409]

outputs:
  completed:
    type: boolean
    x-registry-source: /completed

not_applicable:
  subject_mismatch:
    rationale: The public demonstration response has no reviewed institutional identifier contract to compare with the requested todo identifier.
    request_fixture: completed-todo
REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_INTEGRATION_YAML_EOF

mkdir -p '.'
cat >'registry-stack.yaml' <<'REGISTRYCTL_REGISTRY_STACK_YAML_EOF'
version: 1

registry:
  id: public-json-live-demo

integrations:
  public-todo:
    file: integrations/public-todo/integration.yaml

services:
  todo-verification:
    kind: consultation_api
    version: 1
    purpose: public-source-connection-demonstration
    legal_basis: public-service-delivery
    consent: not_required
    consultations:
      todo:
        integration: public-todo
        input:
          todo_id: request.target.identifiers.public_todo_id
REGISTRYCTL_REGISTRY_STACK_YAML_EOF

printf '%s\n' 'Applied the optional no-credential public JSON source demonstration overlay.'
