#!/bin/sh
# Generated by docs/site/scripts/generate-registryctl-example-overlays.mjs.
# Apply only after creating an HTTP starter and removing integrations/person-record.
set -eu

if [ ! -f registry-stack.yaml ] || [ ! -d integrations ]; then
  printf '%s\n' 'run this overlay from a Registryctl HTTP starter project' >&2
  exit 1
fi
if [ -e integrations/person-record ]; then
  printf '%s\n' 'remove integrations/person-record before applying this overlay' >&2
  exit 1
fi

mkdir -p 'environments'
cat >'environments/local.yaml' <<'REGISTRYCTL_ENVIRONMENTS_LOCAL_YAML_EOF'
version: 1

development:
  source_mode: synthetic
  default_integration: public-todo
  default_fixture: completed-todo

integrations:
  public-todo:
    source:
      origin: https://public-json-source.invalid

issuance:
  issuer: did:web:notary.invalid
  signing_kid: project-issuer-key
  signing_key: { secret: REGISTRY_NOTARY_ISSUER_JWK }
  generation: 1

callers:
  evidence-client:
    api_key_fingerprint: { secret: EVIDENCE_CLIENT_TOKEN_HASH }
    scopes: ["evidence:todo:read"]

relay:
  origin: https://relay.internal.invalid
  issuer: https://workload-issuer.internal.invalid
  jwks_url: https://workload-issuer.internal.invalid/.well-known/jwks.json
  audience: registry-relay
  allowed_clients: [fictional-relay-client]

notary_relay:
  base_url: http://127.0.0.1:8080
  workload_client_id: fictional-registry-notary
  token_file: /run/secrets/relay-workload-token

deployment:
  profile: local
  relay: { service: fictional-registry-relay }
  notary: { service: fictional-registry-notary }
REGISTRYCTL_ENVIRONMENTS_LOCAL_YAML_EOF

mkdir -p 'environments'
cat >'environments/public-demo-missing.yaml' <<'REGISTRYCTL_ENVIRONMENTS_PUBLIC_DEMO_MISSING_YAML_EOF'
version: 1

development:
  source_mode: operator_bound
  default_integration: public-todo
  default_fixture: no-todo

integrations:
  public-todo:
    source:
      origin: https://jsonplaceholder.typicode.com

issuance:
  issuer: did:web:notary.invalid
  signing_kid: project-issuer-key
  signing_key: { secret: REGISTRY_NOTARY_ISSUER_JWK }
  generation: 1

callers:
  evidence-client:
    api_key_fingerprint: { secret: EVIDENCE_CLIENT_TOKEN_HASH }
    scopes: ["evidence:todo:read"]

relay:
  origin: https://relay.internal.invalid
  issuer: https://workload-issuer.internal.invalid
  jwks_url: https://workload-issuer.internal.invalid/.well-known/jwks.json
  audience: registry-relay
  allowed_clients: [fictional-relay-client]

notary_relay:
  base_url: http://127.0.0.1:8080
  workload_client_id: fictional-registry-notary
  token_file: /run/secrets/relay-workload-token

deployment:
  profile: local
  relay: { service: fictional-registry-relay }
  notary: { service: fictional-registry-notary }
REGISTRYCTL_ENVIRONMENTS_PUBLIC_DEMO_MISSING_YAML_EOF

mkdir -p 'environments'
cat >'environments/public-demo.yaml' <<'REGISTRYCTL_ENVIRONMENTS_PUBLIC_DEMO_YAML_EOF'
version: 1

development:
  source_mode: operator_bound
  default_integration: public-todo
  default_fixture: completed-todo

integrations:
  public-todo:
    source:
      origin: https://jsonplaceholder.typicode.com

issuance:
  issuer: did:web:notary.invalid
  signing_kid: project-issuer-key
  signing_key: { secret: REGISTRY_NOTARY_ISSUER_JWK }
  generation: 1

callers:
  evidence-client:
    api_key_fingerprint: { secret: EVIDENCE_CLIENT_TOKEN_HASH }
    scopes: ["evidence:todo:read"]

relay:
  origin: https://relay.internal.invalid
  issuer: https://workload-issuer.internal.invalid
  jwks_url: https://workload-issuer.internal.invalid/.well-known/jwks.json
  audience: registry-relay
  allowed_clients: [fictional-relay-client]

notary_relay:
  base_url: http://127.0.0.1:8080
  workload_client_id: fictional-registry-notary
  token_file: /run/secrets/relay-workload-token

deployment:
  profile: local
  relay: { service: fictional-registry-relay }
  notary: { service: fictional-registry-notary }
REGISTRYCTL_ENVIRONMENTS_PUBLIC_DEMO_YAML_EOF

mkdir -p 'integrations/public-todo/fixtures'
cat >'integrations/public-todo/fixtures/ambiguous.yaml' <<'REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_FIXTURES_AMBIGUOUS_YAML_EOF'
name: ambiguous-todo
classification: synthetic
input: { todo_id: "4" }
interactions:
  - expect:
      method: GET
      path: /todos/4
    respond: { status: 409, body: {} }
expect: { outcome: ambiguous }
REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_FIXTURES_AMBIGUOUS_YAML_EOF

mkdir -p 'integrations/public-todo/fixtures'
cat >'integrations/public-todo/fixtures/completed.yaml' <<'REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_FIXTURES_COMPLETED_YAML_EOF'
name: completed-todo
classification: synthetic
request:
  target:
    type: Person
    identifiers: [{ scheme: public_todo_id, value: "4" }]
  claims: [todo-record-exists]
  disclosure: predicate
  format: application/vnd.registry-notary.claim-result+json
  purpose: public-source-connection-demonstration
input: { todo_id: "4" }
interactions:
  - expect:
      method: GET
      path: /todos/4
    respond:
      status: 200
      body:
        userId: 1
        id: 4
        title: et porro tempora
        completed: true
expect:
  outcome: match
  outputs: { completed: true }
  claims: { todo-record-exists: true, todo-completed: true }
REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_FIXTURES_COMPLETED_YAML_EOF

mkdir -p 'integrations/public-todo/fixtures'
cat >'integrations/public-todo/fixtures/no-match.yaml' <<'REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_FIXTURES_NO_MATCH_YAML_EOF'
name: no-todo
classification: synthetic
request:
  target:
    type: Person
    identifiers: [{ scheme: public_todo_id, value: "999999" }]
  claims: [todo-record-exists]
  disclosure: predicate
  format: application/vnd.registry-notary.claim-result+json
  purpose: public-source-connection-demonstration
input: { todo_id: "999999" }
interactions:
  - expect:
      method: GET
      path: /todos/999999
    respond: { status: 404, body: {} }
expect:
  outcome: no_match
  outputs: {}
  claims: { todo-record-exists: false, todo-completed: null }
REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_FIXTURES_NO_MATCH_YAML_EOF

mkdir -p 'integrations/public-todo'
cat >'integrations/public-todo/integration.yaml' <<'REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_INTEGRATION_YAML_EOF'
version: 1
id: public-todo
revision: 1

source:
  product: jsonplaceholder
  versions:
    unverified: [public-demo-api]
  auth: { type: none }

input:
  todo_id:
    role: selector
    type: string
    maxLength: 16

capability:
  http:
    request:
      method: GET
      path: /todos/{input.todo_id}
    response:
      no_match: [404]
      ambiguous: [409]

outputs:
  completed:
    type: boolean
    x-registry-source: /completed

not_applicable:
  subject_mismatch:
    rationale: The public demonstration response has no reviewed institutional identifier contract to compare with the requested todo identifier.
    request_fixture: completed-todo
REGISTRYCTL_INTEGRATIONS_PUBLIC_TODO_INTEGRATION_YAML_EOF

mkdir -p '.'
cat >'registry-stack.yaml' <<'REGISTRYCTL_REGISTRY_STACK_YAML_EOF'
version: 1

registry:
  id: public-json-live-demo

integrations:
  public-todo:
    file: integrations/public-todo/integration.yaml

services:
  todo-verification:
    kind: evidence
    version: 1
    purpose: public-source-connection-demonstration
    legal_basis: public-service-delivery
    consent: not_required
    access:
      scopes: ["evidence:todo:read"]
    consultations:
      todo:
        integration: public-todo
        input:
          todo_id: request.target.identifiers.public_todo_id
    claims:
      todo-record-exists:
        cel: todo.matched
        disclosure: predicate
      todo-completed:
        output: todo.completed
        disclosure: value
    credential_profiles:
      todo-status:
        format: dc+sd-jwt
        type: https://credentials.invalid/public-todo-status/v1
        validity: 10m
        claims: [todo-record-exists, todo-completed]
REGISTRYCTL_REGISTRY_STACK_YAML_EOF

printf '%s\n' 'Applied the optional no-credential public JSON source demonstration overlay.'
