#!/bin/sh
# Generated by docs/site/scripts/generate-registryctl-example-overlays.mjs.
# Apply only to the pristine HTTP starter embedded in the matching Registryctl release.
set -eu

if ! command -v python3 >/dev/null 2>&1; then
  printf '%s\n' 'python3 is required to verify the HTTP starter closure' >&2
  exit 1
fi

python3 - <<'REGISTRYCTL_STARTER_VALIDATION_PY'
import hashlib
from pathlib import Path

expected = {
  ".gitignore": "84a80d00398b512ef755f17c1764c15b491058265d06d2cea71af37641324b83",
  "environments/local.yaml": "3af49441f405f725b25c9b1075c408fcd4b768b2b0bbd70a59b04c878ae8df45",
  "integrations/person-record/fixtures/active.yaml": "df873d90889c90ccc30132c5b911e555d1a9816ba409bc9cb37504a6466650b7",
  "integrations/person-record/fixtures/ambiguous.yaml": "6a375aa916a0b6b8dba04702b50cd7b1ec600063073c64881a9b62c31f16f232",
  "integrations/person-record/fixtures/no-match.yaml": "415ac27bc7e212e2a92b46e51c9e7282bddd9722aeaf4530557061f10d89b33e",
  "integrations/person-record/integration.yaml": "2b4950e1938e4d8345b7952480daa46e17abfd13ba2a8b42666b34adf7e02412",
  "README.md": "fb9994c4d4859c9d8672ac90b5960edb58eef63a65a4b096068409dc964be63b",
  "registry-stack.yaml": "73e73a00632488badd087c1a2c6830f961ba9533763a7127bed13984809a1386"
}
ignored_roots = {".registry-stack-editor", ".vscode", ".zed"}
transport_files = {"opencrvs-events-api-overlay-v1.sh", "opencrvs-events-api-overlay-v1.sh.sha256"}
root = Path.cwd()

for name in ignored_roots:
    path = root / name
    if path.exists() and (path.is_symlink() or not path.is_dir()):
        raise SystemExit(f"HTTP starter editor path is not a real directory: {name}")
for name in transport_files:
    path = root / name
    if path.exists() and (path.is_symlink() or not path.is_file()):
        raise SystemExit(f"overlay transport path is not a regular file: {name}")

actual = {}
for path in root.rglob("*"):
    relative = path.relative_to(root).as_posix()
    if relative.split("/", 1)[0] in ignored_roots or relative in transport_files:
        continue
    if path.is_symlink():
        raise SystemExit(f"HTTP starter closure contains a symbolic link: {relative}")
    if path.is_file():
        actual[relative] = hashlib.sha256(path.read_bytes()).hexdigest()
    elif not path.is_dir():
        raise SystemExit(f"HTTP starter closure contains a non-file entry: {relative}")

missing = sorted(set(expected) - set(actual))
unexpected = sorted(set(actual) - set(expected))
changed = sorted(path for path in expected.keys() & actual.keys() if expected[path] != actual[path])
if missing or unexpected or changed:
    details = []
    if missing:
        details.append("missing=" + ",".join(missing))
    if unexpected:
        details.append("unexpected=" + ",".join(unexpected))
    if changed:
        details.append("changed=" + ",".join(changed))
    raise SystemExit("HTTP starter closure does not match this release: " + "; ".join(details))
REGISTRYCTL_STARTER_VALIDATION_PY

rm -r integrations/person-record

mkdir -p 'environments'
cat >'environments/local.yaml' <<'REGISTRYCTL_ENVIRONMENTS_LOCAL_YAML_EOF'
version: 1

development:
  source_mode: synthetic
  default_integration: birth-event-search
  default_fixture: birth-event-match

integrations:
  birth-event-search:
    source:
      origin: https://events.opencrvs.invalid
      credential:
        client_id: { secret: OPENCRVS_EVENTS_CLIENT_ID }
        client_secret: { secret: OPENCRVS_EVENTS_CLIENT_SECRET }
        generation: 1
      oauth:
        origin: https://identity.opencrvs.invalid
        path: /oauth/token
        generation: 1

relay:
  origin: https://relay.opencrvs.invalid
  issuer: https://workload-issuer.opencrvs.invalid
  jwks_url: https://workload-issuer.opencrvs.invalid/.well-known/jwks.json
  audience: registry-relay
  allowed_clients: [synthetic-opencrvs-relay-client]
  consultation: { client_id: synthetic-opencrvs-consultation-client, principal_id: synthetic-opencrvs-consultation-principal }

deployment:
  profile: local
  relay: { service: synthetic-opencrvs-relay }
REGISTRYCTL_ENVIRONMENTS_LOCAL_YAML_EOF

mkdir -p 'integrations/birth-event-search'
cat >'integrations/birth-event-search/adapter.rhai' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_ADAPTER_RHAI_EOF'
fn consult(ctx) {
    let exact_tracking_id = #{
        type: "exact",
        term: ctx.input.tracking_id
    };
    let birth_event_clause = #{
        eventType: "birth",
        trackingId: exact_tracking_id
    };
    let response = source.post_json("/api/events/events/search", #{
        query: #{
            type: "and",
            clauses: [birth_event_clause]
        },
        limit: 2,
        offset: 0
    });
    if response.status != 200 {
        return result.fail(failure.source_rejected);
    }

    let events = response.body.results;
    if response.body.total == 0 && events.len == 0 {
        return result.no_match();
    }
    if response.body.total > 1 || events.len > 1 {
        return result.ambiguous();
    }
    if response.body.total != 1 || events.len != 1 {
        return result.fail(failure.source_rejected);
    }

    let event = events[0];
    if event.trackingId != ctx.input.tracking_id {
        return result.fail(failure.subject_mismatch);
    }
    if event.type != "birth" {
        return result.fail(failure.source_rejected);
    }

    result.match(#{
        event_type: event.type,
        registered: event.status == "REGISTERED"
    })
}
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_ADAPTER_RHAI_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/ambiguous.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_AMBIGUOUS_YAML_EOF'
name: birth-event-ambiguous
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: application/json }
      body: { access_token: SYNTHETIC_FIXTURE_TOKEN, token_type: Bearer }
  - expect:
      method: POST
      path: /api/events/events/search
      body:
        query:
          type: and
          clauses:
            - eventType: birth
              trackingId: { type: exact, term: TRK-SYNTH000001 }
        limit: 2
        offset: 0
    respond:
      status: 200
      body:
        total: 2
        results:
          - { id: 00000000-0000-4000-8000-000000000001, type: birth, status: REGISTERED, trackingId: TRK-SYNTH000001 }
          - { id: 00000000-0000-4000-8000-000000000002, type: birth, status: DECLARED, trackingId: TRK-SYNTH000001 }
expect:
  outcome: ambiguous
  outputs: {}
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_AMBIGUOUS_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/match.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_MATCH_YAML_EOF'
name: birth-event-match
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: application/json }
      body:
        access_token: SYNTHETIC_FIXTURE_TOKEN
        token_type: Bearer
  - expect:
      method: POST
      path: /api/events/events/search
      body:
        query:
          type: and
          clauses:
            - eventType: birth
              trackingId: { type: exact, term: TRK-SYNTH000001 }
        limit: 2
        offset: 0
    respond:
      status: 200
      body:
        total: 1
        results:
          - id: 00000000-0000-4000-8000-000000000001
            type: birth
            status: REGISTERED
            trackingId: TRK-SYNTH000001
            declaration:
              child:
                name: Synthetic Source-Only Name
            ignored_source_metadata: synthetic-source-only
expect:
  outcome: match
  outputs:
    event_type: birth
    registered: true
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_MATCH_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/no-match.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_NO_MATCH_YAML_EOF'
name: birth-event-no-match
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: application/json }
      body: { access_token: SYNTHETIC_FIXTURE_TOKEN, token_type: Bearer }
  - expect:
      method: POST
      path: /api/events/events/search
      body:
        query:
          type: and
          clauses:
            - eventType: birth
              trackingId: { type: exact, term: TRK-SYNTH000001 }
        limit: 2
        offset: 0
    respond:
      status: 200
      body: { total: 0, results: [] }
expect:
  outcome: no_match
  outputs: {}
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_NO_MATCH_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/oauth-expiry.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_OAUTH_EXPIRY_YAML_EOF'
name: oauth-token-expiry-rejected
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: application/json }
      body:
        access_token: SYNTHETIC_FIXTURE_TOKEN
        token_type: Bearer
        expires_in: 300
expect: { error: source.response_malformed, outputs: {} }
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_OAUTH_EXPIRY_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/oauth-extra-member.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_OAUTH_EXTRA_MEMBER_YAML_EOF'
name: oauth-token-extra-member-rejected
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: application/json }
      body:
        access_token: SYNTHETIC_FIXTURE_TOKEN
        token_type: Bearer
        unexpected: rejected
expect: { error: source.response_malformed, outputs: {} }
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_OAUTH_EXTRA_MEMBER_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/oauth-media-type.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_OAUTH_MEDIA_TYPE_YAML_EOF'
name: oauth-token-media-type-rejected
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: text/plain }
      body: { access_token: SYNTHETIC_FIXTURE_TOKEN, token_type: Bearer }
expect: { error: source.response_malformed, outputs: {} }
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_OAUTH_MEDIA_TYPE_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/oauth-redirect.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_OAUTH_REDIRECT_YAML_EOF'
name: oauth-token-redirect-rejected
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 302
      headers: { Location: https://redirect.opencrvs.invalid/oauth/token }
      body: {}
expect: { error: source.status_rejected, outputs: {} }
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_OAUTH_REDIRECT_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/oauth-token-type.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_OAUTH_TOKEN_TYPE_YAML_EOF'
name: oauth-token-type-rejected
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: application/json }
      body:
        access_token: SYNTHETIC_FIXTURE_TOKEN
        token_type: bearer
expect: { error: source.response_malformed, outputs: {} }
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_OAUTH_TOKEN_TYPE_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/source-malformed.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_SOURCE_MALFORMED_YAML_EOF'
name: birth-event-source-malformed
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: application/json }
      body: { access_token: SYNTHETIC_FIXTURE_TOKEN, token_type: Bearer }
  - expect:
      method: POST
      path: /api/events/events/search
      body:
        query:
          type: and
          clauses:
            - eventType: birth
              trackingId: { type: exact, term: TRK-SYNTH000001 }
        limit: 2
        offset: 0
    respond:
      status: 200
      body: { total: one, results: [] }
expect: { error: source.status_rejected, outputs: {} }
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_SOURCE_MALFORMED_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/source-rejected.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_SOURCE_REJECTED_YAML_EOF'
name: birth-event-source-rejected
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: application/json }
      body: { access_token: SYNTHETIC_FIXTURE_TOKEN, token_type: Bearer }
  - expect:
      method: POST
      path: /api/events/events/search
      body:
        query:
          type: and
          clauses:
            - eventType: birth
              trackingId: { type: exact, term: TRK-SYNTH000001 }
        limit: 2
        offset: 0
    respond: { status: 503, body: {} }
expect: { error: source.status_rejected, outputs: {} }
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_SOURCE_REJECTED_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/source-timeout.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_SOURCE_TIMEOUT_YAML_EOF'
name: birth-event-source-timeout
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: application/json }
      body: { access_token: SYNTHETIC_FIXTURE_TOKEN, token_type: Bearer }
  - expect:
      method: POST
      path: /api/events/events/search
      body:
        query:
          type: and
          clauses:
            - eventType: birth
              trackingId: { type: exact, term: TRK-SYNTH000001 }
        limit: 2
        offset: 0
    respond: { timeout: 10s }
expect: { error: source.deadline_exceeded, outputs: {} }
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_SOURCE_TIMEOUT_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/subject-mismatch.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_SUBJECT_MISMATCH_YAML_EOF'
name: birth-event-subject-mismatch
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: application/json }
      body: { access_token: SYNTHETIC_FIXTURE_TOKEN, token_type: Bearer }
  - expect:
      method: POST
      path: /api/events/events/search
      body:
        query:
          type: and
          clauses:
            - eventType: birth
              trackingId: { type: exact, term: TRK-SYNTH000001 }
        limit: 2
        offset: 0
    respond:
      status: 200
      body:
        total: 1
        results:
          - id: 00000000-0000-4000-8000-000000000002
            type: birth
            status: REGISTERED
            trackingId: TRK-SYNTH999999
expect: { error: failure.subject_mismatch, outputs: {} }
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_SUBJECT_MISMATCH_YAML_EOF

mkdir -p 'integrations/birth-event-search'
cat >'integrations/birth-event-search/integration.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_INTEGRATION_YAML_EOF'
version: 1
id: synthetic-opencrvs-events-search
revision: 1

source:
  product: opencrvs-events-api
  versions:
    unverified: [develop-synthetic-shape-2026-07-30]
  auth:
    type: oauth2_client_credentials
    request: json
    response_profile: oauth2_bearer_no_expiry
  allow:
    - method: POST
      path: /api/events/events/search
      semantics: read_only
  response:
    format: json
    max_bytes: 64KiB

input:
  tracking_id:
    role: selector
    type: string
    maxLength: 32
    pattern: "^TRK-SYNTH[0-9]{6}$"

capability:
  script:
    file: adapter.rhai

outputs:
  event_type:
    type: string
    maxLength: 32
  registered:
    type: boolean

limits:
  calls: 1
  source_bytes: 128KiB
  request_bytes: 16KiB
  deadline: 10s
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_INTEGRATION_YAML_EOF

mkdir -p '.'
cat >'registry-stack.yaml' <<'REGISTRYCTL_REGISTRY_STACK_YAML_EOF'
version: 1
registry:
  id: synthetic-opencrvs-events-api

integrations:
  birth-event-search:
    file: integrations/birth-event-search/integration.yaml

services:
  birth-event-verification:
    kind: consultation_api
    version: 1
    purpose: birth-event-registration-verification
    legal_basis: public-service-delivery
    consent: not_required
    consultations:
      event:
        integration: birth-event-search
        input:
          tracking_id: request.target.identifiers.opencrvs_tracking_id
REGISTRYCTL_REGISTRY_STACK_YAML_EOF

printf '%s\n' 'Applied the synthetic OpenCRVS Events API-shaped OAuth and Rhai overlay.'
