#!/bin/sh
# Generated by docs/site/scripts/generate-registryctl-example-overlays.mjs.
# Apply only after creating an HTTP starter and removing integrations/person-record.
set -eu

if [ ! -f registry-stack.yaml ] || [ ! -d integrations ]; then
  printf '%s\n' 'run this overlay from a Registryctl HTTP starter project' >&2
  exit 1
fi
if [ -e integrations/person-record ]; then
  printf '%s\n' 'remove integrations/person-record before applying this overlay' >&2
  exit 1
fi

mkdir -p 'environments'
cat >'environments/local.yaml' <<'REGISTRYCTL_ENVIRONMENTS_LOCAL_YAML_EOF'
version: 1

development:
  source_mode: synthetic
  default_integration: birth-event-search
  default_fixture: birth-event-match

integrations:
  birth-event-search:
    source:
      origin: https://events.opencrvs.invalid
      credential:
        client_id: { secret: OPENCRVS_EVENTS_CLIENT_ID }
        client_secret: { secret: OPENCRVS_EVENTS_CLIENT_SECRET }
        generation: 1
      oauth:
        origin: https://identity.opencrvs.invalid
        path: /oauth/token
        generation: 1

callers:
  synthetic-case-client:
    api_key_fingerprint: { secret: SYNTHETIC_CASE_CLIENT_TOKEN_HASH }
    scopes: ["evidence:birth-event:read"]

relay:
  origin: https://relay.opencrvs.invalid
  issuer: https://workload-issuer.opencrvs.invalid
  jwks_url: https://workload-issuer.opencrvs.invalid/.well-known/jwks.json
  audience: registry-relay
  allowed_clients: [synthetic-opencrvs-relay-client]

notary_relay:
  base_url: http://127.0.0.1:8080
  workload_client_id: synthetic-opencrvs-notary
  token_file: /run/secrets/relay-workload-token

deployment:
  profile: local
  relay: { service: synthetic-opencrvs-relay }
  notary: { service: synthetic-opencrvs-notary }
REGISTRYCTL_ENVIRONMENTS_LOCAL_YAML_EOF

mkdir -p 'integrations/birth-event-search'
cat >'integrations/birth-event-search/adapter.rhai' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_ADAPTER_RHAI_EOF'
fn consult(ctx) {
    let exact_tracking_id = #{
        type: "exact",
        term: ctx.input.tracking_id
    };
    let birth_event_clause = #{
        eventType: "birth",
        trackingId: exact_tracking_id
    };
    let response = source.post_json("/api/events/events/search", #{
        query: #{
            type: "and",
            clauses: [birth_event_clause]
        },
        limit: 2,
        offset: 0
    });
    if response.status != 200 {
        return result.fail(failure.source_rejected);
    }

    let events = response.body.results;
    if response.body.total == 0 && events.len == 0 {
        return result.no_match();
    }
    if response.body.total > 1 || events.len > 1 {
        return result.ambiguous();
    }
    if response.body.total != 1 || events.len != 1 {
        return result.fail(failure.source_rejected);
    }

    let event = events[0];
    if event.trackingId != ctx.input.tracking_id {
        return result.fail(failure.subject_mismatch);
    }
    if event.type != "birth" {
        return result.fail(failure.source_rejected);
    }

    result.match(#{
        event_type: event.type,
        registered: event.status == "REGISTERED"
    })
}
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_ADAPTER_RHAI_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/ambiguous.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_AMBIGUOUS_YAML_EOF'
name: birth-event-ambiguous
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: application/json }
      body: { access_token: SYNTHETIC_FIXTURE_TOKEN, token_type: Bearer }
  - expect:
      method: POST
      path: /api/events/events/search
      body:
        query:
          type: and
          clauses:
            - eventType: birth
              trackingId: { type: exact, term: TRK-SYNTH000001 }
        limit: 2
        offset: 0
    respond:
      status: 200
      body:
        total: 2
        results:
          - { id: 00000000-0000-4000-8000-000000000001, type: birth, status: REGISTERED, trackingId: TRK-SYNTH000001 }
          - { id: 00000000-0000-4000-8000-000000000002, type: birth, status: DECLARED, trackingId: TRK-SYNTH000001 }
expect:
  outcome: ambiguous
  outputs: {}
  claims: {}
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_AMBIGUOUS_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/match.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_MATCH_YAML_EOF'
name: birth-event-match
classification: synthetic
request:
  target:
    type: Person
    identifiers:
      - { scheme: opencrvs_tracking_id, value: TRK-SYNTH000001 }
  claims: [birth-event-found, birth-event-registered]
  disclosure: predicate
  format: application/vnd.registry-notary.claim-result+json
  purpose: birth-event-registration-verification
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: application/json }
      body:
        access_token: SYNTHETIC_FIXTURE_TOKEN
        token_type: Bearer
  - expect:
      method: POST
      path: /api/events/events/search
      body:
        query:
          type: and
          clauses:
            - eventType: birth
              trackingId: { type: exact, term: TRK-SYNTH000001 }
        limit: 2
        offset: 0
    respond:
      status: 200
      body:
        total: 1
        results:
          - id: 00000000-0000-4000-8000-000000000001
            type: birth
            status: REGISTERED
            trackingId: TRK-SYNTH000001
            declaration:
              child:
                name: Synthetic Source-Only Name
            ignored_source_metadata: synthetic-source-only
expect:
  outcome: match
  outputs:
    event_type: birth
    registered: true
  claims:
    birth-event-found: true
    birth-event-registered: true
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_MATCH_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/no-match.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_NO_MATCH_YAML_EOF'
name: birth-event-no-match
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: application/json }
      body: { access_token: SYNTHETIC_FIXTURE_TOKEN, token_type: Bearer }
  - expect:
      method: POST
      path: /api/events/events/search
      body:
        query:
          type: and
          clauses:
            - eventType: birth
              trackingId: { type: exact, term: TRK-SYNTH000001 }
        limit: 2
        offset: 0
    respond:
      status: 200
      body: { total: 0, results: [] }
expect:
  outcome: no_match
  outputs: {}
  claims:
    birth-event-found: false
    birth-event-registered: false
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_NO_MATCH_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/oauth-expiry.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_OAUTH_EXPIRY_YAML_EOF'
name: oauth-token-expiry-rejected
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: application/json }
      body:
        access_token: SYNTHETIC_FIXTURE_TOKEN
        token_type: Bearer
        expires_in: 300
expect: { error: source.response_malformed, outputs: {}, claims: {} }
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_OAUTH_EXPIRY_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/oauth-extra-member.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_OAUTH_EXTRA_MEMBER_YAML_EOF'
name: oauth-token-extra-member-rejected
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: application/json }
      body:
        access_token: SYNTHETIC_FIXTURE_TOKEN
        token_type: Bearer
        unexpected: rejected
expect: { error: source.response_malformed, outputs: {}, claims: {} }
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_OAUTH_EXTRA_MEMBER_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/oauth-media-type.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_OAUTH_MEDIA_TYPE_YAML_EOF'
name: oauth-token-media-type-rejected
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: text/plain }
      body: { access_token: SYNTHETIC_FIXTURE_TOKEN, token_type: Bearer }
expect: { error: source.response_malformed, outputs: {}, claims: {} }
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_OAUTH_MEDIA_TYPE_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/oauth-redirect.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_OAUTH_REDIRECT_YAML_EOF'
name: oauth-token-redirect-rejected
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 302
      headers: { Location: https://redirect.opencrvs.invalid/oauth/token }
      body: {}
expect: { error: source.status_rejected, outputs: {}, claims: {} }
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_OAUTH_REDIRECT_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/oauth-token-type.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_OAUTH_TOKEN_TYPE_YAML_EOF'
name: oauth-token-type-rejected
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: application/json }
      body:
        access_token: SYNTHETIC_FIXTURE_TOKEN
        token_type: bearer
expect: { error: source.response_malformed, outputs: {}, claims: {} }
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_OAUTH_TOKEN_TYPE_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/source-malformed.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_SOURCE_MALFORMED_YAML_EOF'
name: birth-event-source-malformed
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: application/json }
      body: { access_token: SYNTHETIC_FIXTURE_TOKEN, token_type: Bearer }
  - expect:
      method: POST
      path: /api/events/events/search
      body:
        query:
          type: and
          clauses:
            - eventType: birth
              trackingId: { type: exact, term: TRK-SYNTH000001 }
        limit: 2
        offset: 0
    respond:
      status: 200
      body: { total: one, results: [] }
expect: { error: source.status_rejected, outputs: {}, claims: {} }
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_SOURCE_MALFORMED_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/source-rejected.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_SOURCE_REJECTED_YAML_EOF'
name: birth-event-source-rejected
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: application/json }
      body: { access_token: SYNTHETIC_FIXTURE_TOKEN, token_type: Bearer }
  - expect:
      method: POST
      path: /api/events/events/search
      body:
        query:
          type: and
          clauses:
            - eventType: birth
              trackingId: { type: exact, term: TRK-SYNTH000001 }
        limit: 2
        offset: 0
    respond: { status: 503, body: {} }
expect: { error: source.status_rejected, outputs: {}, claims: {} }
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_SOURCE_REJECTED_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/source-timeout.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_SOURCE_TIMEOUT_YAML_EOF'
name: birth-event-source-timeout
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: application/json }
      body: { access_token: SYNTHETIC_FIXTURE_TOKEN, token_type: Bearer }
  - expect:
      method: POST
      path: /api/events/events/search
      body:
        query:
          type: and
          clauses:
            - eventType: birth
              trackingId: { type: exact, term: TRK-SYNTH000001 }
        limit: 2
        offset: 0
    respond: { timeout: 10s }
expect: { error: source.deadline_exceeded, outputs: {}, claims: {} }
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_SOURCE_TIMEOUT_YAML_EOF

mkdir -p 'integrations/birth-event-search/fixtures'
cat >'integrations/birth-event-search/fixtures/subject-mismatch.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_SUBJECT_MISMATCH_YAML_EOF'
name: birth-event-subject-mismatch
classification: synthetic
input: { tracking_id: TRK-SYNTH000001 }
interactions:
  - expect:
      method: POST
      path: /oauth/token
      headers: { Accept: application/json, Content-Type: application/json }
      body: { grant_type: client_credentials }
    respond:
      status: 200
      headers: { Content-Type: application/json }
      body: { access_token: SYNTHETIC_FIXTURE_TOKEN, token_type: Bearer }
  - expect:
      method: POST
      path: /api/events/events/search
      body:
        query:
          type: and
          clauses:
            - eventType: birth
              trackingId: { type: exact, term: TRK-SYNTH000001 }
        limit: 2
        offset: 0
    respond:
      status: 200
      body:
        total: 1
        results:
          - id: 00000000-0000-4000-8000-000000000002
            type: birth
            status: REGISTERED
            trackingId: TRK-SYNTH999999
expect: { error: failure.subject_mismatch, outputs: {}, claims: {} }
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_FIXTURES_SUBJECT_MISMATCH_YAML_EOF

mkdir -p 'integrations/birth-event-search'
cat >'integrations/birth-event-search/integration.yaml' <<'REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_INTEGRATION_YAML_EOF'
version: 1
id: synthetic-opencrvs-events-search
revision: 1

source:
  product: opencrvs-events-api
  versions:
    unverified: [develop-synthetic-shape-2026-07-30]
  auth:
    type: oauth2_client_credentials
    request: json
    response_profile: oauth2_bearer_no_expiry
  allow:
    - method: POST
      path: /api/events/events/search
      semantics: read_only
  response:
    format: json
    max_bytes: 64KiB

input:
  tracking_id:
    role: selector
    type: string
    maxLength: 32
    pattern: "^TRK-SYNTH[0-9]{6}$"

capability:
  script:
    file: adapter.rhai

outputs:
  event_type:
    type: string
    maxLength: 32
  registered:
    type: boolean

limits:
  calls: 1
  source_bytes: 128KiB
  request_bytes: 16KiB
  deadline: 10s
REGISTRYCTL_INTEGRATIONS_BIRTH_EVENT_SEARCH_INTEGRATION_YAML_EOF

mkdir -p '.'
cat >'registry-stack.yaml' <<'REGISTRYCTL_REGISTRY_STACK_YAML_EOF'
version: 1
registry:
  id: synthetic-opencrvs-events-api

integrations:
  birth-event-search:
    file: integrations/birth-event-search/integration.yaml

services:
  birth-event-verification:
    kind: evidence
    version: 1
    purpose: birth-event-registration-verification
    legal_basis: public-service-delivery
    consent: not_required
    access:
      scopes: ["evidence:birth-event:read"]
    consultations:
      event:
        integration: birth-event-search
        input:
          tracking_id: request.target.identifiers.opencrvs_tracking_id
    claims:
      birth-event-found:
        cel: event.matched
        disclosure: predicate
      birth-event-registered:
        cel: >-
          event.matched
            && event.event_type == "birth"
            && event.registered
        disclosure: predicate
REGISTRYCTL_REGISTRY_STACK_YAML_EOF

printf '%s\n' 'Applied the synthetic OpenCRVS Events API-shaped OAuth and Rhai overlay.'
