/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class SchedulingClient {
  constructor(config: any)
  getScheduling(token: string): Promise<SchedulingOutcome>
  listServices(token: string, cursor?: string | undefined | null): Promise<SchedulingOutcome>
  listOfferings(token: string, cursor?: string | undefined | null): Promise<SchedulingOutcome>
  availability(token: string, offering: string, query?: any | undefined | null): Promise<SchedulingOutcome>
  explain(token: string, offering: string, start: string): Promise<SchedulingOutcome>
  createHold(token: string, idempotencyKey: string, request: any): Promise<SchedulingOutcome>
  releaseHold(token: string, holdId: string): Promise<SchedulingOutcome>
  createAppointment(token: string, idempotencyKey: string, request: any): Promise<SchedulingOutcome>
  getAppointment(token: string, appointmentId: string): Promise<SchedulingOutcome>
  listAppointments(token: string, reference: any, page?: any | undefined | null): Promise<SchedulingOutcome>
  rescheduleAppointment(token: string, appointmentId: string, idempotencyKey: string, request: any): Promise<SchedulingOutcome>
  cancelAppointment(token: string, appointmentId: string, idempotencyKey: string, request: any): Promise<SchedulingOutcome>
  appointmentHistory(token: string, appointmentId: string, cursor?: string | undefined | null): Promise<SchedulingOutcome>
  listResources(token: string, cursor?: string | undefined | null): Promise<SchedulingOutcome>
  listLocations(token: string, cursor?: string | undefined | null): Promise<SchedulingOutcome>
}

export interface SchedulingOutcome {
  kind: string
  value: any
  traceId: string
}
