/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class MessagingClient {
  constructor(config: any)
  health(): Promise<MessagingOutcome>
  ready(): Promise<MessagingOutcome>
  submit(token: string, idempotencyKey: string, request: any): Promise<MessagingOutcome>
  messageReceipt(token: string, idempotencyKey: string, request: any): Promise<MessagingOutcome>
  message(token: string, messageId: string): Promise<MessagingOutcome>
  cancel(token: string, messageId: string): Promise<MessagingOutcome>
  preview(token: string, templateId: string, version: string, request: any): Promise<MessagingOutcome>
}

export interface MessagingOutcome {
  kind: string
  value: any
  traceId: string
}
