#!/bin/sh
set -eu

repo_root=$(git rev-parse --show-toplevel)

export CARGO_INCREMENTAL=0
export CARGO_PROFILE_DEV_DEBUG=0
export CARGO_PROFILE_TEST_DEBUG=0
export SCCACHE_BASEDIRS="${SCCACHE_BASEDIRS:-$repo_root}"

exec cargo "$@"
