// SPDX-License-Identifier: Apache-2.0

//! Gate for the `bregctl explain` wire contract described in
//! `products/breg/contracts/explain/README.md`.
//!
//! For every tracked fixture and every `explain` subject, this runs the real
//! `bregctl` binary, then validates the `explanation` object it prints
//! against the matching JSON Schema contract file. A drift between
//! `explain_*` in `lib.rs` and the schemas under
//! `products/breg/contracts/explain/` fails here before it reaches an
//! adopter.

use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use jsonschema::{Draft, JSONSchema};
use serde_json::{json, Value};

/// The header an explanation opens with, by the name of its schema file: each
/// of the nine formats carries its own `apiVersion` and a `kind` that names
/// the product.
fn envelope(contract: &str) -> (&'static str, &'static str) {
    match contract {
        "ModelExplanation" => (
            "id.registrystack.org/formats/breg/model-explanation/v1alpha4",
            "BRegModelExplanation",
        ),
        "AccessExplanation" => (
            "id.registrystack.org/formats/breg/access-explanation/v1alpha4",
            "BRegAccessExplanation",
        ),
        "AccessPreview" => (
            "id.registrystack.org/formats/breg/access-preview/v1alpha4",
            "BRegAccessPreview",
        ),
        "RoutesExplanation" => (
            "id.registrystack.org/formats/breg/routes-explanation/v1alpha4",
            "BRegRoutesExplanation",
        ),
        "QueriesExplanation" => (
            "id.registrystack.org/formats/breg/queries-explanation/v1alpha4",
            "BRegQueriesExplanation",
        ),
        "ActionsExplanation" => (
            "id.registrystack.org/formats/breg/actions-explanation/v1alpha4",
            "BRegActionsExplanation",
        ),
        "ChangeRequestsExplanation" => (
            "id.registrystack.org/formats/breg/change-requests-explanation/v1alpha4",
            "BRegChangeRequestsExplanation",
        ),
        "EventsExplanation" => (
            "id.registrystack.org/formats/breg/events-explanation/v1alpha4",
            "BRegEventsExplanation",
        ),
        "LifecycleExplanation" => (
            "id.registrystack.org/formats/breg/lifecycle-explanation/v1alpha4",
            "BRegLifecycleExplanation",
        ),
        other => panic!("no explain contract is named {other}"),
    }
}

/// Fixture directories the gate replays, each an on-disk registry project
/// under `products/breg/`. Chosen to cover every subject's optional
/// branches: `farmer-landholding-evidence` is the only fixture with an
/// `action-handler/v2` handler (exercises `actions[].evidence`), and
/// `spatial-service-sites` is the only fixture with spatial queries
/// (exercises `spatialQueries` and `gis`). The two consent fixtures carry
/// a module generated by `bregctl module add consent` (exercises the consent
/// branches of `access` and `actions`).
const FIXTURES: &[(&str, &str)] = &[
    (
        "asset-site-placement",
        "products/breg/acceptance/asset-site-placement",
    ),
    (
        "business-establishments",
        "products/breg/acceptance/business-establishments",
    ),
    (
        "asset-site-placement-change-requests",
        "products/breg/acceptance/asset-site-placement-change-requests",
    ),
    (
        "publicschema-household-change-requests",
        "products/breg/acceptance/publicschema-household-change-requests",
    ),
    (
        "person-name-change-rhai",
        "products/breg/acceptance/person-name-change-rhai",
    ),
    (
        "person-registration-rhai",
        "products/breg/acceptance/person-registration-rhai",
    ),
    (
        "request-attachments",
        "products/breg/acceptance/request-attachments",
    ),
    (
        "asset-registration-actions",
        "products/breg/fixtures/asset-registration-actions",
    ),
    (
        "household-contact-actions",
        "products/breg/fixtures/household-contact-actions",
    ),
    (
        "farmer-landholding-evidence",
        "products/breg/acceptance/farmer-landholding-evidence",
    ),
    (
        "spatial-service-sites",
        "products/breg/acceptance/spatial-service-sites",
    ),
    (
        "consent-person-registry",
        "products/breg/fixtures/consent-person-registry",
    ),
    (
        "consent-land-registry",
        "products/breg/fixtures/consent-land-registry",
    ),
];

/// Access-review scenario files, replayed through `explain access --scenario`.
const ACCESS_SCENARIOS: &[(&str, &str)] = &[
    (
        "allowed",
        "products/breg/examples/access-review/allowed.json",
    ),
    (
        "missing-scope",
        "products/breg/examples/access-review/missing-scope.json",
    ),
];

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repository root resolves")
}

fn bregctl(arguments: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_bregctl"))
        .args(arguments)
        .output()
        .expect("bregctl starts")
}

fn json_stdout(output: &Output) -> Value {
    serde_json::from_slice(&output.stdout).expect("command stdout is JSON")
}

fn explain(subject: &str, project: &Path) -> Value {
    let output = bregctl(&[
        "--format",
        "json",
        "explain",
        subject,
        project.to_str().expect("fixture path is UTF-8"),
    ]);
    assert!(
        output.status.success(),
        "bregctl explain {subject} {project:?} failed: {output:?}"
    );
    let report = json_stdout(&output);
    assert_eq!(
        report["ok"],
        Value::Bool(true),
        "bregctl explain {subject} {project:?} reported ok=false: {report:#?}"
    );
    report["explanation"].clone()
}

fn explain_with_scenario(project: &Path, scenario: &Path) -> Value {
    let output = bregctl(&[
        "--format",
        "json",
        "explain",
        "access",
        project.to_str().expect("fixture path is UTF-8"),
        "--scenario",
        scenario.to_str().expect("scenario path is UTF-8"),
    ]);
    assert!(
        output.status.success(),
        "bregctl explain access {project:?} --scenario {scenario:?} failed: {output:?}"
    );
    let report = json_stdout(&output);
    assert_eq!(
        report["ok"],
        Value::Bool(true),
        "bregctl explain access {project:?} --scenario {scenario:?} reported ok=false: {report:#?}"
    );
    report["explanation"].clone()
}

fn load_schema(kind: &str) -> JSONSchema {
    let schema = load_schema_document(kind);
    JSONSchema::options()
        .with_draft(Draft::Draft202012)
        .compile(&schema)
        .unwrap_or_else(|error| panic!("schema {kind} compiles: {error}"))
}

fn load_schema_document(kind: &str) -> Value {
    let path = repo_root()
        .join("products/breg/contracts/explain")
        .join(format!("{kind}.schema.json"));
    let bytes =
        std::fs::read(&path).unwrap_or_else(|error| panic!("schema {path:?} reads: {error}"));
    serde_json::from_slice(&bytes).unwrap_or_else(|error| panic!("schema {path:?} parses: {error}"))
}

/// Asserts `explanation` carries the envelope for `kind`, then validates it
/// in full against that kind's schema file. On a schema violation, every
/// validation error is printed with its `instance_path` before panicking, so
/// a single failing fixture shows the complete list of what is wrong rather
/// than only the first mismatch.
fn assert_matches_contract(label: &str, kind: &str, explanation: &Value) {
    let (api_version, envelope_kind) = envelope(kind);
    assert_eq!(
        explanation["apiVersion"],
        Value::String(api_version.to_owned()),
        "{label}: unexpected apiVersion in {explanation:#?}"
    );
    assert_eq!(
        explanation["kind"],
        Value::String(envelope_kind.to_owned()),
        "{label}: unexpected kind in {explanation:#?}"
    );

    let schema = load_schema(kind);
    let result = schema.validate(explanation);
    if let Err(errors) = result {
        let mut report = format!("{label}: {kind} does not satisfy its schema contract:\n");
        for error in errors {
            report.push_str(&format!("  - {}: {error}\n", error.instance_path));
        }
        panic!("{report}");
    }
}

fn fixture_path(relative: &str) -> PathBuf {
    let path = repo_root().join(relative);
    assert!(path.is_dir(), "fixture directory {path:?} exists");
    path
}

#[test]
fn explain_model_matches_contract() {
    for (name, relative) in FIXTURES {
        let explanation = explain("model", &fixture_path(relative));
        assert_matches_contract(name, "ModelExplanation", &explanation);
    }
}

#[test]
fn explain_access_matches_contract() {
    for (name, relative) in FIXTURES {
        let explanation = explain("access", &fixture_path(relative));
        assert_matches_contract(name, "AccessExplanation", &explanation);
    }
}

#[test]
fn explain_access_scenario_matches_contract() {
    let project = fixture_path("products/breg/examples/access-review");
    for (name, relative) in ACCESS_SCENARIOS {
        let scenario = repo_root().join(relative);
        assert!(scenario.is_file(), "scenario file {scenario:?} exists");
        let explanation = explain_with_scenario(&project, &scenario);
        assert_matches_contract(name, "AccessPreview", &explanation);
    }
}

/// A project directory holding the consent-enforcement fixture, removed on
/// drop. No tracked product fixture declares consent yet.
struct ConsentProject(PathBuf);

impl ConsentProject {
    fn new(label: &str) -> Self {
        let root = std::env::temp_dir()
            .canonicalize()
            .expect("temporary directory resolves")
            .join(format!(
                "bregctl-explain-consent-{label}-{}",
                std::process::id()
            ));
        std::fs::create_dir_all(&root).expect("temporary project directory is created");
        std::fs::copy(
            repo_root().join("crates/registry-breg/tests/fixtures/consent-access.yaml"),
            root.join("registry.yaml"),
        )
        .expect("consent fixture is copied");
        Self(root)
    }
}

impl Drop for ConsentProject {
    fn drop(&mut self) {
        std::fs::remove_dir_all(&self.0).expect("temporary project directory is removed");
    }
}

#[test]
fn explain_access_consent_matches_contract() {
    let project = ConsentProject::new("access");
    let explanation = explain("access", &project.0);
    assert_matches_contract("consent-access", "AccessExplanation", &explanation);
    let consent = &explanation["consent"];
    assert_eq!(consent["permissions"].as_array().unwrap().len(), 2);
    assert_eq!(consent["issuers"][0]["issuer"], "steward");

    let scenario = project.0.join("scenario.json");
    std::fs::write(
        &scenario,
        serde_json::to_vec(&json!({
            "entity": "person",
            "accessProfile": "food-targeting",
            "operation": "get",
            "claims": {
                "principalClaim": "principal",
                "principal": "synthetic-caseworker",
                "scopes": ["records:read"],
                "purpose": "food-assistance",
                "actorKind": "service",
                "requesterClient": "wfp-scope"
            }
        }))
        .unwrap(),
    )
    .unwrap();
    let preview = explain_with_scenario(&project.0, &scenario);
    assert_matches_contract("consent-access", "AccessPreview", &preview);
    assert_eq!(preview["admitted"], true);
    assert_eq!(preview["recipients"], json!(["referral-network", "wfp"]));
}

#[test]
fn explain_access_states_who_holds_each_statistical_dataset_operation() {
    let project = repo_root().join("products/breg/acceptance/facility");
    let explanation = explain("access", &project);
    assert_matches_contract("facility", "AccessExplanation", &explanation);
    let audience = |dataset: &str| {
        json!({
            "dataset": dataset,
            "readLive": ["facility-operator"],
            "publish": ["statistics-publisher"],
            "readReleases": ["facility-operator", "statistics-publisher", "statistics-reader"],
        })
    };
    assert_eq!(
        explanation["statisticalDatasets"],
        json!([
            audience("monthly-discharge-reports"),
            audience("monthly-valid-permits-fields"),
            audience("monthly-valid-permits-temporal"),
        ])
    );
}

#[test]
fn explain_routes_matches_contract() {
    for (name, relative) in FIXTURES {
        let explanation = explain("routes", &fixture_path(relative));
        assert_matches_contract(name, "RoutesExplanation", &explanation);
    }
}

#[test]
fn explain_queries_matches_contract() {
    for (name, relative) in FIXTURES {
        let explanation = explain("queries", &fixture_path(relative));
        assert_matches_contract(name, "QueriesExplanation", &explanation);
    }
}

#[test]
fn explain_actions_matches_contract() {
    for (name, relative) in FIXTURES {
        let explanation = explain("actions", &fixture_path(relative));
        assert_matches_contract(name, "ActionsExplanation", &explanation);
    }
}

#[test]
fn facility_action_permission_targets_keep_each_operation_and_source() {
    let explanation = explain(
        "actions",
        &fixture_path("products/breg/fixtures/facility-registry-actions"),
    );
    let action = explanation["actions"]
        .as_array()
        .expect("actions are listed")
        .iter()
        .find(|action| action["id"] == "register-facility")
        .expect("register-facility is explained");
    let permission = action["permissions"]
        .as_array()
        .expect("permissions are listed")
        .iter()
        .find(|permission| permission["profile"] == "facility-registrar")
        .expect("facility registrar permission is explained");
    let roles = permission["targets"]
        .as_array()
        .expect("permission targets are listed")
        .iter()
        .map(|target| {
            let source = &target["source"];
            json!({
                "entity": target["entity"],
                "operation": target["operation"],
                "sourceType": source["type"],
                "sourceId": source.get("effect").unwrap_or(&source["input"]["input"]),
            })
        })
        .collect::<Vec<_>>();
    assert_eq!(
        roles,
        vec![
            json!({"entity": "facility", "operation": "create", "sourceType": "effect", "sourceId": "facility"}),
            json!({"entity": "initial-operator-assignment", "operation": "create", "sourceType": "effect", "sourceId": "initial-assignment"}),
            json!({"entity": "operator", "operation": "invoke", "sourceType": "input", "sourceId": "operator"}),
        ]
    );
}

#[test]
fn explain_change_requests_matches_contract() {
    for (name, relative) in FIXTURES {
        let explanation = explain("change-requests", &fixture_path(relative));
        assert_matches_contract(name, "ChangeRequestsExplanation", &explanation);
    }
}

#[test]
fn explain_events_matches_contract() {
    for (name, relative) in FIXTURES {
        let explanation = explain("events", &fixture_path(relative));
        assert_matches_contract(name, "EventsExplanation", &explanation);
    }
}

/// `explain lifecycle` is the one subject that takes no PROJECT, so it needs
/// its own runner rather than the fixture loop above. It returns the whole
/// report, not just `explanation`, because the absent `revision` is part of
/// what this contract states.
fn explain_lifecycle_report() -> Value {
    let output = bregctl(&["--format", "json", "explain", "lifecycle"]);
    assert!(
        output.status.success(),
        "bregctl explain lifecycle failed: {output:?}"
    );
    let report = json_stdout(&output);
    assert_eq!(
        report["ok"],
        Value::Bool(true),
        "bregctl explain lifecycle reported ok=false: {report:#?}"
    );
    report
}

#[test]
fn explain_lifecycle_matches_contract() {
    let report = explain_lifecycle_report();
    assert_matches_contract("lifecycle", "LifecycleExplanation", &report["explanation"]);
}

/// The request machine does not vary by project, so its identifiers are wire
/// contract and the schema pins them. Without that, renaming a state or an
/// event and updating the Rust unit tests in the same change would leave this
/// contract test green, which is exactly the drift "pinned in full" denies.
///
/// The machine's own id is pinned the same way and for a sharper reason: a
/// constraint conditional on `id == "request"` would stop applying the moment
/// the machine were renamed, so the one rename it most needs to reject would
/// fall through to the generic shape and validate.
#[test]
fn renaming_a_lifecycle_state_or_event_fails_the_contract() {
    let report = explain_lifecycle_report();
    let schema = load_schema("LifecycleExplanation");

    let renamed_machine = {
        let mut explanation = report["explanation"].clone();
        explanation["lifecycles"][0]["id"] = Value::String("change_request".to_owned());
        explanation
    };
    assert!(
        schema.validate(&renamed_machine).is_err(),
        "renaming the machine itself must fail the schema: {renamed_machine:#?}"
    );

    let second_machine = {
        let mut explanation = report["explanation"].clone();
        let lifecycles = explanation["lifecycles"]
            .as_array_mut()
            .expect("lifecycles array");
        let duplicate = lifecycles[0].clone();
        lifecycles.push(duplicate);
        explanation
    };
    assert!(
        schema.validate(&second_machine).is_err(),
        "bregctl reports one machine, so a second must fail the schema: {second_machine:#?}"
    );

    let renamed_state: Value = serde_json::from_str(
        &report["explanation"]
            .to_string()
            .replace("\"submitted\"", "\"in_review\""),
    )
    .expect("renamed explanation is JSON");
    assert!(
        schema.validate(&renamed_state).is_err(),
        "renaming the submitted state must fail the schema: {renamed_state:#?}"
    );

    let renamed_event: Value = serde_json::from_str(
        &report["explanation"]
            .to_string()
            .replace("\"event\":\"apply\"", "\"event\":\"commit\""),
    )
    .expect("renamed explanation is JSON");
    assert!(
        schema.validate(&renamed_event).is_err(),
        "renaming the apply event must fail the schema: {renamed_event:#?}"
    );

    let extra_edge = {
        let mut explanation = report["explanation"].clone();
        let transitions = explanation["lifecycles"][0]["transitions"]
            .as_array_mut()
            .expect("transitions array");
        let duplicate = transitions[0].clone();
        transitions.push(duplicate);
        explanation
    };
    assert!(
        schema.validate(&extra_edge).is_err(),
        "a seventh edge must fail the schema: {extra_edge:#?}"
    );
}

/// `initial`, `terminal`, `unreachable`, and the two transition counts are
/// derived from the edge list rather than written down, so pinning the states
/// by id alone would leave the derivation itself unpinned: a report calling
/// `draft` terminal or `cancelled` unreachable would still validate, and the
/// contract would say nothing about the one part of the state list a code
/// change can silently get wrong. Each derived fact is pinned to the value the
/// derivation must produce, and this test is what proves the pin bites.
#[test]
fn flipping_a_derived_lifecycle_fact_fails_the_contract() {
    let report = explain_lifecycle_report();
    let schema = load_schema("LifecycleExplanation");
    let ids: Vec<&str> = report["explanation"]["lifecycles"][0]["states"]
        .as_array()
        .expect("states array")
        .iter()
        .map(|state| state["id"].as_str().expect("state id"))
        .collect();
    assert_eq!(ids, ["draft", "submitted", "cancelled", "applied"]);
    let state = |id: &str, field: &str, value: Value| {
        let mut explanation = report["explanation"].clone();
        let states = explanation["lifecycles"][0]["states"]
            .as_array_mut()
            .expect("states array");
        let entry = states
            .iter_mut()
            .find(|state| state["id"] == id)
            .unwrap_or_else(|| panic!("{id} is reported"));
        assert_ne!(entry[field], value, "{id}.{field} already reports the edit");
        entry[field] = value;
        explanation
    };

    for (id, field, value) in [
        ("draft", "terminal", Value::Bool(true)),
        ("draft", "initial", Value::Bool(false)),
        ("applied", "terminal", Value::Bool(false)),
        ("cancelled", "terminal", Value::Bool(false)),
        ("cancelled", "unreachable", Value::Bool(true)),
        ("submitted", "outgoingTransitions", Value::from(3)),
        ("submitted", "incomingTransitions", Value::from(2)),
        ("applied", "incomingTransitions", Value::from(0)),
    ] {
        let edited = state(id, field, value.clone());
        assert!(
            schema.validate(&edited).is_err(),
            "{id}.{field} reported as {value} must fail the schema: {edited:#?}"
        );
    }
}

/// The table is pinned by position, not only by vocabulary. A schema that
/// constrained each entry to an enum of the known ids would still admit a
/// table with the states reordered, `revise` and `rebase` swapped, or an
/// edge replaced by a duplicate of another, and every one of those is a
/// different machine reported under the same names. The enforcement layers
/// are pinned the same way because their order is what the report says
/// about the runtime: a layer moved is a different claim about when the
/// engine refuses.
#[test]
fn reordering_or_thinning_the_lifecycle_fails_the_contract() {
    let report = explain_lifecycle_report();
    let schema = load_schema("LifecycleExplanation");
    let lifecycle = |edit: &dyn Fn(&mut Value)| {
        let mut explanation = report["explanation"].clone();
        edit(&mut explanation["lifecycles"][0]);
        explanation
    };

    let swapped_states = lifecycle(&|machine| {
        machine["states"].as_array_mut().expect("states").swap(0, 1);
    });
    assert!(
        schema.validate(&swapped_states).is_err(),
        "reordering the states must fail the schema: {swapped_states:#?}"
    );

    let swapped_edges = lifecycle(&|machine| {
        let edges = machine["transitions"].as_array_mut().expect("transitions");
        assert_eq!(edges[1]["event"], Value::String("revise".to_owned()));
        assert_eq!(edges[2]["event"], Value::String("rebase".to_owned()));
        edges.swap(1, 2);
    });
    assert!(
        schema.validate(&swapped_edges).is_err(),
        "swapping the revise and rebase edges must fail the schema: {swapped_edges:#?}"
    );

    let duplicated_edge = lifecycle(&|machine| {
        let edges = machine["transitions"].as_array_mut().expect("transitions");
        edges[5] = edges[4].clone();
    });
    assert!(
        schema.validate(&duplicated_edge).is_err(),
        "replacing the apply edge with a second cancel edge must fail the schema: {duplicated_edge:#?}"
    );

    let no_enforcement = lifecycle(&|machine| {
        machine
            .as_object_mut()
            .expect("machine object")
            .remove("enforcement");
    });
    assert!(
        schema.validate(&no_enforcement).is_err(),
        "a machine without its enforcement layers must fail the schema: {no_enforcement:#?}"
    );

    let dropped_layer = lifecycle(&|machine| {
        machine["enforcement"]
            .as_array_mut()
            .expect("enforcement")
            .pop();
    });
    assert!(
        schema.validate(&dropped_layer).is_err(),
        "dropping the persist layer must fail the schema: {dropped_layer:#?}"
    );

    let swapped_layers = lifecycle(&|machine| {
        machine["enforcement"]
            .as_array_mut()
            .expect("enforcement")
            .swap(0, 1);
    });
    assert!(
        schema.validate(&swapped_layers).is_err(),
        "reordering the enforcement layers must fail the schema: {swapped_layers:#?}"
    );

    let layer_without_events = lifecycle(&|machine| {
        machine["enforcement"][0]["events"] = Value::Array(Vec::new());
    });
    assert!(
        schema.validate(&layer_without_events).is_err(),
        "a layer that applies to no event must fail the schema: {layer_without_events:#?}"
    );

    let layer_with_unknown_event = lifecycle(&|machine| {
        machine["enforcement"][0]["events"] = Value::Array(vec![Value::String("merge".to_owned())]);
    });
    assert!(
        schema.validate(&layer_with_unknown_event).is_err(),
        "a layer naming an event the machine does not raise must fail the schema: {layer_with_unknown_event:#?}"
    );

    // Which events a layer covers is the layer's whole claim, so a legal event
    // name in the wrong layer has to fail as loudly as an unknown one. The
    // apply preflight runs for apply alone; saying it runs for submit is a
    // different machine reported under the same layer names.
    let layer_with_wrong_event = lifecycle(&|machine| {
        machine["enforcement"][1]["events"] =
            Value::Array(vec![Value::String("submit".to_owned())]);
    });
    assert!(
        schema.validate(&layer_with_wrong_event).is_err(),
        "an apply-only layer claiming submit must fail the schema: {layer_with_wrong_event:#?}"
    );

    let layer_with_widened_events = lifecycle(&|machine| {
        machine["enforcement"][4]["events"] = Value::Array(vec![
            Value::String("submit".to_owned()),
            Value::String("revise".to_owned()),
            Value::String("rebase".to_owned()),
            Value::String("cancel".to_owned()),
        ]);
    });
    assert!(
        schema.validate(&layer_with_widened_events).is_err(),
        "widening the submitter-target layer to cancel must fail the schema: {layer_with_widened_events:#?}"
    );

    // The events run in the order the machine raises them, so a reordered list
    // is a reordered machine even though every name in it is legal.
    let layer_with_reordered_events = lifecycle(&|machine| {
        let events = machine["enforcement"][0]["events"]
            .as_array_mut()
            .expect("events");
        events.reverse();
    });
    assert!(
        schema.validate(&layer_with_reordered_events).is_err(),
        "reversing a layer's event list must fail the schema: {layer_with_reordered_events:#?}"
    );
}

/// An enforcement layer id is a machine-matched name, so it is lowercase
/// kebab-case, and the contract refuses the snake_case spelling of each one.
#[test]
fn lifecycle_contract_refuses_a_snake_case_layer_id() {
    let report = explain_lifecycle_report();
    let schema = load_schema("LifecycleExplanation");
    let explanation = &report["explanation"];
    assert!(
        schema.is_valid(explanation),
        "the lifecycle report satisfies LifecycleExplanation"
    );
    let layers = explanation["lifecycles"][0]["enforcement"]
        .as_array()
        .expect("enforcement array");
    assert_eq!(layers.len(), 21);
    for (index, layer) in layers.iter().enumerate() {
        let id = layer["id"].as_str().expect("layer id");
        assert!(!id.contains('_'), "layer id {id} is not kebab-case");
        let earlier = id.replace('-', "_");
        assert_ne!(earlier, id, "layer id {id} has one spelling only");
        let mut document = explanation.clone();
        document["lifecycles"][0]["enforcement"][index]["id"] = Value::String(earlier.clone());
        assert!(
            !schema.is_valid(&document),
            "LifecycleExplanation accepts the earlier layer id {earlier}"
        );
    }
}

/// An identifier an explanation carries is a local identifier, and its
/// contract refuses a value outside that grammar. The registry project already
/// holds every authored identifier to it, so the output is unchanged.
#[test]
fn each_contract_refuses_an_identifier_outside_the_local_grammar() {
    let cases: &[(&str, &str, &str, &[&str])] = &[
        (
            "model",
            "products/breg/acceptance/asset-site-placement",
            "ModelExplanation",
            &["/moduleClosure/0/id"],
        ),
        (
            "actions",
            "products/breg/fixtures/asset-registration-actions",
            "ActionsExplanation",
            &["/actions/0/id", "/actions/0/effects/0/id"],
        ),
        (
            "change-requests",
            "products/breg/acceptance/asset-site-placement-change-requests",
            "ChangeRequestsExplanation",
            &["/requests/0/effects/0/id"],
        ),
        (
            "access",
            "products/breg/fixtures/consent-person-registry",
            "AccessExplanation",
            &["/consent/organizations/0/id", "/consent/groups/0/id"],
        ),
    ];
    for (subject, fixture, kind, pointers) in cases {
        let explanation = explain(subject, &fixture_path(fixture));
        let schema = load_schema(kind);
        assert!(schema.is_valid(&explanation), "{fixture} satisfies {kind}");
        for pointer in *pointers {
            for outside in ["Not An Id", "9lives", "a.b", ""] {
                let mut document = explanation.clone();
                let member = document
                    .pointer_mut(pointer)
                    .unwrap_or_else(|| panic!("{kind} writes {pointer} for {fixture}"));
                assert!(member.is_string(), "{kind} {pointer} is a string");
                *member = Value::String(outside.to_owned());
                assert!(
                    !schema.is_valid(&document),
                    "{kind} accepts {outside:?} at {pointer}"
                );
            }
        }
    }

    // The module a Rhai planner was declared in is named by its identifier.
    let explanation = explain(
        "change-requests",
        &fixture_path("products/breg/acceptance/person-name-change-rhai"),
    );
    let schema = load_schema("ChangeRequestsExplanation");
    let mut document = explanation.clone();
    document["requests"][0]["planner"]["declaringOrigin"] =
        json!({"type": "module", "id": "people"});
    assert!(
        schema.is_valid(&document),
        "ChangeRequestsExplanation accepts a module origin"
    );
    document["requests"][0]["planner"]["declaringOrigin"]["id"] = json!("Not An Id");
    assert!(
        !schema.is_valid(&document),
        "ChangeRequestsExplanation accepts a module origin that is no identifier"
    );

    // Every lifecycle identifier is pinned to a constant, so no other value
    // reaches the grammar: the contract states the type beside each constant.
    let lifecycle = load_schema_document("LifecycleExplanation");
    let local_id = json!("#/$defs/LocalId");
    assert_eq!(
        lifecycle["$defs"]["LocalId"]["pattern"],
        "^[a-z][a-z0-9_-]{0,63}$"
    );
    let pin = &lifecycle["$defs"]["requestLifecyclePin"]["properties"];
    assert_eq!(pin["id"]["$ref"], local_id);
    for state in pin["states"]["prefixItems"].as_array().expect("states") {
        assert_eq!(state["properties"]["id"]["$ref"], local_id);
    }
    for layer in pin["enforcement"]["prefixItems"]
        .as_array()
        .expect("enforcement layers")
    {
        assert_eq!(layer["properties"]["id"]["$ref"], local_id);
    }
    for definition in ["lifecycle", "enforcementLayer", "state"] {
        assert_eq!(
            lifecycle["$defs"][definition]["properties"]["id"]["$ref"], local_id,
            "LifecycleExplanation types the {definition} id"
        );
    }
}

/// An identifier the compiler derives, a route or operation id, is a
/// dot-separated path of local identifiers, and its contract refuses a value
/// outside that grammar. The compiler composes every such identifier from
/// identifiers the project already holds to the local grammar, so the output
/// is unchanged.
#[test]
fn each_contract_refuses_a_derived_identifier_outside_the_dotted_grammar() {
    let fixture = fixture_path("products/breg/fixtures/asset-registration-actions");
    let routes = explain("routes", &fixture);
    let action_route = routes["routes"]
        .as_array()
        .expect("routes")
        .iter()
        .position(|route| route["type"] == "action")
        .expect("the fixture declares an action route");
    let cases = [
        (
            "RoutesExplanation",
            routes,
            format!("/routes/{action_route}/id"),
        ),
        (
            "QueriesExplanation",
            explain("queries", &fixture),
            "/operations/0/id".to_owned(),
        ),
        (
            "ActionsExplanation",
            explain("actions", &fixture),
            "/actions/0/routes/0/id".to_owned(),
        ),
    ];
    for (kind, explanation, pointer) in cases {
        let schema = load_schema(kind);
        assert!(
            schema.is_valid(&explanation),
            "the fixture satisfies {kind}"
        );
        let document = load_schema_document(kind);
        assert_eq!(
            document["$defs"]["DerivedId"]["pattern"],
            "^[a-z][a-z0-9_-]{0,63}(\\.[a-z][a-z0-9_-]{0,63})+$",
            "{kind} defines the derived grammar"
        );
        let written = explanation
            .pointer(&pointer)
            .and_then(Value::as_str)
            .unwrap_or_else(|| panic!("{kind} writes {pointer}"));
        assert!(written.contains('.'), "{kind} {pointer} is a dotted path");
        for outside in [
            "Not.An.Id",
            "records",
            "records..list",
            "records.9lives",
            "",
        ] {
            let mut mutated = explanation.clone();
            *mutated
                .pointer_mut(&pointer)
                .expect("the member is present") = Value::String(outside.to_owned());
            assert!(
                !schema.is_valid(&mutated),
                "{kind} accepts {outside:?} at {pointer}"
            );
        }
    }
}

/// The JSON pointers of every union an actions explanation writes: the source
/// of each target, and the binding, the field mutations, and the values of
/// each effect.
fn action_union_pointers(explanation: &Value) -> Vec<String> {
    let mut pointers = Vec::new();
    let actions = explanation["actions"].as_array().expect("actions array");
    for (action_index, action) in actions.iter().enumerate() {
        let action_pointer = format!("/actions/{action_index}");
        let targets = action["targets"].as_array().expect("targets array");
        for (target_index, target) in targets.iter().enumerate() {
            if target.get("source").is_some() {
                pointers.push(format!("{action_pointer}/targets/{target_index}/source"));
            }
        }
        let permissions = action["permissions"].as_array().expect("permissions array");
        for (permission_index, permission) in permissions.iter().enumerate() {
            let targets = permission["targets"].as_array().expect("targets array");
            for target_index in 0..targets.len() {
                pointers.push(format!(
                    "{action_pointer}/permissions/{permission_index}/targets/{target_index}/source"
                ));
            }
        }
        let effects = action["effects"].as_array().expect("effects array");
        for (effect_index, effect) in effects.iter().enumerate() {
            let effect_pointer = format!("{action_pointer}/effects/{effect_index}");
            pointers.push(format!("{effect_pointer}/target/binding"));
            let fields = effect["fields"].as_array().expect("fields array");
            for (field_index, field) in fields.iter().enumerate() {
                pointers.push(format!("{effect_pointer}/fields/{field_index}"));
                if field.get("value").is_some() {
                    pointers.push(format!("{effect_pointer}/fields/{field_index}/value"));
                }
            }
        }
    }
    pointers
}

/// Asserts the union at `pointer` is tagged by a kebab-case `type`, and that
/// `schema` refuses the same document tagged by `kind` or by the snake_case
/// spelling of the tag. Returns the tag.
fn assert_union_is_tagged_by_type(
    kind: &str,
    schema: &JSONSchema,
    explanation: &Value,
    pointer: &str,
) -> String {
    let union = explanation
        .pointer(pointer)
        .and_then(Value::as_object)
        .unwrap_or_else(|| panic!("{kind} writes an object at {pointer}"));
    let tag = union
        .get("type")
        .and_then(Value::as_str)
        .unwrap_or_else(|| panic!("{kind} tags {pointer} with type"))
        .to_owned();
    assert!(
        !union.contains_key("kind"),
        "{kind} writes no kind at {pointer}"
    );
    assert!(!tag.contains('_'), "{kind} tag {tag} is kebab-case");

    let mut document = explanation.clone();
    let member = document
        .pointer_mut(pointer)
        .and_then(Value::as_object_mut)
        .expect("union object");
    let value = member.remove("type").expect("type member");
    member.insert("kind".to_owned(), value);
    assert!(
        !schema.is_valid(&document),
        "{kind} accepts {pointer} tagged by kind"
    );

    let earlier = tag.replace('-', "_");
    if earlier != tag {
        let mut document = explanation.clone();
        document.pointer_mut(pointer).expect("union object")["type"] = Value::String(earlier);
        assert!(
            !schema.is_valid(&document),
            "{kind} accepts the snake_case tag at {pointer}"
        );
    }
    tag
}

/// Every union an actions or routes explanation writes is tagged by `type`
/// with a kebab-case value, and the contract refuses the `kind` tag and the
/// snake_case values.
#[test]
fn actions_and_routes_contracts_refuse_a_union_tagged_by_kind() {
    let schema = load_schema("ActionsExplanation");
    let mut tags = std::collections::BTreeSet::new();
    for fixture in [
        "products/breg/fixtures/household-contact-actions",
        "products/breg/acceptance/person-registration-rhai",
    ] {
        let explanation = explain("actions", &fixture_path(fixture));
        assert_matches_contract(fixture, "ActionsExplanation", &explanation);
        let pointers = action_union_pointers(&explanation);
        assert!(!pointers.is_empty(), "{fixture} writes unions");
        for pointer in pointers {
            tags.insert(assert_union_is_tagged_by_type(
                "ActionsExplanation",
                &schema,
                &explanation,
                &pointer,
            ));
        }
    }
    assert_eq!(
        tags.into_iter().collect::<Vec<_>>(),
        [
            "computed",
            "create",
            "effect",
            "existing",
            "from-effect",
            "from-input",
            "input",
            "set"
        ]
    );

    let schema = load_schema("RoutesExplanation");
    let fixture = "products/breg/fixtures/household-contact-actions";
    let explanation = explain("routes", &fixture_path(fixture));
    assert_matches_contract(fixture, "RoutesExplanation", &explanation);
    let routes = explanation["routes"].as_array().expect("routes array");
    let mut tags = std::collections::BTreeSet::new();
    for index in 0..routes.len() {
        tags.insert(assert_union_is_tagged_by_type(
            "RoutesExplanation",
            &schema,
            &explanation,
            &format!("/routes/{index}"),
        ));
    }
    assert_eq!(tags.into_iter().collect::<Vec<_>>(), ["action", "entity"]);
}

/// What an actions explanation states about a handler, its evidence, and a
/// requirement is a set of constants, each written in kebab-case, and the
/// contract refuses the snake_case spelling of every one it pins.
#[test]
fn actions_contract_refuses_a_snake_case_handler_constant() {
    let schema = load_schema("ActionsExplanation");
    let mut pinned_values = std::collections::BTreeSet::new();
    let mut unpinned = 0;
    for fixture in [
        "products/breg/acceptance/person-registration-rhai",
        "products/breg/acceptance/farmer-landholding-evidence",
    ] {
        let explanation = explain("actions", &fixture_path(fixture));
        assert_matches_contract(fixture, "ActionsExplanation", &explanation);
        let actions = explanation["actions"].as_array().expect("actions array");
        for (action_index, action) in actions.iter().enumerate() {
            let mut statements = Vec::new();
            if action.get("handler").is_some() {
                for (member, pinned) in [
                    ("inputKeys", true),
                    ("omittedSlots", false),
                    ("evaluation", false),
                    ("reads", true),
                    ("replay", true),
                ] {
                    statements.push((format!("/actions/{action_index}/handler/{member}"), pinned));
                }
            }
            if action.get("evidence").is_some() {
                for member in ["deadline", "invocation", "disclosure", "lifecycle"] {
                    statements.push((format!("/actions/{action_index}/evidence/{member}"), false));
                }
            }
            let requirements = action
                .get("requires")
                .and_then(Value::as_array)
                .map_or(0, Vec::len);
            for index in 0..requirements {
                statements.push((
                    format!("/actions/{action_index}/requires/{index}/evaluated"),
                    true,
                ));
            }
            for (pointer, pinned) in statements {
                let value = explanation
                    .pointer(&pointer)
                    .and_then(Value::as_str)
                    .unwrap_or_else(|| panic!("{fixture} writes a string at {pointer}"));
                assert!(
                    !value.contains('_'),
                    "{fixture} writes {value} at {pointer}, which is not kebab-case"
                );
                if !pinned {
                    unpinned += 1;
                    continue;
                }
                let mut document = explanation.clone();
                *document.pointer_mut(&pointer).expect("statement") =
                    Value::String(value.replace('-', "_"));
                assert!(
                    !schema.is_valid(&document),
                    "ActionsExplanation accepts the snake_case value at {pointer}"
                );
                pinned_values.insert(value.to_owned());
            }
        }
    }
    assert!(unpinned > 0, "the fixtures write unpinned statements");
    assert_eq!(
        pinned_values.into_iter().collect::<Vec<_>>(),
        [
            "authored-ids",
            "before-effects-under-target-lock",
            "recover-committed-result-without-handler-evaluation",
            "supplied-inputs-only"
        ]
    );
}

/// A queries explanation names each bound of an operation `maximum<Thing>`,
/// and the contract refuses the `max<Thing>` spelling of every one.
#[test]
fn queries_contract_refuses_a_bound_spelled_max() {
    let schema = load_schema("QueriesExplanation");
    let fixture = "products/breg/acceptance/asset-site-placement";
    let explanation = explain("queries", &fixture_path(fixture));
    assert_matches_contract(fixture, "QueriesExplanation", &explanation);
    let operations = explanation["operations"]
        .as_array()
        .expect("operations array");
    assert!(!operations.is_empty(), "{fixture} writes query operations");
    for (index, operation) in operations.iter().enumerate() {
        let bounds = operation["bounds"].as_object().expect("bounds object");
        assert_eq!(
            bounds.keys().map(String::as_str).collect::<Vec<_>>(),
            [
                "maximumFilterDepth",
                "maximumFilterNodes",
                "maximumFilterPayloadBytes",
                "maximumFilterPredicates",
                "maximumInValues",
                "maximumPageSize",
                "maximumSelectedFields",
                "maximumTop"
            ]
        );
        for key in bounds.keys() {
            let mut document = explanation.clone();
            let bounds = document["operations"][index]["bounds"]
                .as_object_mut()
                .expect("bounds object");
            let value = bounds.remove(key).expect("bound");
            bounds.insert(key.replacen("maximum", "max", 1), value);
            assert!(
                !schema.is_valid(&document),
                "QueriesExplanation accepts the max spelling of {key}"
            );
        }
    }
}

/// An actions explanation reports how long an accepted assertion is retained
/// in days, the unit every retention in the stack is written in, and the
/// contract refuses the member spelled in seconds.
#[test]
fn actions_contract_refuses_an_evidence_retention_in_seconds() {
    let schema = load_schema("ActionsExplanation");
    let fixture = "products/breg/acceptance/farmer-landholding-evidence";
    let explanation = explain("actions", &fixture_path(fixture));
    assert_matches_contract(fixture, "ActionsExplanation", &explanation);
    let actions = explanation["actions"].as_array().expect("actions array");
    let mut checked = 0;
    for (index, action) in actions.iter().enumerate() {
        let Some(evidence) = action.get("evidence").and_then(Value::as_object) else {
            continue;
        };
        assert_eq!(evidence.get("retentionDays"), Some(&json!(1)));
        assert!(!evidence.contains_key("retentionSeconds"));

        let mut document = explanation.clone();
        let evidence = document["actions"][index]["evidence"]
            .as_object_mut()
            .expect("evidence object");
        evidence.remove("retentionDays");
        evidence.insert("retentionSeconds".to_owned(), json!(86_400));
        assert!(
            !schema.is_valid(&document),
            "ActionsExplanation accepts retentionSeconds"
        );
        checked += 1;
    }
    assert!(checked > 0, "{fixture} writes action evidence");
}

/// The access explanation and the access preview spell their own constants
/// in kebab-case: every claim contract error the engine can report, and the
/// preview's `mode` and `recordAccess`. Each contract refuses the snake_case
/// spelling.
#[test]
fn access_contracts_refuse_a_snake_case_constant() {
    use registry_breg::authority::AuthorityInventoryError;

    let schema = load_schema("AccessExplanation");
    let fixture = "products/breg/examples/access-review";
    let explanation = explain("access", &fixture_path(fixture));
    assert_matches_contract(fixture, "AccessExplanation", &explanation);
    assert!(explanation["claimContractError"].is_null());
    let errors = [
        AuthorityInventoryError::PrincipalClaimMissing,
        AuthorityInventoryError::TargetEntityNotCompiled,
        AuthorityInventoryError::BoundaryFieldNotCompiled,
        AuthorityInventoryError::LookupSelectorNotCompiled,
        AuthorityInventoryError::LookupClaimMappingIncomplete,
        AuthorityInventoryError::LookupFieldNotCompiled,
        AuthorityInventoryError::ConflictingClaimExpectation,
    ];
    for error in errors {
        let written = serde_json::to_value(error).expect("claim contract error serializes");
        let word = written.as_str().expect("claim contract error is a string");
        assert!(
            !word.contains('_'),
            "the engine writes claimContractError {word}, which is not kebab-case"
        );
        let mut document = explanation.clone();
        document["claimContractError"] = written.clone();
        assert!(
            schema.is_valid(&document),
            "AccessExplanation refuses claimContractError {word}"
        );
        document["claimContractError"] = json!(word.replace('-', "_"));
        assert!(
            !schema.is_valid(&document),
            "AccessExplanation accepts a snake_case claimContractError for {word}"
        );
    }

    let schema = load_schema("AccessPreview");
    let project = fixture_path(fixture);
    for (name, relative) in ACCESS_SCENARIOS {
        let preview = explain_with_scenario(&project, &repo_root().join(relative));
        assert_matches_contract(name, "AccessPreview", &preview);
        assert_eq!(preview["mode"], json!("offline-synthetic"), "{name}");
        assert_eq!(preview["recordAccess"], json!("not-evaluated"), "{name}");
        for (member, old) in [
            ("mode", "offline_synthetic"),
            ("recordAccess", "not_evaluated"),
        ] {
            let mut document = preview.clone();
            document[member] = json!(old);
            assert!(
                !schema.is_valid(&document),
                "AccessPreview accepts {member} {old}"
            );
        }
    }
}

/// The JSON pointers of every tagged union a change-requests explanation
/// writes: the planner, its declaring origin, the target of each possible
/// write, and the binding, the field mutations, and the values of each
/// effect.
fn change_request_union_pointers(explanation: &Value) -> Vec<String> {
    let mut pointers = Vec::new();
    let requests = explanation["requests"].as_array().expect("requests array");
    for (request_index, request) in requests.iter().enumerate() {
        let request_pointer = format!("/requests/{request_index}");
        pointers.push(format!("{request_pointer}/planner"));
        let planner = &request["planner"];
        if planner.get("declaringOrigin").is_some() {
            pointers.push(format!("{request_pointer}/planner/declaringOrigin"));
        }
        if let Some(writes) = planner.get("possibleWrites").and_then(Value::as_array) {
            for write_index in 0..writes.len() {
                pointers.push(format!(
                    "{request_pointer}/planner/possibleWrites/{write_index}/target"
                ));
            }
        }
        let effects = request["effects"].as_array().expect("effects array");
        for (effect_index, effect) in effects.iter().enumerate() {
            let effect_pointer = format!("{request_pointer}/effects/{effect_index}");
            pointers.push(format!("{effect_pointer}/target/binding"));
            let fields = effect["fields"].as_array().expect("fields array");
            for (field_index, field) in fields.iter().enumerate() {
                pointers.push(format!("{effect_pointer}/fields/{field_index}"));
                if field.get("value").is_some() {
                    pointers.push(format!("{effect_pointer}/fields/{field_index}/value"));
                }
            }
        }
    }
    pointers
}

/// Collects into `tags` the constant every schema node under `node` pins for
/// a `type` member, and fails on a node that pins a `kind` member.
fn collect_schema_union_tags(
    node: &Value,
    pointer: &str,
    tags: &mut std::collections::BTreeSet<String>,
) {
    match node {
        Value::Object(members) => {
            if let Some(properties) = members.get("properties").and_then(Value::as_object) {
                assert!(
                    !properties.contains_key("kind"),
                    "ChangeRequestsExplanation pins a kind member at {pointer}"
                );
                if let Some(tag) = properties
                    .get("type")
                    .and_then(|member| member.get("const"))
                    .and_then(Value::as_str)
                {
                    tags.insert(tag.to_owned());
                }
            }
            for (name, member) in members {
                collect_schema_union_tags(member, &format!("{pointer}/{name}"), tags);
            }
        }
        Value::Array(items) => {
            for (index, item) in items.iter().enumerate() {
                collect_schema_union_tags(item, &format!("{pointer}/{index}"), tags);
            }
        }
        _ => {}
    }
}

/// Every tagged union a change-requests explanation writes is tagged by
/// `type` with a kebab-case value, and the contract refuses the `kind` tag
/// and the snake_case values, including the variants no tracked project
/// writes.
#[test]
fn change_requests_contract_refuses_a_union_tagged_by_kind() {
    let schema = load_schema("ChangeRequestsExplanation");
    let mut tags = std::collections::BTreeSet::new();
    for fixture in [
        "products/breg/acceptance/publicschema-household-change-requests",
        "products/breg/acceptance/person-name-change-rhai",
    ] {
        let explanation = explain("change-requests", &fixture_path(fixture));
        assert_matches_contract(fixture, "ChangeRequestsExplanation", &explanation);
        let pointers = change_request_union_pointers(&explanation);
        assert!(!pointers.is_empty(), "{fixture} writes unions");
        for pointer in pointers {
            tags.insert(assert_union_is_tagged_by_type(
                "ChangeRequestsExplanation",
                &schema,
                &explanation,
                &pointer,
            ));
        }
    }
    assert_eq!(
        tags.into_iter().collect::<Vec<_>>(),
        [
            "declarative",
            "existing",
            "from-effect",
            "from-field",
            "project",
            "reserved-create",
            "rhai",
            "set"
        ]
    );

    let document = load_schema_document("ChangeRequestsExplanation");
    let mut pinned = std::collections::BTreeSet::new();
    collect_schema_union_tags(
        &document["properties"]["requests"],
        "/properties/requests",
        &mut pinned,
    );
    assert_eq!(
        pinned.into_iter().collect::<Vec<_>>(),
        [
            "clear",
            "declarative",
            "existing",
            "from-effect",
            "from-field",
            "module",
            "none",
            "project",
            "required",
            "reserved-create",
            "rhai",
            "set"
        ]
    );
}

/// The lifecycle report names no revision, because no project produced it.
/// Every other subject does, so this also asserts the contrast rather than
/// just the absence.
#[test]
fn explain_lifecycle_reports_no_revision_while_other_subjects_do() {
    let report = explain_lifecycle_report();
    assert_eq!(
        report.get("revision"),
        None,
        "explain lifecycle carries no compiled project, so it names no revision: {report:#?}"
    );

    let project = fixture_path("products/breg/acceptance/business-establishments");
    let output = bregctl(&[
        "--format",
        "json",
        "explain",
        "model",
        project.to_str().expect("fixture path is UTF-8"),
    ]);
    let model_report = json_stdout(&output);
    assert!(
        model_report["revision"].is_string(),
        "explain model names the compiled revision: {model_report:#?}"
    );
}

/// `--production` asks for the production package-closure check. This subject
/// compiles nothing and so runs no such check, and reporting
/// `profile: production` anyway would state that a check had passed when it
/// never ran. Refused for the same reason PROJECT is.
#[test]
fn explain_lifecycle_refuses_the_production_profile() {
    let output = bregctl(&["--format", "json", "explain", "lifecycle", "--production"]);
    assert!(
        !output.status.success(),
        "bregctl explain lifecycle --production is refused: {output:?}"
    );
    let report = json_stdout(&output);
    assert_eq!(report["ok"], Value::Bool(false), "{report:#?}");
    assert_eq!(
        report["diagnostics"][0]["code"],
        Value::String("lifecycle.profile.unused".to_owned()),
        "{report:#?}"
    );
}

/// The human lead every other `explain` subject prints announces a compiled
/// inventory. This subject has none, so it must not borrow that sentence.
#[test]
fn explain_lifecycle_does_not_announce_a_compiled_inventory() {
    let output = bregctl(&["explain", "lifecycle"]);
    assert!(
        output.status.success(),
        "bregctl explain lifecycle failed: {output:?}"
    );
    let stdout = String::from_utf8(output.stdout).expect("bregctl writes UTF-8");
    assert!(
        !stdout.contains("Explained the compiled inventory."),
        "explain lifecycle compiles nothing: {stdout}"
    );
    assert!(
        stdout.contains("No project was compiled."),
        "explain lifecycle says so in its lead: {stdout}"
    );
}

/// A PROJECT is refused rather than ignored, so that nothing teaches a reader
/// the lifecycle might vary by project.
#[test]
fn explain_lifecycle_refuses_a_project() {
    let project = fixture_path("products/breg/acceptance/business-establishments");
    let output = bregctl(&[
        "--format",
        "json",
        "explain",
        "lifecycle",
        project.to_str().expect("fixture path is UTF-8"),
    ]);
    assert!(
        !output.status.success(),
        "bregctl explain lifecycle <project> is refused: {output:?}"
    );
    let report = json_stdout(&output);
    assert_eq!(report["ok"], Value::Bool(false), "{report:#?}");
    assert_eq!(
        report["diagnostics"][0]["code"],
        Value::String("lifecycle.project.unused".to_owned()),
        "{report:#?}"
    );
}

/// PROJECT stayed required for every other subject: making it optional in
/// clap moved the refusal from clap to `explain`, it did not remove it.
#[test]
fn explain_refuses_a_missing_project_for_every_other_subject() {
    for subject in [
        "model",
        "access",
        "routes",
        "queries",
        "actions",
        "change-requests",
        "events",
    ] {
        let output = bregctl(&["--format", "json", "explain", subject]);
        assert!(
            !output.status.success(),
            "bregctl explain {subject} with no project is refused: {output:?}"
        );
        let report = json_stdout(&output);
        assert_eq!(
            report["diagnostics"][0]["code"],
            Value::String("explain.project.missing".to_owned()),
            "explain {subject}: {report:#?}"
        );
    }
}

/// Each kind's minimal valid example, registered in
/// `products/platform/config-formats.yaml`, is a committed `explanation`
/// that `bregctl` writes for the access-review example project (with no
/// project for `lifecycle`). An example that drifts from the command's output
/// fails here; the README beside the schemas gives the commands that rewrite
/// every example.
#[test]
fn committed_examples_are_what_explain_writes() {
    let project = fixture_path("products/breg/examples/access-review");
    let written = [
        (
            "model-explanation.json",
            "ModelExplanation",
            explain("model", &project),
        ),
        (
            "access-explanation.json",
            "AccessExplanation",
            explain("access", &project),
        ),
        (
            "access-preview.json",
            "AccessPreview",
            explain_with_scenario(&project, &project.join("allowed.json")),
        ),
        (
            "actions-explanation.json",
            "ActionsExplanation",
            explain("actions", &project),
        ),
        (
            "change-requests-explanation.json",
            "ChangeRequestsExplanation",
            explain("change-requests", &project),
        ),
        (
            "events-explanation.json",
            "EventsExplanation",
            explain("events", &project),
        ),
        (
            "queries-explanation.json",
            "QueriesExplanation",
            explain("queries", &project),
        ),
        (
            "routes-explanation.json",
            "RoutesExplanation",
            explain("routes", &project),
        ),
        (
            "lifecycle-explanation.json",
            "LifecycleExplanation",
            explain_lifecycle_report()["explanation"].clone(),
        ),
    ];
    let examples = repo_root().join("products/breg/examples/formats/explain");
    for (file, kind, explanation) in written {
        let path = examples.join(file);
        let bytes =
            std::fs::read(&path).unwrap_or_else(|error| panic!("example {path:?} reads: {error}"));
        let committed: Value = serde_json::from_slice(&bytes)
            .unwrap_or_else(|error| panic!("example {path:?} parses: {error}"));
        assert_matches_contract(file, kind, &committed);
        assert!(
            committed == explanation,
            "{path:?} is not what `bregctl explain` writes now; rewrite the examples with the \
             commands in products/breg/contracts/explain/README.md"
        );
    }
}

/// Every explain contract refuses the header the nine formats shared before
/// each took its own `apiVersion` and its product-prefixed `kind`.
#[test]
fn each_contract_refuses_the_shared_explain_header() {
    for (file, contract) in [
        ("model-explanation.json", "ModelExplanation"),
        ("access-explanation.json", "AccessExplanation"),
        ("access-preview.json", "AccessPreview"),
        ("actions-explanation.json", "ActionsExplanation"),
        (
            "change-requests-explanation.json",
            "ChangeRequestsExplanation",
        ),
        ("events-explanation.json", "EventsExplanation"),
        ("queries-explanation.json", "QueriesExplanation"),
        ("routes-explanation.json", "RoutesExplanation"),
        ("lifecycle-explanation.json", "LifecycleExplanation"),
    ] {
        let path = repo_root()
            .join("products/breg/examples/formats/explain")
            .join(file);
        let bytes =
            std::fs::read(&path).unwrap_or_else(|error| panic!("example {path:?} reads: {error}"));
        let committed: Value = serde_json::from_slice(&bytes)
            .unwrap_or_else(|error| panic!("example {path:?} parses: {error}"));
        let schema = load_schema(contract);
        assert!(schema.is_valid(&committed), "{file} satisfies {contract}");
        for (member, earlier) in [
            (
                "apiVersion",
                "registry.registrystack.org/breg-explain/v1alpha4",
            ),
            ("kind", contract),
        ] {
            let mut document = committed.clone();
            document[member] = Value::String(earlier.to_owned());
            assert!(
                !schema.is_valid(&document),
                "{contract} accepts the earlier {member}"
            );
        }
    }
}

/// The `breg/ctl-report` format's example is the whole report one `explain`
/// run writes, committed as written.
#[test]
fn committed_report_example_is_what_bregctl_writes() {
    let project = fixture_path("products/breg/examples/access-review");
    let output = bregctl(&[
        "--format",
        "json",
        "explain",
        "actions",
        project.to_str().expect("fixture path is UTF-8"),
    ]);
    assert!(
        output.status.success(),
        "bregctl explain actions {project:?} failed: {output:?}"
    );
    let path = repo_root().join("products/breg/examples/formats/ctl-report.json");
    let committed =
        std::fs::read(&path).unwrap_or_else(|error| panic!("example {path:?} reads: {error}"));
    assert!(
        committed == output.stdout,
        "{path:?} is not what `bregctl --format json explain actions` writes now; rewrite it \
         with the command in products/breg/contracts/explain/README.md"
    );
}
