#!/usr/bin/env python3
import argparse
import html
import os
import socketserver
from http.server import BaseHTTPRequestHandler
from pathlib import Path
from urllib.parse import parse_qs, urlparse


def read_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key] = value
    return values


def quote_env(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def write_callback_env(path: Path, values: dict[str, str]) -> None:
    lines = [
        "# Generated by scripts/capture-esignet-callback.py. Do not edit by hand.",
        f"ESIGNET_AUTHORIZATION_CODE={quote_env(values['code'])}",
    ]
    if values.get("state"):
        lines.append(f"ESIGNET_CALLBACK_STATE={quote_env(values['state'])}")
    if values.get("iss"):
        lines.append(f"ESIGNET_CALLBACK_ISSUER={quote_env(values['iss'])}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


class ReusableTCPServer(socketserver.TCPServer):
    allow_reuse_address = True


def main() -> int:
    parser = argparse.ArgumentParser(description="Capture one eSignet OIDC callback.")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=int(os.environ.get("CITIZEN_WITNESS_PORT", "4325")))
    parser.add_argument("--state-file", default="output/citizen-self-attestation/esignet-pkce.env")
    parser.add_argument("--output", default="output/citizen-self-attestation/esignet-callback.env")
    args = parser.parse_args()

    state_file = Path(args.state_file)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    expected_state = read_env(state_file).get("ESIGNET_STATE", "")

    class Handler(BaseHTTPRequestHandler):
        def log_message(self, format: str, *args: object) -> None:
            return

        def do_GET(self) -> None:
            parsed = urlparse(self.path)
            if parsed.path != "/callback":
                self.send_response(404)
                self.end_headers()
                return

            query = parse_qs(parsed.query)
            code = query.get("code", [""])[0]
            state = query.get("state", [""])[0]
            issuer = query.get("iss", [""])[0]
            error = query.get("error", [""])[0]
            error_description = query.get("error_description", [""])[0]

            if error:
                self._send_page(
                    400,
                    "eSignet returned an error",
                    f"{html.escape(error)} {html.escape(error_description)}",
                    "Return to the terminal and run just citizen-login again.",
                )
                self.server.should_stop = True  # type: ignore[attr-defined]
                return

            if not code:
                self._send_page(
                    400,
                    "Missing authorization code",
                    "The callback did not include a code parameter.",
                    "Return to the terminal and run just citizen-login again.",
                )
                self.server.should_stop = True  # type: ignore[attr-defined]
                return

            if expected_state and state != expected_state:
                self._send_page(
                    400,
                    "State mismatch",
                    "The callback state did not match the saved PKCE state.",
                    "Return to the terminal and run just citizen-login again.",
                )
                self.server.should_stop = True  # type: ignore[attr-defined]
                return

            write_callback_env(output, {"code": code, "state": state, "iss": issuer})
            self._send_page(
                200,
                "Authorization code captured",
                f"Saved the code to {html.escape(str(output))}.",
                "Return to the terminal and run: just citizen-code",
            )
            print(f"Captured eSignet authorization code in {output}")
            self.server.should_stop = True  # type: ignore[attr-defined]

        def _send_page(self, status: int, title: str, detail: str, next_step: str) -> None:
            body = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{html.escape(title)}</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; margin: 3rem; line-height: 1.5; }}
    main {{ max-width: 42rem; }}
    code {{ background: #f3f4f6; padding: 0.125rem 0.25rem; border-radius: 4px; }}
  </style>
</head>
<body>
  <main>
    <h1>{html.escape(title)}</h1>
    <p>{detail}</p>
    <p>{html.escape(next_step)}</p>
  </main>
</body>
</html>
"""
            encoded = body.encode("utf-8")
            self.send_response(status)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(encoded)))
            self.end_headers()
            self.wfile.write(encoded)

    with ReusableTCPServer((args.host, args.port), Handler) as httpd:
        httpd.should_stop = False  # type: ignore[attr-defined]
        print(f"Waiting for eSignet callback on http://{args.host}:{args.port}/callback")
        while not httpd.should_stop:  # type: ignore[attr-defined]
            httpd.handle_request()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
