name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: "24 6 * * 2"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release/1.0

permissions:
  contents: read

jobs:
  scorecard:
    name: Scorecard
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
          submodules: false

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc
        with:
          results_file: scorecard-results.sarif
          results_format: sarif
          publish_results: ${{ github.event_name != 'pull_request' }}
